SymbolicNode
std::atomic<std::size_t> SymbolicNode::cached_hash
Referenced by hash.
std::atomic<bool> SymbolicNode::hash_computed
Referenced by hash.
SymbolicNode::SymbolicNode()=default
SymbolicNode::SymbolicNode(const SymbolicNode &)
virtual int SymbolicNode::compare_same_type(const SymbolicNode &other) const =0
与同类型节点进行比较（由子类实现）。
Referenced by compare, equals.
virtual std::size_t SymbolicNode::compute_hash() const =0
计算当前节点的哈希值（由子类实现）。
Referenced by hash.
SymbolicNode & SymbolicNode::operator=(const SymbolicNode &)
virtual SymbolicNode::~SymbolicNode()=default
virtual void SymbolicNode::accept(SymbolicVisitor &visitor)=0
接受 Visitor 访问。
virtual std::shared_ptr< SymbolicNode > SymbolicNode::clone() const =0
深拷贝当前节点及其子树。
int SymbolicNode::compare(const SymbolicNode &other) const
与另一个节点进行全序比较。
other 待比较的节点 小于返回 -1，等于返回 0，大于返回 1
References compare_same_type, type_priority.
Referenced by VariableNode::compare_same_type, PowerNode::compare_same_type.
bool SymbolicNode::equals(const SymbolicNode &other) const
判断两个节点是否结构相等。
other 待比较的节点 相等返回 true
References compare_same_type, hash, type_priority.
std::size_t SymbolicNode::hash() const
获取节点哈希值（带缓存）。
哈希值
References cached_hash, compute_hash, hash_computed.
Referenced by MatrixNode::compute_hash, equals.
virtual bool SymbolicNode::is_number() const
判断节点是否为数值节点。
virtual bool SymbolicNode::is_one() const
判断节点数值是否为 1。
virtual bool SymbolicNode::is_positive() const
判断节点是否可证明为严格正数（非数值节点默认返回 false）。
virtual bool SymbolicNode::is_zero() const
判断节点数值是否为 0。
Referenced by MatrixNode::compute_hash.
virtual int SymbolicNode::type_priority() const =0
返回节点类型的排序优先级，用于规范化排序。
Referenced by compare, equals.