poly_utils.hpp
bool lamina::contains(const SymbolicExpr &expr, const std::string &var)
判断符号表达式是否包含指定变量
expr 符号表达式 var 变量名 包含该变量返回 true
References lamina::depends_on_var, SymbolicExpr::root.
Referenced by lamina::depends_on_parameters, lamina::ParametricSolver::solve_polynomial_parametric, lamina::Solver::solve_polynomial_system.
bool lamina::depends_on_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
判断符号节点是否依赖指定变量
node 符号节点 var 变量名 包含该变量返回 true
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, RelationalNode::left, LogicalNode::left, VariableNode::name, AddNode::operands, MultiplyNode::operands, RelationalNode::right, LogicalNode::right, MatrixNode::storage.
Referenced by lamina::collect_transcendental_subexprs, lamina::contains, lamina::decompose_exp_base_pattern, lamina::decompose_lambert_w_pattern, lamina::decompose_trig_exp_pattern, lamina::Integrator::depends_on, lamina::depends_on_any_param, lamina::detect_substitution, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::invert_substitution_h, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::rd_is_const_in, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality, lamina::symbolic_to_poly_recursive, lamina::LinearSubstitutionStrategy::try_integrate, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, IntegrationVisitor::visit.
T lamina::extract_coeff_value(const std::shared_ptr< SymbolicExpr > &c)
从符号表达式中提取指定类型的系数值
T 目标系数类型 c 符号表达式 提取的系数值
BigInt lamina::extract_coeff_value< BigInt >(const std::shared_ptr< SymbolicExpr > &c)
References Rational::is_integer, Rational::to_BigInt.
Rational lamina::extract_coeff_value< Rational >(const std::shared_ptr< SymbolicExpr > &c)
References Rational::from_double, lamina::Rational, Rational::simplify.
SymbolicPolyCoeff lamina::extract_coeff_value< SymbolicPolyCoeff >(const std::shared_ptr< SymbolicExpr > &c)
void lamina::gaussian_eliminate(std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &A, size_t m, size_t n, std::vector< size_t > &pivot_col_for_row, int &sign)
对增广矩阵进行高斯消元
A 增广矩阵（符号表达式元素） m 行数 n 列数 pivot_col_for_row 输出各行的主元列号 sign 输出行交换的符号（+1 或 -1）
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power.
Referenced by lamina::Solver::solve_linear_system, SymbolicExpr::solve_system.
std::shared_ptr< SymbolicExpr > lamina::poly_to_symbolic(const Polynomial< T > &poly)
将一元多项式转换为符号表达式
T 系数类型 poly 一元多项式 对应的符号表达式
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::Polynomial< CoeffType >::variable_name.
Referenced by SymbolicExpr::poly_gcd, lamina::solve_numeric.
Polynomial< T > lamina::symbolic_to_poly(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
将符号表达式转换为一元多项式
T 系数类型 expr 符号表达式 var 主变量名 对应的一元多项式
Polynomial< T > lamina::symbolic_to_poly_recursive(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
递归地将符号节点转换为一元多项式
T 系数类型 node 符号节点 var 主变量名 对应的一元多项式
References lamina::depends_on_var, BigInt::IsNegative, BigInt::to_int.