newton_raphson.cpp
std::optional< NumericRoot > lamina::bisection(const std::shared_ptr< SymbolicExpr > &f, const std::string &var, lmmc_real_t lo, lmmc_real_t hi, const SolveOptions &opts)
二分法求根。
f 目标函数表达式 var 求解变量名 lo 区间下界（要求 f(lo) 与 f(hi) 异号） hi 区间上界 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
Referenced by lamina::newton_raphson.
static Rational lamina::cauchy_bound(const Polynomial< Rational > &poly)
References Rational::abs, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, Rational::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Rational.
Referenced by lamina::isolate_real_roots.
static int lamina::count_sign_changes(const std::vector< Rational > &values)
References lamina::Rational.
Referenced by lamina::sturm_sign_changes_at, lamina::sturm_sign_changes_at_neg_inf, lamina::sturm_sign_changes_at_pos_inf.
std::vector< std::pair< Rational, Rational > > lamina::isolate_real_roots(const Polynomial< Rational > &poly)
使用 Sturm 序列隔离有理系数多项式的所有实根。
poly 有理系数多项式 隔离区间列表，每个区间包含恰好一个实根
References lamina::cauchy_bound, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::is_zero, lamina::Rational, lamina::roots_in_interval, lamina::Polynomial< CoeffType >::square_free_part, lamina::Polynomial< CoeffType >::trim.
Referenced by lamina::rootof_evaluate, lamina::solve_numeric.
std::optional< NumericRoot > lamina::newton_raphson(const std::shared_ptr< SymbolicExpr > &f, const std::shared_ptr< SymbolicExpr > &df, const std::string &var, lmmc_real_t x0, const SolveOptions &opts)
Newton-Raphson 迭代求根（无区间约束）。
f 目标函数表达式 df 目标函数的导数表达式 var 求解变量名 x0 迭代初始值 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
Referenced by lamina::rootof_evaluate, lamina::solve_numeric.
std::optional< NumericRoot > lamina::newton_raphson(const std::shared_ptr< SymbolicExpr > &f, const std::shared_ptr< SymbolicExpr > &df, const std::string &var, lmmc_real_t x0, lmmc_real_t bracket_lo, lmmc_real_t bracket_hi, const SolveOptions &opts)
Newton-Raphson 迭代求根（带区间约束，迭代超出区间时回退到二分法）。
f 目标函数表达式 df 目标函数的导数表达式 var 求解变量名 x0 迭代初始值 bracket_lo 搜索区间下界 bracket_hi 搜索区间上界 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References lamina::bisection, lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
static int lamina::roots_in_interval(const std::vector< Polynomial< Rational > > &sturm, const Rational &a, const Rational &b)
References lamina::sturm_sign_changes_at.
Referenced by lamina::isolate_real_roots.
std::vector< NumericRoot > lamina::solve_numeric(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, const SolveOptions &opts={})
对表达式进行数值求根，综合使用 Newton-Raphson 和根隔离方法。
expr 待求根的表达式（视为等于零） var 求解变量名 opts 求解选项（容差、最大迭代次数等） 数值根列表
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, Rational::from_double, lamina::SolveOptions::has_initial_guess, lamina::SolveOptions::initial_guess, lamina::isolate_real_roots, lamina::SolveOptions::max_roots, lamina::newton_raphson, SymbolicExpr::number, lamina::poly_to_symbolic, lamina::Rational, lamina::NumericRoot::residual, lamina::SolveOptions::tolerance, lamina::NumericRoot::value, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::solve_dispatch.
static int lamina::sturm_sign_changes_at(const std::vector< Polynomial< Rational > > &sturm, const Rational &x)
References lamina::count_sign_changes.
Referenced by lamina::roots_in_interval.
static int lamina::sturm_sign_changes_at_neg_inf(const std::vector< Polynomial< Rational > > &sturm)
References lamina::count_sign_changes.
static int lamina::sturm_sign_changes_at_pos_inf(const std::vector< Polynomial< Rational > > &sturm)
References lamina::count_sign_changes.