matcher.cpp
static bool lamina::is_wildcard(const std::shared_ptr< SymbolicNode > &node, const std::unordered_set< std::string > &wildcards, std::string &name_out)
Referenced by lamina::match_recursive.
static bool lamina::match_commutative_recursive(const std::vector< std::shared_ptr< SymbolicNode > > &p_ops, const std::vector< std::shared_ptr< SymbolicNode > > &t_ops, std::vector< bool > &used_t, size_t p_index, const std::unordered_set< std::string > &wildcards, MatchMap &results)
References lamina::match_commutative_recursive, lamina::match_recursive.
Referenced by lamina::match_commutative_recursive, lamina::match_recursive.
static bool lamina::match_recursive(const std::shared_ptr< SymbolicNode > &p_node, const std::shared_ptr< SymbolicNode > &t_node, const std::unordered_set< std::string > &wildcards, MatchMap &results)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, lamina::is_wildcard, lamina::match_commutative_recursive, lamina::match_recursive.
Referenced by lamina::Matcher::match, lamina::match_commutative_recursive, lamina::match_recursive.
SymbolicExpr lamina::wildcard(const std::string &name)
创建通配符表达式
name 通配符名称 表示通配符的符号表达式
References SymbolicFactory::create_variable.
Referenced by lamina::IntegrationTable::load_defaults.