lamina::Matcher
bool lamina::Matcher::match(const SymbolicExpr &pattern, const SymbolicExpr &target, const std::unordered_set< std::string > &wildcards, MatchMap &results)
将模式与目标表达式进行匹配
pattern 模式表达式 target 目标表达式 wildcards 模式中的通配符名称集合 results 匹配成功时输出绑定结果 匹配成功返回 true
References lamina::match_recursive, SymbolicExpr::root.
Referenced by lamina::TableLookupStrategy::try_integrate, lamina::RewriteVisitor::try_match.
SymbolicExpr lamina::Matcher::replace(const SymbolicExpr &template_expr, const MatchMap &bindings, bool use_rest=true)
将绑定结果代入模板表达式
template_expr 模板表达式 bindings 通配符绑定映射 use_rest 是否使用剩余项替换 替换后的表达式
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, lamina::ReplacementVisitor::get_result, SymbolicExpr::root.
Referenced by lamina::TableLookupStrategy::try_integrate, lamina::RewriteVisitor::try_match.