SymbolicExpr
Type
数值
std::shared_ptr<SymbolicNode> SymbolicExpr::root
AST 根节点
Referenced by lamina::RelationStore::add_relation, lamina::RewriteEngine::apply, lamina::InferenceEngine::apply_monotonicity_rules, lamina::RewriteEngine::apply_step, lamina::AssumptionContext::assume, compare, lamina::contains, lamina::Integrator::depends_on, differentiate, expand, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::RationalDecompositionStrategy::extract_rational, lamina::TrigCombinationStrategy::extract_sec_power, lamina::TrigCombinationStrategy::extract_sin_cos_powers, lamina::TrigCombinationStrategy::extract_tan_power, get_identifier, get_number_value, get_operands, get_type, lamina::RelationStore::has_relation, lamina::InferenceEngine::infer_add_domain, lamina::InferenceEngine::infer_add_sign, lamina::InferenceEngine::infer_function_domain, lamina::InferenceEngine::infer_function_property, lamina::InferenceEngine::infer_multiply_domain, lamina::InferenceEngine::infer_multiply_sign, lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property, integrate, lamina::Integrator::integrate_def, lamina::AssumptionContext::is_integer, lamina::AssumptionContext::is_negative, lamina::AssumptionContext::is_nonnegative, lamina::AssumptionContext::is_nonzero, is_one, lamina::AssumptionContext::is_positive, lamina::AssumptionContext::is_real, is_zero, lamina::isolate_linear_coeff, limit, lamina::Integrator::make_integral_node, lamina::Matcher::match, lamina::InferenceEngine::propagate_bounds, lamina::InferenceEngine::query_integer, lamina::QueryInterface::query_integer, lamina::InferenceEngine::query_negative, lamina::QueryInterface::query_negative, lamina::InferenceEngine::query_nonnegative, lamina::QueryInterface::query_nonnegative, lamina::InferenceEngine::query_nonpositive, lamina::InferenceEngine::query_nonzero, lamina::QueryInterface::query_nonzero, lamina::InferenceEngine::query_positive, lamina::QueryInterface::query_positive, lamina::InferenceEngine::query_real, lamina::QueryInterface::query_real, lamina::Matcher::replace, series, simplify, lamina::Solver::solve_linear_system, substitute, to_numeric, lamina::anonymous_namespace{solver.cpp}::to_poly, lamina::anonymous_namespace{solver.cpp}::to_poly, to_string, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::SpecialFunctionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate, lamina::RewriteVisitor::try_match.
SymbolicExpr::SymbolicExpr()
默认构造，根节点为空。
SymbolicExpr::SymbolicExpr(std::shared_ptr< SymbolicNode > node)
从 AST 节点构造表达式。
node AST 根节点
SymbolicExpr::SymbolicExpr(Type t)
int SymbolicExpr::compare(const std::shared_ptr< SymbolicExpr > &other) const
与另一个表达式进行全序比较。
other 待比较的表达式 小于返回负数，等于返回 0，大于返回正数
References root.
::Rational SymbolicExpr::convert_rational() const
将数值表达式转换为 Rational（BigInt 也会转换）。
有理数值，非数值类型返回 Rational(0)
std::shared_ptr< SymbolicExpr > SymbolicExpr::differentiate(const std::string &var_name) const
对表达式关于指定变量求导。
var_name 求导变量名 导数表达式
References DifferentiationVisitor::get_result, NormalizationVisitor::get_result, root.
Referenced by differentiate_legacy, lamina::SubstitutionStrategy::try_integrate, lamina::IBPStrategy::try_integrate, lamina::valid_dependency.
std::shared_ptr< SymbolicExpr > SymbolicExpr::expand() const
展开表达式（分配律展开乘法等）。
展开后的表达式
References ExpandVisitor::get_result, root.
std::shared_ptr< SymbolicExpr > SymbolicExpr::factor() const
对表达式进行因式分解。
因式分解后的表达式
References add, multiply, number, poly_gcd, power, simplify, solve, VariablesVisitor::vars.
Referenced by determinant, poly_resultant, rref.
::BigInt SymbolicExpr::get_big_int() const
获取大整数值。
BigInt 值 std::runtime_error 表达式不是 BigInt 时抛出
std::string SymbolicExpr::get_identifier() const
References root.
int SymbolicExpr::get_int() const
std::variant< int, ::BigInt, ::Rational > SymbolicExpr::get_number() const
获取数值表达式的值。
数值（int、BigInt 或 Rational） std::runtime_error 表达式不是数值时抛出
std::variant< int,::BigInt,::Rational > SymbolicExpr::get_number_value() const
References root.
bool SymbolicExpr::get_number_value_is_zero() const
判断表达式数值是否为零。
std::vector< std::shared_ptr< SymbolicExpr > > SymbolicExpr::get_operands() const
References add, root.
::Rational SymbolicExpr::get_rational() const
获取有理数值。
Rational 值 std::runtime_error 表达式不是 Rational 时抛出
SymbolicExpr::Type SymbolicExpr::get_type() const
References Abs, FunctionNode::Abs, Add, ArcCos, FunctionNode::ArcCos, ArcSin, FunctionNode::ArcSin, ArcTan, FunctionNode::ArcTan, Atan2, FunctionNode::Atan2, Cos, FunctionNode::Cos, FunctionNode::Exp, FunctionNode::LambertW, Ln, FunctionNode::Ln, Log, FunctionNode::Log, Matrix, Multiply, Number, Power, root, Sin, FunctionNode::Sin, Sqrt, FunctionNode::Sqrt, Tan, FunctionNode::Tan, Variable, Vector.
std::shared_ptr< SymbolicExpr > SymbolicExpr::integrate(const std::string &var) const
计算不定积分。
var 积分变量名 积分结果表达式
References lamina::Integrator::integrate, root.
bool SymbolicExpr::is_big_int() const
判断表达式是否为大整数类型。
bool SymbolicExpr::is_int() const
判断表达式是否为整数（包括 BigInt、整数 Rational、近似整数浮点）。
bool SymbolicExpr::is_number() const
判断表达式是否为数值节点。
Referenced by lamina::Integrator::integrate_recursive, lamina::PartialFractionStrategy::try_integrate.
bool SymbolicExpr::is_one() const
判断表达式是否为一。
References eq, root.
bool SymbolicExpr::is_rational() const
判断表达式是否为有理数类型。
bool SymbolicExpr::is_zero() const
判断表达式是否为零。
References eq, root.
Referenced by determinant.
std::shared_ptr< SymbolicExpr > SymbolicExpr::limit(const std::string &var, const std::shared_ptr< SymbolicExpr > &point, const std::string &direction="") const
计算表达式的极限。
var 趋近的变量名 point 趋近的目标值 direction 方向："+"（右极限）、"-"（左极限）、""（双侧） 极限结果表达式
References LimitVisitor::get_result, root.
std::shared_ptr< SymbolicExpr > SymbolicExpr::series(const std::string &var, const std::shared_ptr< SymbolicExpr > &point, int order) const
在指定点展开为泰勒级数。
var 展开变量名 point 展开中心点 order 展开阶数 级数表达式
References add, BigInt::factorial, multiply, number, power, root, variable.
std::shared_ptr< SymbolicExpr > SymbolicExpr::simplify() const
对表达式进行化简。
化简后的表达式
References NormalizationVisitor::get_result, root.
Referenced by lamina::Integrator::apply_linearity, eigenvectors, factor, lamina::Integrator::integrate_def, simplify_trig, lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int, lamina::TableLookupStrategy::try_integrate, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
std::shared_ptr< SymbolicExpr > SymbolicExpr::simplify_trig() const
对表达式进行三角恒等式化简。
化简后的表达式
References add, lamina::RewriteEngine::add_rule, lamina::RewriteEngine::apply, cos, multiply, number, power, simplify, sin.
std::shared_ptr< SymbolicExpr > SymbolicExpr::substitute(const std::string &var_name, const std::shared_ptr< SymbolicExpr > &value) const
将表达式中指定变量替换为给定值。
var_name 变量名 value 替换值 替换后的新表达式
References NormalizationVisitor::get_result, SubstituteVisitor::get_result, root.
Referenced by lamina::Integrator::integrate_def.
lmmc_real_t SymbolicExpr::to_numeric() const
将表达式求值为浮点数。
数值结果
References FunctionNode::Abs, FunctionNode::Atan2, FunctionNode::Cos, FunctionNode::Exp, FunctionNode::LambertW, FunctionNode::Ln, root, FunctionNode::Sin, FunctionNode::Sqrt, FunctionNode::Tan, to_numeric.
Referenced by lamina::Integrator::integrate_def, to_numeric, lamina::PartialFractionStrategy::try_integrate.
std::string SymbolicExpr::to_string() const
将表达式转换为可读字符串。
字符串表示
References PrintVisitor::get_result, root.
Referenced by lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_or_create_aux_var.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::add(std::shared_ptr< SymbolicExpr > left, std::shared_ptr< SymbolicExpr > right)
创建加法表达式。
left 左操作数 right 右操作数 和表达式
Referenced by lamina::arc_length_x, lamina::arc_length_y, lamina::InequalitySolver::build_parametric_solution, charpoly, lamina::complex_abs, lamina::complex_add, lamina::complex_div, lamina::complex_mul, lamina::complex_sub, lamina::compute_determinant, determinant, eigenvectors, factor, lamina::gaussian_eliminate, get_operands, lamina::Integrator::integrate_def, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, lamina::invert_cos, lamina::invert_sin, lamina::invert_substitution_h, lamina::invert_tan, lamina::line_plane_intersection, lamina::IntegrationTable::load_defaults, lamina::matrix_reflection, lamina::SymbolicPolyCoeff::operator+, lamina::SymbolicPolyCoeff::operator-, lamina::SymbolicPolyCoeff::operator==, lamina::point_plane_distance, lamina::poly_to_symbolic, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, lamina::anonymous_namespace{integration.cpp}::rd_var_minus, rref, series, simplify_trig, lamina::skew_lines_distance, solve, lamina::solve_closed_form_from_poly, lamina::solve_complex_quadratic, lamina::solve_cubic, lamina::solve_dispatch, lamina::solve_inner_equation, lamina::solve_linear1_ode, lamina::solve_linear2_ode, lamina::ParametricSolver::solve_linear_parametric, lamina::InequalitySolver::solve_parametric_inequality, solve_polynomial_closed, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::solve_separable_ode, lamina::sub, lamina::sym_sub, lamina::symbolic_poly_to_expr, Irrational::to_symbolic, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::vector_cross, lamina::volume_of_revolution_x, lamina::volume_of_revolution_y.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::atan2(std::shared_ptr< SymbolicExpr > y, std::shared_ptr< SymbolicExpr > x)
创建双参数反正切表达式 atan2(y, x)。
y y 坐标 x x 坐标 atan2 表达式
References FunctionNode::Atan2.
Referenced by lamina::complex_arg.
std::shared_ptr< SymbolicExpr > SymbolicExpr::charpoly(const std::shared_ptr< SymbolicExpr > &mat, const std::string &lambda)
计算矩阵的特征多项式。
mat 矩阵表达式 lambda 特征值变量名 特征多项式表达式
References add, determinant, Matrix, matrix, multiply, number, variable.
Referenced by eigenvalues.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::cos(std::shared_ptr< SymbolicExpr > op)
创建余弦函数表达式。
op 参数表达式 cos(op)
References FunctionNode::Cos.
Referenced by lamina::complex_exp_form, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::make_cos_scaled, simplify_trig, lamina::solve_linear2_ode, lamina::SubstitutionStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > SymbolicExpr::determinant(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵行列式。
mat 矩阵表达式 行列式值
References add, determinant, factor, is_zero, Matrix, matrix, multiply, number, power.
Referenced by charpoly, determinant, lamina::matrix_determinant.
std::shared_ptr< SymbolicExpr > SymbolicExpr::divide(const std::shared_ptr< SymbolicExpr > &num, const std::shared_ptr< SymbolicExpr > &den)
执行符号除法。
num 被除数 den 除数 商表达式
References multiply, number, power.
Referenced by lamina::Integrator::check_cycle, lamina::complex_div, lamina::decompose_trig_exp_pattern, lamina::implicit_diff, lamina::invert_exp_base, lamina::invert_h_power, lamina::line_plane_intersection, lamina::IntegrationTable::load_defaults, lamina::SymbolicPolyCoeff::operator/, lamina::point_plane_distance, lamina::Integrator::resolve_cycle, lamina::skew_lines_distance, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, lamina::solve_cubic, lamina::solve_linear1_ode, lamina::solve_linear2_ode, lamina::solve_linear_internal, lamina::ParametricSolver::solve_linear_parametric, solve_polynomial_closed, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::solve_separable_ode, lamina::solve_symbolic_poly, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > SymbolicExpr::eigenvalues(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵的特征值。
mat 矩阵表达式 特征值列表表达式
References charpoly, matrix, solve.
Referenced by eigenvectors.
std::vector< std::pair< std::shared_ptr< SymbolicExpr >, std::vector< std::shared_ptr< SymbolicExpr > > > > SymbolicExpr::eigenvectors(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵的特征向量。
mat 矩阵表达式 特征值与对应特征向量的列表
References add, eigenvalues, Matrix, matrix, multiply, number, simplify, solve_system, variable, Vector.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::eq(std::shared_ptr< SymbolicExpr > lhs, std::shared_ptr< SymbolicExpr > rhs)
创建等式关系表达式 lhs = rhs。
lhs 左侧表达式 rhs 右侧表达式 等式表达式
References RelationalNode::EQ.
Referenced by lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector, is_one, is_zero, solve, solve_system.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::exp(std::shared_ptr< SymbolicExpr > op)
创建指数函数表达式 e^op。
op 指数参数 exp(op)
References FunctionNode::Exp.
Referenced by lamina::detect_substitution, lamina::invert_ln, lamina::IntegrationTable::load_defaults, lamina::solve_linear1_ode, lamina::solve_linear2_ode, lamina::SubstitutionStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::infinity(int k=1)
创建无穷大表达式。
k 正数表示正无穷，负数表示负无穷 无穷大表达式
References FunctionNode::Infinity, multiply, number.
Referenced by Value::as_symbolic.
std::shared_ptr< SymbolicExpr > SymbolicExpr::integral(std::shared_ptr< SymbolicExpr > op, const std::string &var)
计算表达式关于指定变量的不定积分。
op 被积表达式 var 积分变量名 积分结果
std::shared_ptr< SymbolicExpr > SymbolicExpr::inverse(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵的逆。
mat 矩阵表达式 逆矩阵，不可逆时返回 nullptr
References Matrix, matrix, number, rref.
Referenced by lamina::matrix_inverse.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::lambertw(std::shared_ptr< SymbolicExpr > op)
创建 Lambert W 函数表达式。
op 参数表达式 W(op)
References FunctionNode::LambertW.
Referenced by lamina::invert_lambert_w.
std::shared_ptr< SymbolicExpr > SymbolicExpr::limit_func(std::shared_ptr< SymbolicExpr > op, const std::string &var, std::shared_ptr< SymbolicExpr > target)
计算表达式的极限。
op 表达式 var 趋近变量名 target 趋近目标值 极限结果
static std::shared_ptr< SymbolicExpr > SymbolicExpr::ln(std::shared_ptr< SymbolicExpr > op)
创建自然对数表达式。
op 参数表达式 ln(op)
References FunctionNode::Ln.
Referenced by lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, lamina::invert_exp, lamina::invert_exp_base, lamina::invert_h_exp, lamina::IntegrationTable::load_defaults, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::log(std::shared_ptr< SymbolicExpr > val, std::shared_ptr< SymbolicExpr > base)
创建以指定底数的对数表达式。
val 真数 base 底数 log_base(val)
References FunctionNode::Log.
std::shared_ptr< SymbolicExpr > SymbolicExpr::make_integral(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
创建积分表达式节点（不求值）。
expr 被积表达式 var 积分变量名 积分表达式
References FunctionNode::Calculus_Integral.
std::shared_ptr< SymbolicExpr > SymbolicExpr::make_limit(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, const std::shared_ptr< SymbolicExpr > &point)
创建极限表达式节点（不求值）。
expr 表达式 var 趋近变量名 point 趋近目标值 极限表达式
References FunctionNode::Limit.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::matrix(const std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &elements)
从二维元素列表创建矩阵表达式。
elements 二维表达式数组，elements[i][j] 为第 i 行第 j 列元素 矩阵表达式
Referenced by Value::as_symbolic, charpoly, determinant, eigenvalues, eigenvectors, inverse, lamina::matrix_reflection, lamina::matrix_rotation, lamina::matrix_scaling, rref, transpose.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::multiply(std::shared_ptr< SymbolicExpr > left, std::shared_ptr< SymbolicExpr > right)
创建乘法表达式。
left 左操作数 right 右操作数 乘积表达式
Referenced by lamina::Integrator::apply_linearity, lamina::arc_length_x, lamina::arc_length_y, lamina::InequalitySolver::build_parametric_solution, charpoly, lamina::Integrator::check_cycle, lamina::complex_conj, lamina::complex_div, lamina::complex_exp_form, lamina::complex_mul, lamina::complex_sub, lamina::compute_determinant, lamina::decompose_exp_base_pattern, lamina::decompose_lambert_w_pattern, lamina::decompose_trig_exp_pattern, determinant, divide, eigenvectors, lamina::MultipleIntegralEngine::evaluate, factor, lamina::gaussian_eliminate, lamina::implicit_diff, infinity, lamina::TrigCombinationStrategy::integrate_even_case, lamina::TrigCombinationStrategy::integrate_odd_case, lamina::Integrator::integrate_recursive, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, lamina::invert_cos, lamina::invert_h_power, lamina::invert_sin, lamina::invert_substitution_h, lamina::invert_tan, lamina::line_plane_intersection, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::make_cos_scaled, lamina::anonymous_namespace{integration.cpp}::make_sin_scaled, lamina::matrix_multiply, lamina::matrix_reflection, lamina::matrix_rotation, lamina::multiply_factors, lamina::negate, lamina::SymbolicPolyCoeff::operator*, lamina::SymbolicPolyCoeff::operator-, lamina::SymbolicPolyCoeff::operator-, lamina::SymbolicPolyCoeff::operator==, lamina::point_plane_distance, poly_resultant, lamina::poly_to_symbolic, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, rref, series, simplify_trig, lamina::skew_lines_distance, solve, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, lamina::solve_complex_quadratic, lamina::solve_cubic, lamina::solve_dispatch, lamina::solve_inner_equation, lamina::solve_linear1_ode, lamina::solve_linear2_ode, lamina::ParametricSolver::solve_linear_parametric, lamina::InequalitySolver::solve_parametric_inequality, solve_polynomial_closed, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::solve_separable_ode, lamina::solve_symbolic_poly, solve_system, lamina::sym_sub, lamina::symbolic_poly_to_expr, Irrational::to_symbolic, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::SpecialFunctionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate, lamina::vector_cross, lamina::vector_dot, lamina::volume_of_revolution_x, lamina::volume_of_revolution_y.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::number(const ::BigInt &bi)
创建大整数数值表达式。
bi 大整数 数值表达式
static std::shared_ptr< SymbolicExpr > SymbolicExpr::number(const ::Rational &r)
创建有理数数值表达式。
r 有理数 数值表达式
static std::shared_ptr< SymbolicExpr > SymbolicExpr::number(double n)
创建浮点数值表达式。
n 浮点值 数值表达式
static std::shared_ptr< SymbolicExpr > SymbolicExpr::number(int n)
创建整数数值表达式。
n 整数值 数值表达式
Referenced by lamina::Integrator::apply_linearity, lamina::arc_length_x, lamina::arc_length_y, Value::as_symbolic, lamina::bisection, lamina::InequalitySolver::build_parametric_solution, lamina::cbrt_expr, charpoly, lamina::complex_abs, lamina::complex_conj, lamina::complex_div, lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector, lamina::complex_mul, lamina::complex_sub, lamina::compute_determinant, lamina::decompose_exp_base_pattern, lamina::decompose_lambert_w_pattern, lamina::decompose_trig_exp_pattern, determinant, divide, eigenvectors, lamina::Interval::empty, lamina::extract_constant_term, factor, lamina::find_roots_with_multiplicity, lamina::gaussian_eliminate, get_coeff, lamina::implicit_diff, infinity, lamina::Integrator::integrate_def, lamina::TrigCombinationStrategy::integrate_even_case, lamina::TrigCombinationStrategy::integrate_odd_case, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, inverse, lamina::invert_cos, lamina::invert_h_power, lamina::invert_sin, lamina::invert_substitution_h, lamina::invert_tan, lamina::line_plane_intersection, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::make_cos_scaled, lamina::make_pi, lamina::anonymous_namespace{integration.cpp}::make_sin_scaled, lamina::matrix_reflection, lamina::matrix_rotation, lamina::matrix_scaling, lamina::multiply_factors, lamina::multiply_no_expand, lamina::negate, lamina::newton_raphson, lamina::newton_raphson, lamina::num, lamina::num_r, lamina::SymbolicPolyCoeff::operator-, lamina::SymbolicPolyCoeff::operator-, lamina::SymbolicPolyCoeff::operator==, lamina::parse_numeric_value, lamina::point_plane_distance, poly_gcd, poly_resultant, lamina::poly_to_symbolic, lamina::rational_to_symbolic_poly, lamina::anonymous_namespace{integration.cpp}::rd_num_int, lamina::anonymous_namespace{integration.cpp}::rd_num_rat, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, lamina::anonymous_namespace{integration.cpp}::rd_var_minus, lamina::Integrator::resolve_cycle, root_of, lamina::rootof_evaluate, rref, series, simplify_trig, lamina::skew_lines_distance, solve, lamina::solve_biquadratic, lamina::solve_by_factoring, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, lamina::solve_complex_nth_root, lamina::solve_complex_quadratic, lamina::solve_cubic, lamina::solve_dispatch, lamina::solve_inner_equation, lamina::solve_linear2_ode, lamina::ParametricSolver::solve_linear_parametric, lamina::solve_numeric, lamina::InequalitySolver::solve_parametric_inequality, solve_polynomial_closed, lamina::solve_quartic, lamina::solve_separable_ode, lamina::solve_symbolic_poly, solve_system, lamina::ParametricSolver::solve_system_piecewise, lamina::sym_rational, lamina::sym_sub, lamina::symbolic_poly_to_expr, Irrational::to_symbolic, lamina::anonymous_namespace{integration.cpp}::trig_rational, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::SpecialFunctionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate, lamina::vector_cross, lamina::volume_of_revolution_x, lamina::volume_of_revolution_y.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::number(long long n)
创建 long long 数值表达式。
n 整数值 数值表达式
std::shared_ptr< SymbolicExpr > SymbolicExpr::poly_gcd(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
计算两个多项式表达式的最大公因式。
a 第一个多项式 b 第二个多项式 GCD 表达式
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, lamina::Polynomial< CoeffType >::gcd, RelationalNode::left, LogicalNode::left, VariableNode::name, number, AddNode::operands, MultiplyNode::operands, lamina::poly_to_symbolic, RelationalNode::right, LogicalNode::right.
Referenced by factor.
std::shared_ptr< SymbolicExpr > SymbolicExpr::poly_resultant(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::string &var)
计算两个多项式关于指定变量的结式。
a 第一个多项式 b 第二个多项式 var 消去的变量名 结式表达式
References factor, multiply, number, power.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::power(std::shared_ptr< SymbolicExpr > base, std::shared_ptr< SymbolicExpr > exponent)
创建幂运算表达式。
base 底数 exponent 指数 幂表达式
Referenced by lamina::arc_length_x, lamina::arc_length_y, lamina::cbrt_expr, lamina::complex_abs, lamina::complex_div, determinant, divide, factor, lamina::gaussian_eliminate, lamina::TrigCombinationStrategy::integrate_odd_case, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, lamina::invert_h_power, lamina::IntegrationTable::load_defaults, poly_resultant, lamina::poly_to_symbolic, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, rref, series, simplify_trig, solve, lamina::solve_closed_form_from_poly, lamina::solve_complex_quadratic, lamina::solve_cubic, lamina::InequalitySolver::solve_parametric_inequality, solve_polynomial_closed, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::symbolic_poly_to_expr, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::SpecialFunctionStrategy::try_integrate, lamina::volume_of_revolution_x, lamina::volume_of_revolution_y.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::root_of(std::shared_ptr< SymbolicExpr > poly, const std::string &var, int index)
创建 RootOf 表达式，表示多项式的第 index 个根。
poly 多项式表达式 var 多项式变量名 index 根的索引 RootOf 表达式
References number, FunctionNode::RootOf, variable.
Referenced by lamina::make_rootof_solutions.
std::shared_ptr< SymbolicExpr > SymbolicExpr::rref(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵的行最简阶梯形（RREF）。
mat 矩阵表达式 RREF 矩阵
References add, factor, Matrix, matrix, multiply, number, power, Vector.
Referenced by inverse.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::sin(std::shared_ptr< SymbolicExpr > op)
创建正弦函数表达式。
op 参数表达式 sin(op)
References FunctionNode::Sin.
Referenced by lamina::complex_exp_form, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::make_sin_scaled, simplify_trig, lamina::solve_linear2_ode, lamina::SubstitutionStrategy::try_integrate.
std::vector< std::shared_ptr< SymbolicExpr > > SymbolicExpr::solve(std::shared_ptr< SymbolicExpr > eq, const std::string &var_name)
求解方程，返回指定变量的所有解。
eq 方程表达式（等于零的形式，或 RelationalNode） var_name 求解的变量名 解的列表
References add, eq, RelationalNode::EQ, RelationalNode::GEQ, get_coeff, RelationalNode::GT, RelationalNode::LEQ, RelationalNode::LT, multiply, number, power, lamina::solve_dispatch.
Referenced by eigenvalues, factor, lamina::invert_substitution_h, lamina::solve_inner_equation, lamina::ParametricSolver::solve_polynomial_parametric, lamina::Solver::solve_polynomial_system, lamina::solve_transcendental_impl, lamina::solve_with_assumptions.
std::vector< std::map< std::string, std::shared_ptr< SymbolicExpr > > > SymbolicExpr::solve_system(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns, const std::vector< std::string > &parameters)
求解含参数的方程组。
equations 方程列表（每个表达式等于零） unknowns 未知数变量名列表 parameters 参数变量名列表 解的列表，每个解为变量名到表达式的映射
References lamina::ParametricSolver::solve_system.
std::vector< std::map< std::string, std::shared_ptr< SymbolicExpr > > > SymbolicExpr::solve_system(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &vars)
求解方程组（无参数变量版本）。
equations 方程列表（每个表达式等于零） vars 未知数变量名列表 解的列表，每个解为变量名到表达式的映射
References eq, lamina::gaussian_eliminate, get_coeff, multiply, number.
Referenced by eigenvectors.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::sqrt(std::shared_ptr< SymbolicExpr > operand)
创建平方根表达式，等价于 operand^(1/2)。
operand 被开方数 平方根表达式
Referenced by lamina::arc_length_x, lamina::arc_length_y, lamina::complex_abs, lamina::RationalDecompositionStrategy::integrate_term, lamina::IntegrationTable::load_defaults, lamina::point_plane_distance, lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi, lamina::skew_lines_distance, lamina::solve_biquadratic, lamina::solve_closed_form_from_poly, lamina::solve_complex_quadratic, lamina::solve_cubic, lamina::solve_quadratic_internal, lamina::solve_quartic, Irrational::to_symbolic, lamina::SpecialFunctionStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::tan(std::shared_ptr< SymbolicExpr > op)
创建正切函数表达式。
op 参数表达式 tan(op)
References FunctionNode::Tan.
Referenced by lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::IntegrationTable::load_defaults.
std::shared_ptr< SymbolicExpr > SymbolicExpr::transpose(const std::shared_ptr< SymbolicExpr > &mat)
计算矩阵转置。
mat 矩阵表达式 转置矩阵
References Matrix, matrix, Vector.
static std::shared_ptr< SymbolicExpr > SymbolicExpr::variable(const std::string &name)
创建变量表达式。
name 变量名 变量表达式
Referenced by charpoly, lamina::Integrator::check_cycle, lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector, lamina::detect_substitution, eigenvectors, lamina::Integrator::integrate_def, lamina::Integrator::integrate_recursive, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_sin_m_cos_n, lamina::TrigCombinationStrategy::integrate_tan_power, lamina::RationalDecompositionStrategy::integrate_term, lamina::anonymous_namespace{integration.cpp}::make_cos_scaled, lamina::Integrator::make_integral_node, lamina::anonymous_namespace{integration.cpp}::make_sin_scaled, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, lamina::anonymous_namespace{integration.cpp}::rd_var_minus, root_of, series, lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi, lamina::solve_linear1_ode, lamina::solve_linear2_ode, lamina::ParametricSolver::solve_linear_parametric, lamina::InequalitySolver::solve_parametric_inequality, lamina::ParametricSolver::solve_polynomial_parametric, lamina::Solver::solve_polynomial_system, lamina::symbolic_poly_to_expr, lamina::IntervalUnion::to_expr, Irrational::to_symbolic, lamina::LinearSubstitutionStrategy::try_integrate, lamina::RationalDecompositionStrategy::try_integrate, lamina::SpecialFunctionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > SymbolicExpr::differentiate_legacy(const std::string &var_name) const
References differentiate.