lamina::IntervalUnion
std::vector<Interval> lamina::IntervalUnion::intervals_
Referenced by complement, contains, intersect, intervals, is_empty, is_entire_line, normalize, to_expr, to_string, unite.
lamina::IntervalUnion::IntervalUnion()
Referenced by empty, from_single, parse, unite.
lamina::IntervalUnion::IntervalUnion(std::vector< Interval > intervals)
从区间列表构造并集
intervals 区间列表
References normalize.
IntervalUnion lamina::IntervalUnion::complement() const
求补集
补集结果
References empty, entire_line, intervals_, is_entire_line, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, lamina::Endpoint::neg_inf, lamina::Endpoint::pos_inf, lamina::Interval::upper, lamina::Endpoint::value.
bool lamina::IntervalUnion::contains(double value) const
判断数值是否在并集内
value 待判断的数值 包含返回 true
References intervals_.
IntervalUnion lamina::IntervalUnion::intersect(const IntervalUnion &other) const
与另一个并集求交
other 另一个区间并集 交集结果
References lamina::compare_endpoints_lower, lamina::compare_endpoints_upper, empty, intervals_, lamina::Interval::lower, lamina::Interval::upper.
Referenced by lamina::InequalitySolver::solve_inequalities.
const std::vector< Interval > & lamina::IntervalUnion::intervals() const
获取内部区间列表
区间列表的常引用
References intervals_.
Referenced by parse.
bool lamina::IntervalUnion::is_empty() const
判断并集是否为空
空集返回 true
References intervals_.
Referenced by lamina::InequalitySolver::solve_inequalities.
bool lamina::IntervalUnion::is_entire_line() const
判断并集是否为全实数轴
是全实数轴返回 true
References intervals_.
Referenced by complement.
std::shared_ptr< SymbolicExpr > lamina::IntervalUnion::to_expr(const std::string &var) const
转换为符号表达式
var 变量名 表示该区间并集的符号表达式
References LogicalNode::And, RelationalNode::GEQ, RelationalNode::GT, intervals_, RelationalNode::LEQ, RelationalNode::LT, LogicalNode::Or, SymbolicExpr::variable.
std::string lamina::IntervalUnion::to_string() const
转换为字符串表示
区间并集的字符串形式
References intervals_, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, lamina::Interval::upper, lamina::Endpoint::value.
IntervalUnion lamina::IntervalUnion::unite(const IntervalUnion &other) const
与另一个并集求并
other 另一个区间并集 并集结果
References IntervalUnion, intervals_.
IntervalUnion lamina::IntervalUnion::empty()
构造空集
空的区间并集
References IntervalUnion.
Referenced by lamina::InequalitySolver::build_parametric_solution, complement, intersect, parse, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality.
IntervalUnion lamina::IntervalUnion::entire_line()
构造全实数轴
表示 (-∞, +∞) 的并集
References lamina::Interval::entire_line, from_single.
Referenced by lamina::InequalitySolver::build_parametric_solution, complement, lamina::InequalitySolver::solve_inequalities, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality.
IntervalUnion lamina::IntervalUnion::from_single(const Interval &iv)
从单个区间构造并集
iv 区间 包含单个区间的并集
References IntervalUnion.
Referenced by entire_line.
std::optional< IntervalUnion > lamina::IntervalUnion::parse(const std::string &str)
从字符串解析区间并集
str 字符串表示 解析成功返回并集，失败返回 nullopt
References IntervalUnion, empty, intervals, lamina::parse_single_interval, lamina::skip_ws, lamina::starts_with_at.
void lamina::IntervalUnion::normalize()
References lamina::can_merge, intervals_, lamina::max_upper, lamina::Interval::upper.
Referenced by IntervalUnion.