lamina::QueryInterface
Tribool lamina::QueryInterface::query_positive(const SymbolicExpr &expr) const
Query whether the expression is positive (> 0).
References ctx_, lamina::False, get_infinity_sign, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_positive, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_positive.
Tribool lamina::QueryInterface::query_negative(const SymbolicExpr &expr) const
Query whether the expression is negative (< 0).
References ctx_, lamina::False, get_infinity_sign, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_negative, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_negative.
Tribool lamina::QueryInterface::query_nonnegative(const SymbolicExpr &expr) const
Query whether the expression is non-negative (>= 0).
References ctx_, lamina::False, get_infinity_sign, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_nonnegative, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_nonnegative.
Tribool lamina::QueryInterface::query_real(const SymbolicExpr &expr) const
Query whether the expression is real.
References ctx_, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_real, SymbolicExpr::root, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_real.
Tribool lamina::QueryInterface::query_integer(const SymbolicExpr &expr) const
Query whether the expression is an integer.
References ctx_, lamina::False, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_integer, SymbolicExpr::root, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_integer.
Tribool lamina::QueryInterface::query_nonzero(const SymbolicExpr &expr) const
Query whether the expression is non-zero (!= 0).
References ctx_, is_infinity_node, is_nan_number, is_unhandled_type, lamina::num, lamina::InferenceEngine::query_nonzero, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by lamina::AssumptionContext::is_nonzero.
const AssumptionContext& lamina::QueryInterface::ctx_
Referenced by query_integer, query_negative, query_nonnegative, query_nonzero, query_positive, query_real.
lamina::QueryInterface::QueryInterface(const AssumptionContext &ctx)
Construct a QueryInterface bound to an AssumptionContext.
ctx The AssumptionContext used for property lookups and inference
int lamina::QueryInterface::get_infinity_sign(const std::shared_ptr< SymbolicNode > &node) const
Determine the sign of an infinity expression. Positive infinity: FunctionNode::Infinity directly. Negative infinity: MultiplyNode(-1, FunctionNode::Infinity). Returns +1 for positive infinity, -1 for negative infinity, 0 if indeterminate.
References FunctionNode::Infinity, lamina::num, lamina::Rational.
Referenced by query_negative, query_nonnegative, query_positive.
bool lamina::QueryInterface::is_infinity_node(const std::shared_ptr< SymbolicNode > &node) const
Check if a FunctionNode represents infinity (FuncType::Infinity).
References FunctionNode::Infinity.
Referenced by query_integer, query_negative, query_nonnegative, query_nonzero, query_positive, query_real.
bool lamina::QueryInterface::is_nan_number(const NumberNode &node) const
Check if a NumberNode holds NaN.
References NumberNode::value.
Referenced by query_integer, query_negative, query_nonnegative, query_nonzero, query_positive, query_real.
bool lamina::QueryInterface::is_unhandled_type(const std::shared_ptr< SymbolicNode > &node) const
Check if the root node is a special case that should return Unknown immediately. Returns true if the node is null, MatrixNode, RelationalNode, or LogicalNode.
Referenced by query_integer, query_negative, query_nonnegative, query_nonzero, query_positive, query_real.