monomial_order.hpp
MonomialOrderType
字典序
using lamina::Monomial = typedef std::vector<int>
单项式类型，以整数向量表示各变量的指数
bool lamina::divides_monomial(const Monomial &divisor, const Monomial &target)
判断 divisor 是否整除 target
divisor 除数单项式 target 被除数单项式 divisor 的每个分量都不超过 target 对应分量时返回 true
Referenced by lamina::fglm_convert, lamina::quotient_dimension, lamina::FGLMPoly::reduce.
Monomial lamina::lcm_monomial(const Monomial &a, const Monomial &b)
计算两个单项式的最小公倍单项式
a 第一个单项式 b 第二个单项式 各分量取最大值构成的单项式
int lamina::total_degree(const Monomial &m)
计算单项式的全次数
m 单项式 各分量指数之和
Referenced by lamina::MonomialOrder::compare_deglex, lamina::MonomialOrder::compare_grevlex, lamina::detail::MonomialEnumerator::next.