lamina::RewriteVisitor
bool lamina::RewriteVisitor::changed
Referenced by try_match, visit, visit, visit, visit.
RewriteEngine& lamina::RewriteVisitor::engine
Referenced by try_match.
std::shared_ptr<SymbolicNode> lamina::RewriteVisitor::result
Referenced by get_result, visit, visit, visit, visit, visit, visit, visit, visit, visit.
lamina::RewriteVisitor::RewriteVisitor(RewriteEngine &e)
std::shared_ptr< SymbolicNode > lamina::RewriteVisitor::get_result() const
References result.
Referenced by lamina::RewriteEngine::apply_step.
std::shared_ptr< SymbolicNode > lamina::RewriteVisitor::try_match(std::shared_ptr< SymbolicNode > node)
References changed, engine, lamina::RewriteEngine::get_rules, lamina::Matcher::match, lamina::Matcher::replace, SymbolicExpr::root.
Referenced by visit, visit, visit, visit, visit, visit, visit, visit, visit.
void lamina::RewriteVisitor::visit(AddNode &node) override
References changed, SymbolicFactory::create_add, AddNode::operands, result, try_match.
void lamina::RewriteVisitor::visit(FunctionNode &node) override
References FunctionNode::arguments, changed, result, try_match, FunctionNode::type.
void lamina::RewriteVisitor::visit(LogicalNode &node) override
References LogicalNode::clone, result, try_match.
void lamina::RewriteVisitor::visit(MatrixNode &node) override
References MatrixNode::clone, result, try_match.
void lamina::RewriteVisitor::visit(MultiplyNode &node) override
References changed, SymbolicFactory::create_multiply, MultiplyNode::operands, result, try_match.
void lamina::RewriteVisitor::visit(NumberNode &node) override
References NumberNode::clone, result, try_match.
void lamina::RewriteVisitor::visit(PowerNode &node) override
References PowerNode::base, changed, PowerNode::exponent, result, try_match.
void lamina::RewriteVisitor::visit(RelationalNode &node) override
References RelationalNode::clone, result, try_match.
void lamina::RewriteVisitor::visit(VariableNode &node) override
References VariableNode::clone, result, try_match.
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.