lamina::RelationStore
std::vector<Relation> lamina::RelationStore::relations_
Referenced by add_relation, clear, get_relations, has_relation.
void lamina::RelationStore::add_relation(const SymbolicExpr &lhs, const SymbolicExpr &rhs, RelationalNode::Op op, PropertyStore &prop_store)
Store a relation and optionally derive sign properties.
If the LHS is a single VariableNode and the RHS is a NumberNode with value 0, the corresponding sign property is declared on the PropertyStore. lhs Left-hand side expression rhs Right-hand side expression op Relational operator prop_store PropertyStore to notify for simple variable > 0 patterns
References lamina::PropertyStore::declare_sign, RelationalNode::EQ, RelationalNode::GEQ, RelationalNode::GT, RelationalNode::LEQ, RelationalNode::LT, lamina::Negative, RelationalNode::NEQ, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, relations_, SymbolicExpr::root.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules.
void lamina::RelationStore::clear()
Clear all stored relations (used during scope pop).
References relations_.
const std::vector< Relation > & lamina::RelationStore::get_relations() const
Retrieve all stored relations.
Const reference to the vector of stored relations
References relations_.
Referenced by lamina::collect_power_exponents.
bool lamina::RelationStore::has_relation(const SymbolicExpr &lhs, const SymbolicExpr &rhs, RelationalNode::Op op) const
Check if a specific relation is stored.
Compares LHS, RHS, and operator using structural equality of the AST nodes. lhs Left-hand side expression rhs Right-hand side expression op Relational operator true if the relation is found in the store
References relations_, SymbolicExpr::root.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules.