fglm.hpp
std::vector< FGLMPoly > lamina::fglm_convert(const std::vector< FGLMPoly > &source_basis, const MonomialOrder &source_order, const MonomialOrder &target_order, size_t num_vars)
FGLM 算法：将零维理想的 Gröbner 基从源序转换到目标序
source_basis 源序下的 Gröbner 基 source_order 源单项式序 target_order 目标单项式序 num_vars 变量个数 目标序下的 Gröbner 基 std::runtime_error 理想非零维或维数过大时抛出
References lamina::FGLMPoly::add_term, lamina::detail::GaussianEliminator::add_vector, lamina::divides_monomial, lamina::FGLMPoly::from_monomial, lamina::FGLMPoly::is_zero, lamina::is_zero_dimensional, lamina::FGLMPoly::LC, lamina::FGLMPoly::LM, lamina::detail::MonomialEnumerator::next, lamina::normal_form, lamina::FGLMPoly::normalize, lamina::quotient_dimension, lamina::Rational, lamina::FGLMPoly::sort_terms, lamina::FGLMPoly::terms.
Referenced by lamina::grevlex_to_lex.
std::vector< FGLMPoly > lamina::grevlex_to_lex(const std::vector< FGLMPoly > &grevlex_basis, size_t num_vars)
将 GrevLex 序下的 Gröbner 基转换为 Lex 序
grevlex_basis GrevLex 序下的 Gröbner 基 num_vars 变量个数 Lex 序下的 Gröbner 基
References lamina::fglm_convert, lamina::MonomialOrder::grevlex, lamina::MonomialOrder::lex.
bool lamina::is_zero_dimensional(const std::vector< FGLMPoly > &basis, size_t num_vars)
判断理想是否为零维（每个变量都有纯幂次首项）
basis Gröbner 基 num_vars 变量个数 零维返回 true
References lamina::FGLMPoly::LM.
Referenced by lamina::fglm_convert.
FGLMPoly lamina::normal_form(const FGLMPoly &f, const std::vector< FGLMPoly > &basis, const MonomialOrder &order)
计算多项式关于基的标准形（余式）
f 待约化多项式 basis Gröbner 基 order 单项式序 标准形
References lamina::FGLMPoly::reduce.
Referenced by lamina::fglm_convert.
std::vector< Rational > lamina::detail::poly_to_vector(const FGLMPoly &p, std::vector< Monomial > &all_monomials, std::map< Monomial, size_t > &monomial_index)
将多项式转换为坐标向量（相对于单项式基）
p 多项式 all_monomials 单项式基（可能被扩展） monomial_index 单项式到索引的映射 坐标向量
References lamina::FGLMPoly::terms.
int lamina::quotient_dimension(const std::vector< FGLMPoly > &basis, size_t num_vars, int max_degree=50)
计算商空间维数（标准单项式个数）
basis Gröbner 基 num_vars 变量个数 max_degree 搜索的最大次数上限 商空间维数；无法确定时返回 -1
References lamina::divides_monomial.
Referenced by lamina::fglm_convert.