lamina::anonymous_namespace{solver.cpp}::PolyBuilder
std::unordered_map<size_t, std::shared_ptr<SymbolicNode> >* lamina::anonymous_namespace{solver.cpp}::PolyBuilder::aux_to_node
std::vector<std::string>& lamina::anonymous_namespace{solver.cpp}::PolyBuilder::ext_vars
Poly lamina::anonymous_namespace{solver.cpp}::PolyBuilder::result
bool lamina::anonymous_namespace{solver.cpp}::PolyBuilder::strict_mode
std::unordered_map<std::string, size_t>& lamina::anonymous_namespace{solver.cpp}::PolyBuilder::transcendental_map
std::vector<std::string> lamina::anonymous_namespace{solver.cpp}::PolyBuilder::vars
bool lamina::anonymous_namespace{solver.cpp}::PolyBuilder::failed
Referenced by visit, visit, visit.
size_t lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_or_create_aux_var(const std::shared_ptr< SymbolicNode > &node)
References SymbolicExpr::to_string.
lamina::anonymous_namespace{solver.cpp}::PolyBuilder::PolyBuilder(const std::vector< std::string > &v, PolyContext &ctx, bool strict=false)
lamina::anonymous_namespace{solver.cpp}::PolyBuilder::PolyBuilder(const std::vector< std::string > &v, std::vector< std::string > &ext_v, std::unordered_map< std::string, size_t > &trans_map, bool strict=false)
lamina::anonymous_namespace{solver.cpp}::PolyBuilder::PolyBuilder(const std::vector< std::string > &v, std::vector< std::string > &ext_v, std::unordered_map< std::string, size_t > &trans_map, std::unordered_map< size_t, std::shared_ptr< SymbolicNode > > *aux_map, bool strict=false)
Poly lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_result() const
Referenced by lamina::anonymous_namespace{solver.cpp}::to_poly, lamina::anonymous_namespace{solver.cpp}::to_poly, visit, visit, visit.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(AddNode &node) override
References lamina::anonymous_namespace{solver.cpp}::add_poly, lamina::anonymous_namespace{solver.cpp}::Poly::add_term, failed, get_result, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, AddNode::operands, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(FunctionNode &node) override
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, FunctionNode::arguments, lamina::depends_on_var, SymbolicExpr::simplify, FunctionNode::type.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(LogicalNode &node) override
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(MatrixNode &node) override
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(MultiplyNode &node) override
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, failed, get_result, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, MultiplyNode::operands, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(NumberNode &node) override
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, NumberNode::value.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(PowerNode &node) override
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, PowerNode::base, PowerNode::exponent, failed, get_result, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(RelationalNode &node) override
void lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit(VariableNode &node) override
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, VariableNode::name.
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.