SymbolicFactory
std::shared_ptr< SymbolicNode > SymbolicFactory::create_add(std::vector< std::shared_ptr< SymbolicNode > > ops)
创建加法节点，自动扁平化嵌套加法并消除零项。
ops 操作数列表 简化后的节点
References create_number.
Referenced by lamina::detect_substitution, lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::isolate_linear_coeff, lamina::match_recursive, lamina::Matcher::replace, lamina::rewrite_exp_as_u_power, lamina::Solver::solve_linear_system, DifferentiationVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, DifferentiationVisitor::visit, DifferentiationVisitor::visit, DifferentiationVisitor::visit.
std::shared_ptr< SymbolicNode > SymbolicFactory::create_multiply(std::vector< std::shared_ptr< SymbolicNode > > ops)
创建乘法节点，自动扁平化嵌套乘法并消除单位元。
ops 操作数列表 简化后的节点
References create_number.
Referenced by lamina::decompose_trig_exp_pattern, lamina::detect_substitution, lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::isolate_linear_coeff, lamina::match_recursive, lamina::Matcher::replace, lamina::rewrite_exp_as_u_power, lamina::Solver::solve_linear_system, DifferentiationVisitor::visit, DifferentiationVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, DifferentiationVisitor::visit, NormalizationVisitor::visit.
std::shared_ptr< SymbolicNode > SymbolicFactory::create_number(const ::BigInt &v)
创建大整数数值节点。
Referenced by lamina::collect_denominator_factors, create_add, create_multiply, create_power, lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::isolate_linear_coeff, lamina::Solver::solve_linear_system, DifferentiationVisitor::visit, DifferentiationVisitor::visit, DifferentiationVisitor::visit, DifferentiationVisitor::visit, DifferentiationVisitor::visit.
std::shared_ptr< SymbolicNode > SymbolicFactory::create_number(const ::Rational &v)
创建有理数数值节点。
std::shared_ptr< SymbolicNode > SymbolicFactory::create_number(lmmc_real_t v)
创建浮点数值节点。
std::shared_ptr< SymbolicNode > SymbolicFactory::create_power(std::shared_ptr< SymbolicNode > base, std::shared_ptr< SymbolicNode > exponent)
创建幂运算节点，自动处理指数为 0/1 及底数为 0/1 的情况。
base 底数节点 exponent 指数节点 简化后的节点
References create_number.
Referenced by lamina::collect_denominator_factors, lamina::detect_substitution, lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::rewrite_exp_as_u_power.
std::shared_ptr< SymbolicNode > SymbolicFactory::create_variable(const std::string &name)
创建变量节点。
Referenced by lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::isolate_linear_coeff, lamina::Solver::solve_linear_system, lamina::wildcard.