inequality_solver.cpp
static bool lamina::depends_on_any_param(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &parameters)
References lamina::depends_on_var.
Referenced by lamina::InequalitySolver::solve_parametric_inequality.
static int lamina::determine_leading_sign(const Polynomial< SymbolicPolyCoeff > &poly)
References lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::num.
Referenced by lamina::InequalitySolver::build_sign_chart, lamina::InequalitySolver::solve_rational_inequality.
static std::vector< std::pair< std::shared_ptr< SymbolicExpr >, int > > lamina::find_roots_with_multiplicity(const std::shared_ptr< SymbolicExpr > &expr, const std::string &variable)
References SymbolicExpr::number, lamina::Rational, lamina::solve_by_factoring, lamina::square_free_factorization, Rational::to_double.
Referenced by lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_rational_inequality.
static bool lamina::root_less_than(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
Referenced by lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality.
static bool lamina::roots_equal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
Referenced by lamina::InequalitySolver::select_intervals, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_rational_inequality.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_symbolic_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &variable)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, lamina::solve_by_factoring.
Referenced by lamina::InequalitySolver::solve_parametric_inequality.