lamina::IntegrationTable
Category
多项式
std::unordered_map<int, std::vector<IntegrationEntry> > lamina::IntegrationTable::entries_
Referenced by add_entry, clear_category, get_all_sorted, get_entries.
const std::vector< IntegrationEntry > lamina::IntegrationTable::empty_entries_
Referenced by get_entries.
lamina::IntegrationTable::IntegrationTable()
References load_defaults.
void lamina::IntegrationTable::add_entry(Category cat, const IntegrationEntry &entry)
向指定类别添加积分规则
cat 规则类别 entry 积分条目
References entries_.
Referenced by load_defaults.
void lamina::IntegrationTable::clear_category(Category cat)
清空指定类别的所有规则
cat 规则类别
References entries_.
std::vector< const IntegrationEntry * > lamina::IntegrationTable::get_all_sorted() const
获取所有规则，按优先级排序
排序后的积分条目指针列表
References entries_.
Referenced by lamina::TableLookupStrategy::try_integrate.
const std::vector< IntegrationEntry > & lamina::IntegrationTable::get_entries(Category cat) const
获取指定类别的所有规则
cat 规则类别 该类别下的积分条目列表
References empty_entries_, entries_.
void lamina::IntegrationTable::load_defaults()
加载默认积分规则表
References SymbolicExpr::add, add_entry, Algebraic, SymbolicExpr::cos, lamina::depends_on_var, SymbolicExpr::divide, SymbolicExpr::exp, Exponential, Hyperbolic, InverseTrig, SymbolicExpr::ln, Logarithmic, lamina::make_expr_ptr, SymbolicExpr::multiply, SymbolicExpr::number, Polynomial, SymbolicExpr::power, SymbolicExpr::sin, SymbolicExpr::sqrt, lamina::sym_rational, lamina::sym_sub, SymbolicExpr::tan, Trigonometric, lamina::wildcard.
Referenced by IntegrationTable.