Irrational
Type
平方根形式 coeff * √radicand
lmmc_real_t Irrational::coefficient
Referenced by constant, e, operator*, operator*, pi, pow, sqrt, to_complex, to_double, to_string, to_symbolic.
std::map<std::string, lmmc_real_t> Irrational::coefficients
Referenced by is_rational, operator*, operator*, operator+, operator-, operator/, simplify, to_complex, to_double, to_string, to_symbolic.
lmmc_real_t Irrational::constant_term
Referenced by constant, e, operator*, operator*, operator+, operator-, operator/, pi, simplify, sqrt, to_complex, to_double, to_string, to_symbolic.
long long Irrational::radicand
Referenced by constant, e, operator*, pi, pow, sqrt, to_complex, to_double, to_string, to_symbolic.
Type Irrational::type
Referenced by constant, e, get_type, is_rational, operator*, operator*, operator/, pi, pow, simplify, sqrt, to_complex, to_double, to_string, to_symbolic.
Irrational::Irrational()
默认构造，初始化为零值的 COMPLEX 类型
Irrational Irrational::abs() const
取绝对值
绝对值无理数对象
References is_negative.
Type Irrational::get_type() const
获取无理数的内部类型
类型枚举值
References type.
bool Irrational::is_negative() const
判断是否为负数
若数值小于零则返回 true
References e, to_double.
Referenced by abs.
bool Irrational::is_positive() const
判断是否为正数
若数值大于零则返回 true
References e, to_double.
bool Irrational::is_rational() const
判断是否可精确表示为有理数
若为纯常数项（无无理部分）则返回 true
References coefficients, COMPLEX, type.
bool Irrational::is_zero() const
判断是否为零
若数值近似为零则返回 true
References e, to_double.
Irrational Irrational::operator*(const Irrational &other) const
References coefficient, coefficients, COMPLEX, constant, constant_term, radicand, SQRT, sqrt, to_double, type.
Irrational Irrational::operator*(lmmc_real_t scalar) const
References coefficient, coefficients, COMPLEX, constant_term, type.
Irrational Irrational::operator+(const Irrational &other) const
References coefficients, constant_term, to_complex.
Irrational Irrational::operator-() const
Irrational Irrational::operator-(const Irrational &other) const
References coefficients, constant_term, to_complex.
Irrational Irrational::operator/(const Irrational &other) const
References coefficients, COMPLEX, constant, constant_term, e, to_double, type.
bool Irrational::operator<(const Irrational &other) const
References to_double.
bool Irrational::operator<=(const Irrational &other) const
bool Irrational::operator==(const Irrational &other) const
References to_double.
bool Irrational::operator>(const Irrational &other) const
bool Irrational::operator>=(const Irrational &other) const
Irrational Irrational::pow(int exponent) const
计算整数次幂
exponent 指数 幂运算结果
References coefficient, constant, e, radicand, SQRT, to_double, type.
void Irrational::simplify()
化简，移除系数为零的项
References coefficients, COMPLEX, constant_term, e, type.
void Irrational::to_complex()
将当前无理数转换为 COMPLEX 线性组合形式
References coefficient, coefficients, COMPLEX, constant_term, E, PI, radicand, SQRT, type.
Referenced by operator+, operator-.
lmmc_real_t Irrational::to_double() const
转换为浮点数近似值
双精度浮点近似
References _irrational_sqrt, coefficient, coefficients, COMPLEX, constant_term, E, LMMC_E, LOG, PI, radicand, SQRT, type.
Referenced by is_negative, is_positive, is_zero, operator*, operator/, operator<, operator==, pow.
std::string Irrational::to_string() const
转换为可读字符串（如 "2√3"、"π/2"）
格式化字符串
References coefficient, coefficients, COMPLEX, constant_term, E, e, LOG, PI, radicand, SQRT, type.
std::shared_ptr< SymbolicExpr > Irrational::to_symbolic() const
将无理数转换为符号表达式
对应的符号表达式
References SymbolicExpr::add, coefficient, coefficients, COMPLEX, constant_term, E, e, Rational::from_double, LOG, SymbolicExpr::multiply, SymbolicExpr::number, PI, radicand, SQRT, SymbolicExpr::sqrt, type, SymbolicExpr::variable.
Referenced by Value::as_symbolic.
static std::pair< long long, long long > Irrational::simplify_sqrt(long long n)
Referenced by sqrt.
static Irrational Irrational::constant(lmmc_real_t value)
构造有理常数（退化为有理数的无理数表示）
value 常数值 常数无理数对象
References coefficient, COMPLEX, constant_term, radicand, type.
Referenced by operator*, operator/, pow.
static Irrational Irrational::e(lmmc_real_t coeff=1.0)
构造 e 的倍数
coeff 系数，默认为 1.0 coeff * e
References coefficient, constant_term, E, radicand, type.
Referenced by is_negative, is_positive, is_zero, operator/, pow, simplify, to_string, to_symbolic.
static Irrational Irrational::pi(lmmc_real_t coeff=1.0)
构造 π 的倍数
coeff 系数，默认为 1.0 coeff * π
References coefficient, constant_term, PI, radicand, type.
static Irrational Irrational::sqrt(long long n, lmmc_real_t coeff=1.0)
构造平方根形式无理数 coeff * √n
n 被开方数 coeff 系数，默认为 1.0 化简后的无理数对象
References coefficient, constant_term, radicand, simplify_sqrt, SQRT, type.
Referenced by operator*.
std::ostream & operator<<(std::ostream &os, const Irrational &ir)