var annotated_dup =
[
    [ "lmmc_coo_sort_entry_t", "sparse_8c.html#structlmmc__coo__sort__entry__t", "sparse_8c_structlmmc__coo__sort__entry__t" ],
    [ "lmmc_eigen_gen_full_result_t", "eigen_8h.html#structlmmc__eigen__gen__full__result__t", "eigen_8h_structlmmc__eigen__gen__full__result__t" ],
    [ "lmmc_eigen_gen_result_t", "eigen_8h.html#structlmmc__eigen__gen__result__t", "eigen_8h_structlmmc__eigen__gen__result__t" ],
    [ "lmmc_eigen_sym_result_t", "eigen_8h.html#structlmmc__eigen__sym__result__t", "eigen_8h_structlmmc__eigen__sym__result__t" ],
    [ "lmmc_interp_akima_t", "interp_8c.html#structlmmc__interp__akima__t", "interp_8c_structlmmc__interp__akima__t" ],
    [ "lmmc_interp_cspline_t", "interp_8c.html#structlmmc__interp__cspline__t", "interp_8c_structlmmc__interp__cspline__t" ],
    [ "lmmc_interp_lagrange_t", "interp_8c.html#structlmmc__interp__lagrange__t", "interp_8c_structlmmc__interp__lagrange__t" ],
    [ "lmmc_interp_pchip_t", "interp_8c.html#structlmmc__interp__pchip__t", "interp_8c_structlmmc__interp__pchip__t" ],
    [ "lmmc_itersolve_config_t", "itersolve_8h.html#structlmmc__itersolve__config__t", "itersolve_8h_structlmmc__itersolve__config__t" ],
    [ "lmmc_itersolve_result_t", "itersolve_8h.html#structlmmc__itersolve__result__t", "itersolve_8h_structlmmc__itersolve__result__t" ],
    [ "lmmc_mat_t", "dense_8h.html#structlmmc__mat__t", "dense_8h_structlmmc__mat__t" ],
    [ "lmmc_nonlinear_config_t", "nonlinear_8h.html#structlmmc__nonlinear__config__t", "nonlinear_8h_structlmmc__nonlinear__config__t" ],
    [ "lmmc_nonlinear_result_t", "nonlinear_8h.html#structlmmc__nonlinear__result__t", "nonlinear_8h_structlmmc__nonlinear__result__t" ],
    [ "lmmc_ode_config_t", "ode_8h.html#structlmmc__ode__config__t", "ode_8h_structlmmc__ode__config__t" ],
    [ "lmmc_ode_result_t", "ode_8h.html#structlmmc__ode__result__t", "ode_8h_structlmmc__ode__result__t" ],
    [ "lmmc_optimize_config_t", "optimize_8h.html#structlmmc__optimize__config__t", "optimize_8h_structlmmc__optimize__config__t" ],
    [ "lmmc_optimize_result_t", "optimize_8h.html#structlmmc__optimize__result__t", "optimize_8h_structlmmc__optimize__result__t" ],
    [ "lmmc_precond_ilu_impl_t", "precond_8c.html#structlmmc__precond__ilu__impl__t", "precond_8c_structlmmc__precond__ilu__impl__t" ],
    [ "lmmc_precond_t", "precond_8h.html#structlmmc__precond__t", "precond_8h_structlmmc__precond__t" ],
    [ "lmmc_quad_result_t", "quadrature_8h.html#structlmmc__quad__result__t", "quadrature_8h_structlmmc__quad__result__t" ],
    [ "lmmc_rng_t", "random_8c.html#structlmmc__rng__t", "random_8c_structlmmc__rng__t" ],
    [ "lmmc_sparse_bsr_t", "sparse_8h.html#structlmmc__sparse__bsr__t", "sparse_8h_structlmmc__sparse__bsr__t" ],
    [ "lmmc_sparse_builder_t", "sparse_8c.html#structlmmc__sparse__builder__t", "sparse_8c_structlmmc__sparse__builder__t" ],
    [ "lmmc_sparse_chol_t", "sparse__direct_8c.html#structlmmc__sparse__chol__t", "sparse__direct_8c_structlmmc__sparse__chol__t" ],
    [ "lmmc_sparse_coo_t", "sparse_8h.html#structlmmc__sparse__coo__t", "sparse_8h_structlmmc__sparse__coo__t" ],
    [ "lmmc_sparse_lu_t", "sparse__direct_8c.html#structlmmc__sparse__lu__t", "sparse__direct_8c_structlmmc__sparse__lu__t" ],
    [ "lmmc_sparse_mat_t", "sparse_8h.html#structlmmc__sparse__mat__t", "sparse_8h_structlmmc__sparse__mat__t" ],
    [ "lmmc_sparse_sym_csr_t", "sparse_8h.html#structlmmc__sparse__sym__csr__t", "sparse_8h_structlmmc__sparse__sym__csr__t" ],
    [ "lmmc_svd_result_t", "eigen_8h.html#structlmmc__svd__result__t", "eigen_8h_structlmmc__svd__result__t" ],
    [ "lmmc_tensor_nd_t", "tensor_8h.html#structlmmc__tensor__nd__t", "tensor_8h_structlmmc__tensor__nd__t" ],
    [ "lmmc_tensor_t", "tensor_8h.html#structlmmc__tensor__t", "tensor_8h_structlmmc__tensor__t" ],
    [ "lmmc_vec_t", "dense_8h.html#structlmmc__vec__t", "dense_8h_structlmmc__vec__t" ],
    [ "ode_implicit_euler_ctx_t", "ode_8c.html#structode__implicit__euler__ctx__t", "ode_8c_structode__implicit__euler__ctx__t" ],
    [ "ode_sdirk_stage_ctx_t", "ode_8c.html#structode__sdirk__stage__ctx__t", "ode_8c_structode__sdirk__stage__ctx__t" ],
    [ "ode_trapezoidal_ctx_t", "ode_8c.html#structode__trapezoidal__ctx__t", "ode_8c_structode__trapezoidal__ctx__t" ]
];