MatrixNode
using MatrixNode::DenseStorage = std::vector<std::shared_ptr<SymbolicNode> >
稠密存储（按行优先展开）
using MatrixNode::SparseStorage = std::map<size_t, std::shared_ptr<SymbolicNode> >
稀疏存储（索引 -> 节点）
const size_t MatrixNode::cols
列数
Referenced by clone, compare_same_type, compute_hash, get, DifferentiationVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, SubstituteVisitor::visit.
const size_t MatrixNode::rows
行数
Referenced by clone, compare_same_type, compute_hash, get, DifferentiationVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, SubstituteVisitor::visit.
const std::variant<DenseStorage, SparseStorage> MatrixNode::storage
实际存储
Referenced by clone, compute_hash, lamina::depends_on_var, lamina::expr_has_free_variables, get, is_sparse, DifferentiationVisitor::visit, NormalizationVisitor::visit, SubstituteVisitor::visit.
std::variant< MatrixNode::DenseStorage, MatrixNode::SparseStorage > MatrixNode::create_storage_from_grid(const std::vector< std::vector< std::shared_ptr< SymbolicNode > > > &grid, size_t total_elements, size_t ncols)
根据稀疏度选择存储方式，从二维网格创建存储。
grid 二维节点网格 total_elements 总元素数 ncols 列数 稠密或稀疏存储
static size_t MatrixNode::validate_grid_columns(const std::vector< std::vector< std::shared_ptr< SymbolicNode > > > &grid)
验证并返回网格的列数（要求各行列数一致）。
grid 二维节点网格 列数 std::invalid_argument 各行列数不一致时抛出
MatrixNode::MatrixNode(const std::vector< std::vector< std::shared_ptr< SymbolicNode > > > &grid)
MatrixNode::MatrixNode(size_t r, size_t c, DenseStorage dense)
MatrixNode::MatrixNode(size_t r, size_t c, SparseStorage sparse)
void MatrixNode::accept(SymbolicVisitor &visitor) override
接受 Visitor 访问。
References SymbolicVisitor::visit.
std::shared_ptr< SymbolicNode > MatrixNode::clone() const override
深拷贝当前节点及其子树。
References cols, rows, storage.
Referenced by ExpandVisitor::visit, LimitVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, IntegrationVisitor::visit.
int SymbolicNode::compare(const SymbolicNode &other) const
与另一个节点进行全序比较。
other 待比较的节点 小于返回 -1，等于返回 0，大于返回 1
References SymbolicNode::compare_same_type, SymbolicNode::type_priority.
Referenced by VariableNode::compare_same_type, PowerNode::compare_same_type.
bool SymbolicNode::equals(const SymbolicNode &other) const
判断两个节点是否结构相等。
other 待比较的节点 相等返回 true
References SymbolicNode::compare_same_type, SymbolicNode::hash, SymbolicNode::type_priority.
std::shared_ptr< SymbolicNode > MatrixNode::get(size_t r, size_t c) const
获取指定位置的矩阵元素。
r 行索引（从 0 开始） c 列索引（从 0 开始） 对应节点，越界返回 nullptr，稀疏缺失返回零节点
References cols, rows, storage.
Referenced by compare_same_type, PrintVisitor::visit.
std::size_t SymbolicNode::hash() const
获取节点哈希值（带缓存）。
哈希值
References SymbolicNode::cached_hash, SymbolicNode::compute_hash, SymbolicNode::hash_computed.
Referenced by compute_hash, SymbolicNode::equals.
virtual bool SymbolicNode::is_number() const
判断节点是否为数值节点。
virtual bool SymbolicNode::is_one() const
判断节点数值是否为 1。
virtual bool SymbolicNode::is_positive() const
判断节点是否可证明为严格正数（非数值节点默认返回 false）。
bool MatrixNode::is_sparse() const
判断当前矩阵是否使用稀疏存储。
References storage.
virtual bool SymbolicNode::is_zero() const
判断节点数值是否为 0。
Referenced by compute_hash.
int MatrixNode::type_priority() const override
返回节点类型的排序优先级，用于规范化排序。
Referenced by compute_hash.
int MatrixNode::compare_same_type(const SymbolicNode &other) const override
与同类型节点进行比较（由子类实现）。
References cols, get, rows.
std::size_t MatrixNode::compute_hash() const override
计算当前节点的哈希值（由子类实现）。
References cols, SymbolicNode::hash, hash_combine, SymbolicNode::is_zero, rows, storage, type_priority.
std::atomic<std::size_t> SymbolicNode::cached_hash
Referenced by SymbolicNode::hash.
std::atomic<bool> SymbolicNode::hash_computed
Referenced by SymbolicNode::hash.