inference_engine.cpp
static std::vector< int > lamina::collect_power_exponents(const RelationStore &store, const std::string &lhs_name, const std::string &rhs_name)
Helper: collect positive integer exponents that appear in PowerNode expressions within the RelationStore involving the given variable names.
References lamina::RelationStore::get_relations, lamina::is_positive_integer_number, BigInt::to_string.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules.
static std::optional< double > lamina::endpoint_to_double(const Endpoint &ep)
Helper: extract a numeric double value from an Endpoint.
Returns std::nullopt if the endpoint is not a finite numeric value.
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::InferenceEngine::propagate_bounds.
static bool lamina::is_even_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds an even integer value.
References BigInt::is_even, lamina::is_integer_number, lamina::num.
Referenced by lamina::InferenceEngine::infer_power_property.
static bool lamina::is_exponent_neg_one(const std::shared_ptr< SymbolicNode > &node)
Helper: check if an exponent NumberNode is exactly -1 (for division detection).
References lamina::num, lamina::Rational.
Referenced by lamina::InferenceEngine::propagate_bounds.
static bool lamina::is_exponent_two(const std::shared_ptr< SymbolicNode > &node)
Helper: check if an exponent NumberNode is exactly 2 (for squaring detection).
References lamina::num, lamina::Rational.
Referenced by lamina::InferenceEngine::propagate_bounds.
static bool lamina::is_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds an integer value.
Works for BigInt (always integer), Rational (if denominator == 1), and double (if finite and equal to its floor).
References lamina::num.
Referenced by lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property, lamina::is_even_integer_number, lamina::is_positive_integer_number.
static bool lamina::is_positive_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds a positive integer value (> 0).
References lamina::is_integer_number, BigInt::IsNegative, lamina::num.
Referenced by lamina::collect_power_exponents, lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property.
static bool lamina::is_zero_number(const NumberNode &num)
Helper: check if a NumberNode holds the value 0.
References lamina::num.
Referenced by lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property.
static Endpoint lamina::make_closed_endpoint(double val)
Helper: create a closed Endpoint from a double value.
References lamina::Endpoint::closed.
Referenced by lamina::make_interval.
static Interval lamina::make_interval(double lo, double hi)
Helper: create an Interval from two double values [lo, hi].
References lamina::Interval::lower, lamina::make_closed_endpoint, lamina::Interval::upper.
Referenced by lamina::InferenceEngine::propagate_bounds.