DifferentiationVisitor
std::string DifferentiationVisitor::var
Referenced by visit.
bool DifferentiationVisitor::implicit_mode
是否为隐函数求导模式
std::string DifferentiationVisitor::implicit_var
隐函数因变量名
std::shared_ptr<SymbolicNode> DifferentiationVisitor::result
求导结果节点
Referenced by get_result, lamina::implicit_diff, visit, visit, visit, visit, visit, visit, visit.
DifferentiationVisitor::DifferentiationVisitor(const std::string &v)
构造普通求导访问器
v 求导变量名
DifferentiationVisitor::DifferentiationVisitor(const std::string &v, const std::string &implicit_v)
构造隐函数求导访问器
v 自变量名 implicit_v 隐函数因变量名
std::shared_ptr< SymbolicNode > DifferentiationVisitor::get_result() const
获取求导结果
求导后的 AST 节点
References result.
Referenced by SymbolicExpr::differentiate, LimitVisitor::visit, LimitVisitor::visit.
void DifferentiationVisitor::visit(AddNode &node) override
References SymbolicFactory::create_add, AddNode::operands, result.
void DifferentiationVisitor::visit(FunctionNode &node) override
References FunctionNode::ArcCos, FunctionNode::ArcSin, FunctionNode::ArcTan, FunctionNode::arguments, FunctionNode::Ci, FunctionNode::Cos, FunctionNode::Cosh, FunctionNode::Cot, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, FunctionNode::Csc, FunctionNode::Ei, FunctionNode::Erf, FunctionNode::Exp, FunctionNode::LambertW, FunctionNode::Li, FunctionNode::Ln, result, FunctionNode::RootOf, FunctionNode::Sec, FunctionNode::Si, FunctionNode::Sin, FunctionNode::Sinh, FunctionNode::Sqrt, FunctionNode::Tan, FunctionNode::Tanh, FunctionNode::type.
virtual void SymbolicVisitor::visit(LogicalNode &node)
void DifferentiationVisitor::visit(MatrixNode &node) override
References MatrixNode::cols, result, MatrixNode::rows, MatrixNode::storage.
void DifferentiationVisitor::visit(MultiplyNode &node) override
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, MultiplyNode::operands, result.
void DifferentiationVisitor::visit(NumberNode &node) override
References SymbolicFactory::create_number, result.
void DifferentiationVisitor::visit(PowerNode &node) override
References PowerNode::base, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, PowerNode::exponent, FunctionNode::Ln, result.
virtual void SymbolicVisitor::visit(RelationalNode &node)
void DifferentiationVisitor::visit(VariableNode &node) override
References SymbolicFactory::create_number, VariableNode::name, result, var.
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.