root_of_utils.hpp
std::vector< std::shared_ptr< SymbolicExpr > > lamina::make_rootof_solutions(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
为不可约多项式构造 RootOf 解表达式列表。
poly 符号系数多项式 var 求解变量名 RootOf 表达式列表，每个元素对应多项式的一个根
References lamina::Polynomial< CoeffType >::degree, SymbolicExpr::root_of, lamina::symbolic_poly_to_expr.
Referenced by lamina::solve_by_factoring, lamina::solve_dispatch.
std::optional< lmmc_real_t > lamina::rootof_evaluate(const std::shared_ptr< SymbolicExpr > &rootof_expr)
对 RootOf 表达式进行数值求值。
rootof_expr RootOf 符号表达式 若求值成功则返回数值结果，否则返回 nullopt
References lamina::isolate_real_roots, lamina::SolveOptions::max_newton_iterations, lamina::newton_raphson, SymbolicExpr::number, FunctionNode::RootOf, lamina::SolveOptions::tolerance, lamina::try_convert_to_rational_poly.
std::shared_ptr< SymbolicExpr > lamina::rootof_simplify(const std::shared_ptr< SymbolicExpr > &rootof_expr)
化简 RootOf 表达式（如可用根式表示则转换为闭式）。
rootof_expr RootOf 符号表达式 化简后的符号表达式
References FunctionNode::RootOf, lamina::rootof_simplify, lamina::solve_closed_form_from_poly, lamina::sort_roots_by_convention.
Referenced by lamina::rootof_simplify.