lamina::Polynomial
std::vector<CoeffType> lamina::Polynomial< CoeffType >::coeffs
系数数组，coeffs[i] 为 x^i 的系数
Referenced by lamina::cauchy_bound, lamina::Polynomial< CoeffType >::content, lamina::convert_to_rational_poly, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::eval, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::RationalDecompositionStrategy::extract_rational, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::gcd, get_coeff, lamina::RationalDecompositionStrategy::integrate_term, lamina::Polynomial< CoeffType >::is_zero, lamina::isolate_real_roots, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Polynomial< CoeffType >::make_monic, lamina::Polynomial< CoeffType >::operator*, lamina::Polynomial< CoeffType >::operator+, lamina::Polynomial< CoeffType >::operator-, lamina::operator<<, lamina::Polynomial< CoeffType >::operator==, lamina::poly_to_symbolic, lamina::Polynomial< CoeffType >::primitive_part, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::rational_to_symbolic_poly, lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, lamina::RationalDecompositionStrategy::solve_coefficients, lamina::solve_numeric, lamina::InequalitySolver::solve_parametric_inequality, lamina::solve_symbolic_poly, lamina::symbolic_poly_to_expr, lamina::Polynomial< CoeffType >::to_string, lamina::Polynomial< CoeffType >::trim, lamina::try_convert_to_rational_poly, lamina::RationalDecompositionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate.
std::string lamina::Polynomial< CoeffType >::variable_name
变量名
Referenced by lamina::convert_to_rational_poly, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::RationalDecompositionStrategy::factor_denominator, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::make_monic, lamina::Polynomial< CoeffType >::operator*, lamina::Polynomial< CoeffType >::operator+, lamina::Polynomial< CoeffType >::operator-, lamina::operator<<, lamina::Polynomial< CoeffType >::operator==, lamina::poly_to_symbolic, lamina::Polynomial< CoeffType >::primitive_part, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::rational_to_symbolic_poly, lamina::RationalDecompositionStrategy::solve_coefficients, lamina::solve_numeric, lamina::symbolic_poly_to_expr, lamina::Polynomial< CoeffType >::to_string, lamina::try_convert_to_rational_poly, lamina::RationalDecompositionStrategy::try_integrate.
lamina::Polynomial< CoeffType >::Polynomial(const CoeffType &c, const std::string &var="x")
从单个常数构造常数多项式
c 常数值 var 变量名
References lamina::Polynomial< CoeffType >::trim.
lamina::Polynomial< CoeffType >::Polynomial(const std::string &var="x")
构造零多项式
var 变量名，默认 "x"
lamina::Polynomial< CoeffType >::Polynomial(const std::vector< CoeffType > &c, const std::string &var="x")
从系数向量构造多项式
c 系数向量（升幂排列） var 变量名
References lamina::Polynomial< CoeffType >::trim.
CoeffType lamina::Polynomial< CoeffType >::content() const
计算多项式的容度（所有系数的 GCD）
容度值
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::gcd_coeff, lamina::Polynomial< CoeffType >::is_zero.
Referenced by lamina::Polynomial< CoeffType >::gcd, lamina::Polynomial< CoeffType >::primitive_part.
int lamina::Polynomial< CoeffType >::degree() const
获取多项式的次数
次数；零多项式返回 -1
References lamina::Polynomial< CoeffType >::coeffs.
Referenced by lamina::cauchy_bound, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::RationalDecompositionStrategy::extract_rational, lamina::RationalDecompositionStrategy::factor_denominator, lamina::find_rational_roots, get_coeff, lamina::RationalDecompositionStrategy::integrate_term, lamina::isolate_real_roots, lamina::make_rootof_solutions, lamina::operator<<, lamina::Polynomial< CoeffType >::operator==, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad, lamina::solve_by_factoring, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, lamina::RationalDecompositionStrategy::solve_coefficients, lamina::solve_numeric, lamina::InequalitySolver::solve_parametric_inequality, solve_polynomial_closed, lamina::solve_symbolic_poly, lamina::square_free_factorization, lamina::Polynomial< CoeffType >::square_free_part, lamina::symbolic_poly_to_expr, lamina::Polynomial< CoeffType >::to_string, lamina::RationalDecompositionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate.
Polynomial lamina::Polynomial< CoeffType >::differentiate() const
求导
导多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::isolate_real_roots, lamina::solve_numeric, lamina::square_free_factorization, lamina::Polynomial< CoeffType >::square_free_part.
std::pair< Polynomial, Polynomial > lamina::Polynomial< CoeffType >::div_mod(const Polynomial &other) const
多项式带余除法
other 除数多项式 pair(商, 余数) std::runtime_error 除数为零多项式时抛出
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::gcd, lamina::isolate_real_roots, lamina::RationalDecompositionStrategy::poly_divide, lamina::solve_by_factoring, lamina::RationalDecompositionStrategy::solve_coefficients, lamina::solve_numeric, lamina::square_free_factorization, lamina::Polynomial< CoeffType >::square_free_part.
CoeffType lamina::Polynomial< CoeffType >::eval(const CoeffType &val) const
对多项式求值（Horner 法）
val 自变量的值 多项式在 val 处的值
References lamina::Polynomial< CoeffType >::coeffs.
Referenced by lamina::find_rational_roots.
bool lamina::Polynomial< CoeffType >::is_zero() const
判断是否为零多项式
References lamina::Polynomial< CoeffType >::coeffs.
Referenced by lamina::Polynomial< CoeffType >::content, lamina::determine_leading_sign, lamina::Polynomial< CoeffType >::div_mod, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::gcd, lamina::isolate_real_roots, lamina::Polynomial< CoeffType >::make_monic, lamina::Polynomial< CoeffType >::operator*, lamina::Polynomial< CoeffType >::operator+, lamina::Polynomial< CoeffType >::operator-, lamina::operator<<, lamina::Polynomial< CoeffType >::operator==, lamina::poly_to_symbolic, lamina::Polynomial< CoeffType >::primitive_part, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::solve_by_factoring, lamina::InequalitySolver::solve_parametric_inequality, lamina::solve_symbolic_poly, lamina::square_free_factorization, lamina::symbolic_poly_to_expr, lamina::Polynomial< CoeffType >::to_string.
CoeffType lamina::Polynomial< CoeffType >::lead_coeff() const
获取首项系数
最高次项的系数；零多项式返回 0
References lamina::Polynomial< CoeffType >::coeffs.
Referenced by lamina::cauchy_bound, lamina::determine_leading_sign, lamina::Polynomial< CoeffType >::div_mod, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::make_monic, lamina::Polynomial< CoeffType >::primitive_part, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::InequalitySolver::solve_parametric_inequality.
Polynomial lamina::Polynomial< CoeffType >::make_monic() const
首一化（使首项系数为 1）
首一多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::Polynomial< CoeffType >::gcd, lamina::square_free_factorization.
Polynomial lamina::Polynomial< CoeffType >::operator*(const Polynomial &other) const
多项式乘法
other 乘数 积多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Polynomial lamina::Polynomial< CoeffType >::operator+(const Polynomial &other) const
多项式加法
other 加数 和多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Polynomial lamina::Polynomial< CoeffType >::operator-(const Polynomial &other) const
多项式减法
other 减数 差多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
bool lamina::Polynomial< CoeffType >::operator==(const Polynomial &other) const
多项式判等
other 比较对象 系数完全相同返回 true
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::variable_name.
Polynomial lamina::Polynomial< CoeffType >::primitive_part() const
计算多项式的本原部分（除以容度）
本原多项式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::content, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::Polynomial< CoeffType >::gcd.
std::pair< Polynomial, Polynomial > lamina::Polynomial< CoeffType >::pseudo_div_mod(const Polynomial &other) const
伪除法（避免分数运算）
other 除数多项式 pair(伪商, 伪余数) std::runtime_error 除数为零多项式时抛出
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::Polynomial< CoeffType >::pseudo_div_mod_rem.
Polynomial lamina::Polynomial< CoeffType >::pseudo_div_mod_rem(const Polynomial &other) const
伪除法取余数
other 除数多项式 伪余数
References lamina::Polynomial< CoeffType >::pseudo_div_mod.
Referenced by lamina::Polynomial< CoeffType >::gcd.
Polynomial lamina::Polynomial< CoeffType >::square_free_part() const
计算无平方因子部分
去除重因子后的多项式
References lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::gcd.
Referenced by lamina::isolate_real_roots.
std::string lamina::Polynomial< CoeffType >::to_string() const
转换为字符串表示
多项式的字符串形式
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::variable_name.
void lamina::Polynomial< CoeffType >::trim()
去除高次零系数
References lamina::Polynomial< CoeffType >::coeffs.
Referenced by lamina::Polynomial< CoeffType >::Polynomial, lamina::Polynomial< CoeffType >::Polynomial, lamina::convert_to_rational_poly, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::RationalDecompositionStrategy::extract_rational, lamina::isolate_real_roots, lamina::Polynomial< CoeffType >::operator*, lamina::Polynomial< CoeffType >::operator+, lamina::Polynomial< CoeffType >::operator-, lamina::Polynomial< CoeffType >::pseudo_div_mod, lamina::try_convert_to_rational_poly.
static Polynomial lamina::Polynomial< CoeffType >::gcd(Polynomial a, Polynomial b)
计算两个多项式的最大公因式
a 第一个多项式 b 第二个多项式 gcd(a, b)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::content, lamina::Polynomial< CoeffType >::div_mod, lamina::gcd_coeff_impl, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::make_monic, lamina::Polynomial< CoeffType >::primitive_part, lamina::Polynomial< CoeffType >::pseudo_div_mod_rem.
Referenced by lamina::RationalDecompositionStrategy::extract_rational, SymbolicExpr::poly_gcd, lamina::square_free_factorization, lamina::Polynomial< CoeffType >::square_free_part.
static CoeffType lamina::Polynomial< CoeffType >::gcd_coeff(const CoeffType &a, const CoeffType &b)
计算两个系数的 GCD（静态方法）
a 第一个系数 b 第二个系数 gcd(a, b)
References BigInt::gcd.
Referenced by lamina::Polynomial< CoeffType >::content.