lamina::anonymous_namespace{integration.cpp}
long long lamina::anonymous_namespace{integration.cpp}::binomial_ll(int n, int k)
References binomial_ll.
Referenced by binomial_ll.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::make_cos_scaled(long long c, const std::string &var)
References SymbolicExpr::cos, make_cos_scaled, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::variable.
Referenced by make_cos_scaled.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::make_sin_scaled(long long c, const std::string &var)
References make_sin_scaled, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::sin, SymbolicExpr::variable.
Referenced by make_sin_scaled.
bool lamina::anonymous_namespace{integration.cpp}::rd_collect_rational(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< Polynomial< Rational > > &num, std::vector< Polynomial< Rational > > &den)
References lamina::num, lamina::Rational, rd_collect_rational.
Referenced by rd_collect_rational.
bool lamina::anonymous_namespace{integration.cpp}::rd_is_const_in(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References lamina::depends_on_var, rd_is_const_in.
Referenced by rd_is_const_in.
bool lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly(const Polynomial< Rational > &p)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Rational, rd_is_zero_poly.
Referenced by rd_is_zero_poly, rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_num_int(long long v)
References SymbolicExpr::number, rd_num_int.
Referenced by rd_num_int, rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_num_rat(const Rational &r)
References SymbolicExpr::number, rd_num_rat.
Referenced by rd_num_rat, rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym(const Polynomial< Rational > &p, const std::string &var)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, rd_is_zero_poly, rd_num_int, rd_num_rat, rd_poly_to_sym, SymbolicExpr::variable.
Referenced by rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_var_minus(const std::string &var, const Rational &r)
References SymbolicExpr::add, SymbolicExpr::number, lamina::Rational, rd_var_minus, SymbolicExpr::variable.
Referenced by rd_var_minus.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_fn_of_var(const std::shared_ptr< SymbolicNode > &node, FunctionNode::FuncType t, const std::string &var)
References sf_is_fn_of_var.
Referenced by sf_is_fn_of_var, sf_is_inv_ln_var.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_inv_ln_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References FunctionNode::Ln, lamina::Rational, sf_is_fn_of_var, sf_is_inv_ln_var.
Referenced by sf_is_inv_ln_var.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_inv_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References lamina::Rational, sf_is_inv_var.
Referenced by sf_is_inv_var, sf_split_inv_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::sf_make_fn(FunctionNode::FuncType t, const std::shared_ptr< SymbolicExpr > &arg)
References sf_make_fn.
Referenced by sf_make_fn.
bool lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad(const std::shared_ptr< SymbolicNode > &node, const std::string &var, Rational &c_out)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, FunctionNode::Exp, lamina::Rational, sf_match_exp_neg_quad.
Referenced by sf_match_exp_neg_quad.
bool lamina::anonymous_namespace{integration.cpp}::sf_split_inv_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< std::shared_ptr< SymbolicNode > > &other_factors, bool &has_inv_var)
References sf_is_inv_var, sf_split_inv_var.
Referenced by sf_split_inv_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi()
References sf_sqrt_pi, SymbolicExpr::sqrt, SymbolicExpr::variable.
Referenced by sf_sqrt_pi.
bool lamina::anonymous_namespace{integration.cpp}::trig_extract_factor(const std::shared_ptr< SymbolicNode > &node, const std::string &var, int &kind_out, int &power_out)
References trig_extract_factor, trig_extract_nonneg_int, trig_match_of_var.
Referenced by trig_extract_factor.
bool lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int(const std::shared_ptr< SymbolicNode > &exp_node, int &n_out)
References SymbolicExpr::simplify, trig_extract_nonneg_int.
Referenced by trig_extract_factor, trig_extract_nonneg_int.
int lamina::anonymous_namespace{integration.cpp}::trig_match_of_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References trig_match_of_var.
Referenced by trig_extract_factor, trig_match_of_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::trig_rational(long long num, long long den)
References lamina::num, SymbolicExpr::number, lamina::Rational, trig_rational.
Referenced by trig_rational.