lamina::RewriteEngine
std::vector<Rule> lamina::RewriteEngine::rules
Referenced by add_rule.
void lamina::RewriteEngine::add_rule(const Rule &rule)
添加重写规则
rule 规则对象
References rules.
Referenced by SymbolicExpr::simplify_trig.
SymbolicExpr lamina::RewriteEngine::apply(const SymbolicExpr &expr, int max_iterations=100)
反复应用规则直到不动点或达到最大迭代次数
expr 输入表达式 max_iterations 最大迭代次数 重写后的表达式
References apply_step, SymbolicExpr::root.
Referenced by SymbolicExpr::simplify_trig.
SymbolicExpr lamina::RewriteEngine::apply_step(const SymbolicExpr &expr)
对表达式应用一步重写
expr 输入表达式 重写后的表达式，若无规则匹配则返回原表达式
References lamina::RewriteVisitor::get_result, SymbolicExpr::root.
Referenced by apply.
const std::vector< Rule > & lamina::RewriteEngine::get_rules() const
获取当前所有规则
规则列表的常引用
Referenced by lamina::RewriteVisitor::try_match.