lamina::PropertyStore
std::unordered_map<std::string, SymbolProperties> lamina::PropertyStore::properties_
Referenced by declare_bounded, declare_domain, declare_parity, declare_sign, get_boundedness, get_bounds, get_domain, get_parity, get_signs, has_domain, has_sign.
void lamina::PropertyStore::declare_bounded(const std::string &symbol, Boundedness bounded, std::optional< Interval > bounds=std::nullopt)
Declare boundedness for a symbol, optionally with interval bounds.
References properties_, lamina::Unknown.
void lamina::PropertyStore::declare_domain(const std::string &symbol, Domain domain)
Declare domain for a symbol. Throws std::invalid_argument on contradiction.
References check_domain_sign_consistency, domain_specificity, properties_.
void lamina::PropertyStore::declare_parity(const std::string &symbol, Parity parity)
Declare parity for a symbol. Throws std::invalid_argument on contradiction.
References domain_specificity, lamina::Integer, properties_, lamina::Unknown.
void lamina::PropertyStore::declare_sign(const std::string &symbol, Sign sign)
Declare sign for a symbol. Throws std::invalid_argument on contradiction.
References check_sign_contradiction, domain_specificity, get_implied_signs, lamina::Integer, lamina::Natural, lamina::Negative, lamina::NonPositive, lamina::PositiveInt, properties_, lamina::Zero.
Referenced by lamina::RelationStore::add_relation.
Boundedness lamina::PropertyStore::get_boundedness(const std::string &symbol) const
Query boundedness for a symbol (default: Unknown).
References properties_, lamina::Unknown.
std::optional< Interval > lamina::PropertyStore::get_bounds(const std::string &symbol) const
Get stored interval bounds (if any).
References properties_.
Domain lamina::PropertyStore::get_domain(const std::string &symbol) const
Query the most specific domain for a symbol (default: Complex).
References lamina::Complex, properties_.
Parity lamina::PropertyStore::get_parity(const std::string &symbol) const
Query parity for a symbol (default: Unknown).
References properties_, lamina::Unknown.
std::unordered_set< Sign, SignHash > lamina::PropertyStore::get_signs(const std::string &symbol) const
Query all signs stored for a symbol.
References properties_.
bool lamina::PropertyStore::has_domain(const std::string &symbol, Domain domain) const
Check if symbol has at least the given domain specificity.
References lamina::Complex, domain_specificity, properties_.
bool lamina::PropertyStore::has_sign(const std::string &symbol, Sign sign) const
Check if symbol has a specific sign (explicit or implied).
References properties_.
void lamina::PropertyStore::check_domain_sign_consistency(const std::string &symbol, const SymbolProperties &props, Domain new_domain)
Check domain-sign cross-constraints. Throws on contradiction.
References lamina::Natural, lamina::Negative, lamina::NonPositive, lamina::PositiveInt, lamina::PropertyStore::SymbolProperties::signs, lamina::Zero.
Referenced by declare_domain.
void lamina::PropertyStore::check_sign_contradiction(const std::string &symbol, const std::unordered_set< Sign, SignHash > &existing, Sign new_sign)
Check sign contradiction pairs. Throws on contradiction.
References lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, lamina::Zero.
Referenced by declare_sign.
int lamina::PropertyStore::domain_specificity(Domain domain) const
Get the specificity level of a domain (higher = more specific).
References lamina::Complex, lamina::Integer, lamina::Natural, lamina::PositiveInt, lamina::Rational, lamina::Real.
Referenced by declare_domain, declare_parity, declare_sign, has_domain.
std::vector< Domain > lamina::PropertyStore::get_ancestor_domains(Domain domain) const
Get ancestor domains (less specific) for a given domain.
References lamina::Complex, lamina::Integer, lamina::Natural, lamina::PositiveInt, lamina::Rational, lamina::Real.
std::unordered_set< Sign, SignHash > lamina::PropertyStore::get_implied_signs(Sign sign) const
Get all signs implied by a given sign.
References lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, lamina::Zero.
Referenced by declare_sign.