lamina::TrigCombinationStrategy
bool lamina::TrigCombinationStrategy::extract_sec_power(const SymbolicExpr &expr, const std::string &var, int &n_out)
检测被积表达式是否为 sec^n(var) 形式。
expr 被积表达式 var 积分变量名 n_out sec 的幂次（正整数） 匹配成功返回 true
References SymbolicExpr::root.
Referenced by try_integrate.
bool lamina::TrigCombinationStrategy::extract_sin_cos_powers(const SymbolicExpr &expr, const std::string &var, int &m_out, int &n_out)
检测被积表达式是否为 sin^m(var)·cos^n(var) 形式。
expr 被积表达式 var 积分变量名 m_out sin 的幂次（非负整数） n_out cos 的幂次（非负整数） 匹配成功返回 true；若包含其他因子、参数不为 var、或幂次为非整数/负数则返回 false
References SymbolicExpr::root.
Referenced by try_integrate.
bool lamina::TrigCombinationStrategy::extract_tan_power(const SymbolicExpr &expr, const std::string &var, int &n_out)
检测被积表达式是否为 tan^n(var) 形式。
expr 被积表达式 var 积分变量名 n_out tan 的幂次（正整数） 匹配成功返回 true
References SymbolicExpr::root.
Referenced by try_integrate.
std::string lamina::TrigCombinationStrategy::name() const override
获取策略名称
策略名称字符串
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::try_integrate(const SymbolicExpr &expr, const std::string &var, Integrator &ctx, int depth=0) override
尝试对表达式进行积分
expr 被积表达式 var 积分变量名 ctx 积分器上下文 depth 当前递归深度 积分结果，失败返回 nullptr
References extract_sec_power, extract_sin_cos_powers, extract_tan_power, integrate_sec_power, integrate_sin_m_cos_n, integrate_tan_power.
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::integrate_even_case(int m, int n, long long scale, const std::string &var, Integrator &ctx, int depth)
处理 m,n 均为偶数的情形：使用半角恒等式 sin²(c·x) = (1 - cos(2c·x))/2，cos²(c·x) = (1 + cos(2c·x))/2， 将被积函数展开为 cos^k(2c·x) 的多项式，并对每个 k 递归调用 integrate_sin_m_cos_n(0, k, 2·scale, ...)。每次递归总度数减半。
References integrate_sin_m_cos_n, lamina::Integrator::max_depth, SymbolicExpr::multiply, lamina::num, SymbolicExpr::number, lamina::Rational.
Referenced by integrate_sin_m_cos_n.
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::integrate_odd_case(int m, int n, long long scale, const std::string &var, Integrator &ctx, int depth)
处理 m 或 n 为奇数的情形：剥离一个 sin/cos，使用毕达哥拉斯恒等式 与 u=cos(c·x) 或 u=sin(c·x) 换元，展开成 u 的多项式后逐项积分。
References lamina::Integrator::max_depth, SymbolicExpr::multiply, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::Rational.
Referenced by integrate_sin_m_cos_n.
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::integrate_sec_power(int n, const std::string &var, Integrator &ctx, int depth)
处理 sec^n(var)（偶数 n）形式：使用归约公式 ∫sec^n = sec^(n-2)·tan/(n-1) + (n-2)/(n-1)·∫sec^(n-2)。 基础情形：n=2 → tan(x)。奇数 n 不在本策略范围内，返回 nullptr。
References SymbolicExpr::add, integrate_sec_power, lamina::Integrator::max_depth, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::Rational, SymbolicExpr::tan, SymbolicExpr::variable.
Referenced by integrate_sec_power, try_integrate.
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::integrate_sin_m_cos_n(int m, int n, long long scale, const std::string &var, Integrator &ctx, int depth)
根据 m,n 奇偶性分派到 odd / even 情形的内部分发器（带尺度参数）。
m sin 幂次 n cos 幂次 scale sin/cos 内部的尺度系数 c，使被积表达式为 sin^m(c·var)·cos^n(c·var)。 顶层调用使用 scale=1，半角恒等式递归时变为 2、4、8。
References integrate_even_case, integrate_odd_case, lamina::Integrator::max_depth, SymbolicExpr::variable.
Referenced by integrate_even_case, try_integrate.
std::shared_ptr< SymbolicExpr > lamina::TrigCombinationStrategy::integrate_tan_power(int n, const std::string &var, Integrator &ctx, int depth)
处理 tan^n(var) 形式：递归地应用 tan^n = tan^(n-2)·(sec²-1)。 基础情形：n=0 → x，n=1 → -ln(cos(x))。
References SymbolicExpr::add, SymbolicExpr::cos, integrate_tan_power, SymbolicExpr::ln, lamina::Integrator::max_depth, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::tan, SymbolicExpr::variable.
Referenced by integrate_tan_power, try_integrate.