LimitVisitor
std::string LimitVisitor::direction
趋近方向（"+"、"-" 或空表示双侧）
Referenced by visit, visit.
std::shared_ptr<SymbolicNode> LimitVisitor::point
趋近点
Referenced by visit, visit, visit.
std::string LimitVisitor::var
趋近变量名
Referenced by visit, visit, visit.
std::shared_ptr<SymbolicNode> LimitVisitor::result
极限计算结果
Referenced by get_result, visit, visit, visit, visit, visit, visit, visit.
LimitVisitor::LimitVisitor(std::string v, std::shared_ptr< SymbolicNode > p, std::string dir="")
构造极限访问器
v 趋近变量名 p 趋近点的 AST 节点 dir 趋近方向，"+" 为右极限，"-" 为左极限，空为双侧
std::shared_ptr< SymbolicNode > LimitVisitor::get_result() const
获取极限计算结果
极限值的 AST 节点
References result.
Referenced by SymbolicExpr::limit, visit, visit.
void LimitVisitor::visit(AddNode &node) override
References NormalizationVisitor::get_result, AddNode::operands, result.
void LimitVisitor::visit(FunctionNode &node) override
References FunctionNode::arguments, NormalizationVisitor::get_result, result, FunctionNode::type.
virtual void SymbolicVisitor::visit(LogicalNode &node)
void LimitVisitor::visit(MatrixNode &node) override
References MatrixNode::clone, result.
void LimitVisitor::visit(MultiplyNode &node) override
References direction, DifferentiationVisitor::get_result, get_result, NormalizationVisitor::get_result, FunctionNode::Infinity, is_inf, MultiplyNode::operands, point, result, var.
void LimitVisitor::visit(NumberNode &node) override
References NumberNode::clone, result.
void LimitVisitor::visit(PowerNode &node) override
References PowerNode::base, direction, PowerNode::exponent, DifferentiationVisitor::get_result, get_result, NormalizationVisitor::get_result, FunctionNode::Infinity, is_inf, BigInt::is_odd, point, result, var.
virtual void SymbolicVisitor::visit(RelationalNode &node)
void LimitVisitor::visit(VariableNode &node) override
References VariableNode::clone, VariableNode::name, point, result, var.
bool LimitVisitor::is_inf(const std::shared_ptr< SymbolicNode > &node)
References FunctionNode::Infinity, is_inf.
Referenced by is_inf, visit, visit.
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.