lamina::detail::MonomialEnumerator
HeapCmp lamina::detail::MonomialEnumerator::cmp_
Referenced by next, push.
std::vector<Monomial> lamina::detail::MonomialEnumerator::heap_
Referenced by next, push.
int lamina::detail::MonomialEnumerator::max_degree_
Referenced by next.
size_t lamina::detail::MonomialEnumerator::num_vars_
Referenced by next.
MonomialOrder lamina::detail::MonomialEnumerator::order_
std::set<Monomial> lamina::detail::MonomialEnumerator::visited_
Referenced by push.
lamina::detail::MonomialEnumerator::MonomialEnumerator(size_t num_vars, const MonomialOrder &order, int max_deg=100)
构造单项式枚举器
num_vars 变量个数 order 单项式序 max_deg 最大次数上限
References push.
bool lamina::detail::MonomialEnumerator::next(Monomial &out)
获取下一个单项式
out 输出单项式 成功返回 true，枚举结束返回 false
References cmp_, heap_, max_degree_, num_vars_, push, lamina::total_degree.
Referenced by lamina::fglm_convert.
void lamina::detail::MonomialEnumerator::push(const Monomial &m)
References cmp_, heap_, visited_.
Referenced by MonomialEnumerator, next.