solve_polynomial.cpp
static std::shared_ptr< SymbolicExpr > lamina::acos_expr(const std::shared_ptr< SymbolicExpr > &x)
References FunctionNode::ArcCos.
static std::shared_ptr< SymbolicExpr > lamina::cbrt_expr(const std::shared_ptr< SymbolicExpr > &x)
References SymbolicExpr::number, SymbolicExpr::power, lamina::Rational.
Referenced by lamina::solve_cubic.
static bool lamina::convert_to_rational_poly(const Polynomial< SymbolicPolyCoeff > &sym_poly, Polynomial< Rational > &out_poly)
References FunctionNode::arguments, PowerNode::base, lamina::Polynomial< CoeffType >::coeffs, PowerNode::exponent, Rational::from_double, AddNode::operands, MultiplyNode::operands, lamina::Rational, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::solve_by_factoring.
std::vector< Rational > lamina::find_rational_roots(const Polynomial< Rational > &poly)
查找有理系数多项式的所有有理根。
poly 有理系数多项式 有理根列表
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::eval, lamina::Polynomial< CoeffType >::is_zero, BigInt::lcm, lamina::Polynomial< CoeffType >::lead_coeff, lamina::positive_divisors, lamina::Rational, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::solve_by_factoring.
static bool lamina::is_purely_numeric(const std::shared_ptr< SymbolicExpr > &expr)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands.
Referenced by lamina::solve_biquadratic, lamina::solve_cubic, lamina::solve_quartic.
static std::shared_ptr< SymbolicExpr > lamina::negate(const std::shared_ptr< SymbolicExpr > &x)
References SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::solve_biquadratic, lamina::solve_cubic, lamina::solve_linear_internal, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::sub.
static std::shared_ptr< SymbolicExpr > lamina::num(int n)
References SymbolicExpr::number.
Referenced by lamina::determine_leading_sign, lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::QueryInterface::get_infinity_sign, lamina::get_integer_value, lamina::implicit_diff, lamina::TrigCombinationStrategy::integrate_even_case, lamina::TrigCombinationStrategy::integrate_odd_case, lamina::is_even_integer_number, lamina::is_exponent_neg_one, lamina::is_exponent_two, lamina::is_integer_number, lamina::is_positive_integer_number, lamina::is_zero_number, lamina::multiply_no_expand, lamina::InferenceEngine::propagate_bounds, lamina::InferenceEngine::query_integer, lamina::QueryInterface::query_integer, lamina::InferenceEngine::query_negative, lamina::QueryInterface::query_negative, lamina::InferenceEngine::query_nonnegative, lamina::QueryInterface::query_nonnegative, lamina::InferenceEngine::query_nonpositive, lamina::InferenceEngine::query_nonzero, lamina::QueryInterface::query_nonzero, lamina::InferenceEngine::query_positive, lamina::QueryInterface::query_positive, lamina::InferenceEngine::query_real, lamina::QueryInterface::query_real, lamina::anonymous_namespace{integration.cpp}::rd_collect_rational, lamina::solve_cubic, lamina::solve_linear1_ode, lamina::InequalitySolver::solve_parametric_inequality, lamina::solve_quadratic_internal, lamina::solve_quartic, lamina::sym_rational, lamina::anonymous_namespace{integration.cpp}::trig_rational, lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value, lamina::PartialFractionStrategy::try_integrate, lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::visit.
static std::shared_ptr< SymbolicExpr > lamina::num_r(int p, int q)
References SymbolicExpr::number, lamina::Rational.
static std::vector< BigInt > lamina::positive_divisors(const BigInt &n)
References BigInt::Abs, BigInt::is_zero.
Referenced by lamina::find_rational_roots.
static Polynomial< SymbolicPolyCoeff > lamina::rational_to_symbolic_poly(const Polynomial< Rational > &rat_poly)
References lamina::Polynomial< CoeffType >::coeffs, SymbolicExpr::number, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::solve_by_factoring.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_biquadratic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::string &var)
求解双二次方程 ax⁴ + bx² + c = 0。
a 四次项系数 b 二次项系数 c 常数项 var 求解变量名 所有根的符号表达式列表
References lamina::is_purely_numeric, lamina::negate, SymbolicExpr::number, lamina::solve_quadratic_internal, SymbolicExpr::sqrt.
Referenced by lamina::solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_by_factoring(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
通过因式分解求解多项式方程。
poly 符号系数多项式 var 求解变量名 所有根的符号表达式列表
References lamina::convert_to_rational_poly, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::is_zero, lamina::make_rootof_solutions, SymbolicExpr::number, lamina::Rational, lamina::rational_to_symbolic_poly, lamina::solve_closed_form_poly, lamina::square_free_factorization.
Referenced by lamina::find_roots_with_multiplicity, lamina::solve_dispatch, lamina::solve_symbolic_poly.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_closed_form_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, SymbolicExpr::multiply, SymbolicExpr::number, lamina::solve_cubic, lamina::solve_quadratic_internal, lamina::solve_quartic.
Referenced by lamina::solve_by_factoring.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_cubic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::string &var)
使用三次公式求解三次方程 ax³ + bx² + cx + d = 0。
a 三次项系数 b 二次项系数 c 一次项系数 d 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, lamina::cbrt_expr, SymbolicExpr::divide, lamina::is_purely_numeric, SymbolicExpr::multiply, lamina::negate, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_linear_internal, lamina::solve_quadratic_internal, SymbolicExpr::sqrt, lamina::sub.
Referenced by lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, solve_polynomial_closed, lamina::solve_quartic.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_linear_internal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
References SymbolicExpr::divide, lamina::negate.
Referenced by lamina::solve_cubic.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_quadratic_internal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::add, SymbolicExpr::divide, SymbolicExpr::multiply, lamina::negate, lamina::num, SymbolicExpr::power, SymbolicExpr::sqrt, lamina::sub.
Referenced by lamina::solve_biquadratic, lamina::solve_closed_form_poly, lamina::solve_cubic, lamina::solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_quartic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::shared_ptr< SymbolicExpr > &e, const std::string &var)
使用四次公式求解四次方程 ax⁴ + bx³ + cx² + dx + e = 0。
a 四次项系数 b 三次项系数 c 二次项系数 d 一次项系数 e 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, SymbolicExpr::divide, lamina::is_purely_numeric, SymbolicExpr::multiply, lamina::negate, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_biquadratic, lamina::solve_cubic, lamina::solve_quadratic_internal, SymbolicExpr::sqrt, lamina::sub.
Referenced by lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, solve_polynomial_closed.
std::vector< std::pair< Polynomial< Rational >, int > > lamina::square_free_factorization(const Polynomial< Rational > &poly)
对有理系数多项式进行无平方因子分解。
poly 有理系数多项式 因子与重数的列表
References lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::gcd, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::make_monic.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::find_roots_with_multiplicity, lamina::solve_by_factoring.
static std::shared_ptr< SymbolicExpr > lamina::sub(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
References SymbolicExpr::add, lamina::negate.
Referenced by lamina::solve_cubic, lamina::Solver::solve_polynomial_system, lamina::solve_quadratic_internal, lamina::solve_quartic.