integration.cpp
long long lamina::anonymous_namespace{integration.cpp}::binomial_ll(int n, int k)
References lamina::anonymous_namespace{integration.cpp}::binomial_ll.
Referenced by lamina::anonymous_namespace{integration.cpp}::binomial_ll.
static bool lamina::has_integral_node_check(const std::shared_ptr< SymbolicNode > &node)
References FunctionNode::Calculus_Integral, lamina::has_integral_node_check.
Referenced by lamina::MultipleIntegralEngine::evaluate, lamina::has_integral_node_check, lamina::TableLookupStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > lamina::make_arctan(const std::shared_ptr< SymbolicExpr > &op)
References FunctionNode::ArcTan.
Referenced by lamina::RationalDecompositionStrategy::integrate_term, lamina::invert_h_tan, lamina::invert_tan, lamina::PartialFractionStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::make_cos_scaled(long long c, const std::string &var)
References SymbolicExpr::cos, lamina::anonymous_namespace{integration.cpp}::make_cos_scaled, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::variable.
Referenced by lamina::anonymous_namespace{integration.cpp}::make_cos_scaled.
static std::shared_ptr< SymbolicExpr > lamina::make_expr_ptr(const SymbolicExpr &e)
Referenced by lamina::Integrator::check_cycle, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::Integrator::integrate_def, lamina::Integrator::integrate_recursive, lamina::IntegrationTable::load_defaults, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::make_sin_scaled(long long c, const std::string &var)
References lamina::anonymous_namespace{integration.cpp}::make_sin_scaled, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::sin, SymbolicExpr::variable.
Referenced by lamina::anonymous_namespace{integration.cpp}::make_sin_scaled.
bool lamina::anonymous_namespace{integration.cpp}::rd_collect_rational(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< Polynomial< Rational > > &num, std::vector< Polynomial< Rational > > &den)
References lamina::num, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::rd_collect_rational.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_collect_rational.
bool lamina::anonymous_namespace{integration.cpp}::rd_is_const_in(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References lamina::depends_on_var, lamina::anonymous_namespace{integration.cpp}::rd_is_const_in.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_is_const_in.
bool lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly(const Polynomial< Rational > &p)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_num_int(long long v)
References SymbolicExpr::number, lamina::anonymous_namespace{integration.cpp}::rd_num_int.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_num_int, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_num_rat(const Rational &r)
References SymbolicExpr::number, lamina::anonymous_namespace{integration.cpp}::rd_num_rat.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_num_rat, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym(const Polynomial< Rational > &p, const std::string &var)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::anonymous_namespace{integration.cpp}::rd_is_zero_poly, lamina::anonymous_namespace{integration.cpp}::rd_num_int, lamina::anonymous_namespace{integration.cpp}::rd_num_rat, lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym, SymbolicExpr::variable.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_poly_to_sym.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::rd_var_minus(const std::string &var, const Rational &r)
References SymbolicExpr::add, SymbolicExpr::number, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::rd_var_minus, SymbolicExpr::variable.
Referenced by lamina::anonymous_namespace{integration.cpp}::rd_var_minus.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_fn_of_var(const std::shared_ptr< SymbolicNode > &node, FunctionNode::FuncType t, const std::string &var)
References lamina::anonymous_namespace{integration.cpp}::sf_is_fn_of_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_is_fn_of_var, lamina::anonymous_namespace{integration.cpp}::sf_is_inv_ln_var.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_inv_ln_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References FunctionNode::Ln, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::sf_is_fn_of_var, lamina::anonymous_namespace{integration.cpp}::sf_is_inv_ln_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_is_inv_ln_var.
bool lamina::anonymous_namespace{integration.cpp}::sf_is_inv_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References lamina::Rational, lamina::anonymous_namespace{integration.cpp}::sf_is_inv_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_is_inv_var, lamina::anonymous_namespace{integration.cpp}::sf_split_inv_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::sf_make_fn(FunctionNode::FuncType t, const std::shared_ptr< SymbolicExpr > &arg)
References lamina::anonymous_namespace{integration.cpp}::sf_make_fn.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_make_fn.
bool lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad(const std::shared_ptr< SymbolicNode > &node, const std::string &var, Rational &c_out)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, FunctionNode::Exp, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_match_exp_neg_quad.
bool lamina::anonymous_namespace{integration.cpp}::sf_split_inv_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< std::shared_ptr< SymbolicNode > > &other_factors, bool &has_inv_var)
References lamina::anonymous_namespace{integration.cpp}::sf_is_inv_var, lamina::anonymous_namespace{integration.cpp}::sf_split_inv_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_split_inv_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi()
References lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi, SymbolicExpr::sqrt, SymbolicExpr::variable.
Referenced by lamina::anonymous_namespace{integration.cpp}::sf_sqrt_pi.
static std::shared_ptr< SymbolicExpr > lamina::sym_rational(long long num, long long den)
References lamina::num, SymbolicExpr::number, lamina::Rational.
Referenced by lamina::IntegrationTable::load_defaults, lamina::PowerRuleStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > lamina::sym_sub(const SymbolicExpr &a, const SymbolicExpr &b)
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::MultipleIntegralEngine::evaluate, lamina::Integrator::integrate_def, lamina::IntegrationTable::load_defaults, lamina::Integrator::resolve_cycle, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
bool lamina::anonymous_namespace{integration.cpp}::trig_extract_factor(const std::shared_ptr< SymbolicNode > &node, const std::string &var, int &kind_out, int &power_out)
References lamina::anonymous_namespace{integration.cpp}::trig_extract_factor, lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int, lamina::anonymous_namespace{integration.cpp}::trig_match_of_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::trig_extract_factor.
bool lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int(const std::shared_ptr< SymbolicNode > &exp_node, int &n_out)
References SymbolicExpr::simplify, lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int.
Referenced by lamina::anonymous_namespace{integration.cpp}::trig_extract_factor, lamina::anonymous_namespace{integration.cpp}::trig_extract_nonneg_int.
int lamina::anonymous_namespace{integration.cpp}::trig_match_of_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References lamina::anonymous_namespace{integration.cpp}::trig_match_of_var.
Referenced by lamina::anonymous_namespace{integration.cpp}::trig_extract_factor, lamina::anonymous_namespace{integration.cpp}::trig_match_of_var.
std::shared_ptr< SymbolicExpr > lamina::anonymous_namespace{integration.cpp}::trig_rational(long long num, long long den)
References lamina::num, SymbolicExpr::number, lamina::Rational, lamina::anonymous_namespace{integration.cpp}::trig_rational.
Referenced by lamina::anonymous_namespace{integration.cpp}::trig_rational.
static bool lamina::valid_dependency(const SymbolicExpr &expr, const std::string &var)
References SymbolicExpr::differentiate.
Referenced by lamina::Integrator::apply_linearity, lamina::Integrator::check_cycle, lamina::Integrator::integrate_recursive, lamina::Integrator::resolve_cycle, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.