bigint.hpp
_STATIC_ASSERT
void * bigint_alloc(size_t size)
为 BigInt 分配内存
Referenced by BigInt::realloc_to.
void bigint_div_(mp_ptr q, mp_ptr r, mp_srcptr n, mp_size_t nn, mp_srcptr d, mp_size_t dn)
大整数除法（底层 LAMMP 调用）
q 商缓冲区 r 余数缓冲区 n 被除数 limb 数组 nn 被除数 limb 数 d 除数 limb 数组 dn 除数 limb 数
Referenced by BigInt::operator%, BigInt::operator/.
void bigint_free(void *p)
释放 BigInt 内部分配的内存
Referenced by BigInt::~BigInt, BigInt::operator=, BigInt::realloc_to.
void bigint_mul_(mp_ptr dst, mp_srcptr numa, mp_size_t na, mp_srcptr numb, mp_size_t nb)
大整数乘法（底层 LAMMP 调用）
dst 结果缓冲区 numa 乘数 a 的 limb 数组 na 乘数 a 的 limb 数 numb 乘数 b 的 limb 数组 nb 乘数 b 的 limb 数
Referenced by BigInt::operator*.
mp_size_t lmmp_rlz(mp_srcptr p, mp_size_t n)
去除 limb 数组的前导零，返回有效长度
p limb 数组指针 n 原始长度 去除前导零后的有效长度