RelationalNode
Op
等于
std::shared_ptr<SymbolicNode> RelationalNode::left
左操作数
Referenced by clone, compare_same_type, compute_hash, lamina::depends_on_var, SymbolicExpr::poly_gcd, ExpandVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, VariablesVisitor::visit, SubstituteVisitor::visit.
Op RelationalNode::op
关系运算符
Referenced by clone, compare_same_type, compute_hash, op_to_string, ExpandVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, SubstituteVisitor::visit.
std::shared_ptr<SymbolicNode> RelationalNode::right
右操作数
Referenced by clone, compare_same_type, compute_hash, lamina::depends_on_var, SymbolicExpr::poly_gcd, ExpandVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, VariablesVisitor::visit, SubstituteVisitor::visit.
RelationalNode::RelationalNode(std::shared_ptr< SymbolicNode > l, std::shared_ptr< SymbolicNode > r, Op o)
void RelationalNode::accept(SymbolicVisitor &visitor) override
接受 Visitor 访问。
References SymbolicVisitor::visit.
std::shared_ptr< SymbolicNode > RelationalNode::clone() const override
深拷贝当前节点及其子树。
References left, op, right.
Referenced by lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit.
int SymbolicNode::compare(const SymbolicNode &other) const
与另一个节点进行全序比较。
other 待比较的节点 小于返回 -1，等于返回 0，大于返回 1
References SymbolicNode::compare_same_type, SymbolicNode::type_priority.
Referenced by VariableNode::compare_same_type, PowerNode::compare_same_type.
int RelationalNode::compare_same_type(const SymbolicNode &other) const override
与同类型节点进行比较（由子类实现）。
References left, op, right.
std::size_t RelationalNode::compute_hash() const override
计算当前节点的哈希值（由子类实现）。
References hash_combine, left, op, right.
bool SymbolicNode::equals(const SymbolicNode &other) const
判断两个节点是否结构相等。
other 待比较的节点 相等返回 true
References SymbolicNode::compare_same_type, SymbolicNode::hash, SymbolicNode::type_priority.
std::size_t SymbolicNode::hash() const
获取节点哈希值（带缓存）。
哈希值
References SymbolicNode::cached_hash, SymbolicNode::compute_hash, SymbolicNode::hash_computed.
Referenced by MatrixNode::compute_hash, SymbolicNode::equals.
virtual bool SymbolicNode::is_number() const
判断节点是否为数值节点。
virtual bool SymbolicNode::is_one() const
判断节点数值是否为 1。
virtual bool SymbolicNode::is_positive() const
判断节点是否可证明为严格正数（非数值节点默认返回 false）。
virtual bool SymbolicNode::is_zero() const
判断节点数值是否为 0。
Referenced by MatrixNode::compute_hash.
int RelationalNode::type_priority() const override
返回节点类型的排序优先级，用于规范化排序。
static std::string RelationalNode::op_to_string(Op op)
将关系运算符转换为字符串表示。
op 关系运算符 对应的字符串（如 "=", "<", ">=" 等）
References EQ, GEQ, GT, LEQ, LT, NEQ, op.
Referenced by PrintVisitor::visit.
std::atomic<std::size_t> SymbolicNode::cached_hash
Referenced by SymbolicNode::hash.
std::atomic<bool> SymbolicNode::hash_computed
Referenced by SymbolicNode::hash.