symbolic_complex.hpp
std::shared_ptr< SymbolicExpr > lamina::complex_abs(const ComplexSymbolic &z)
计算复数的模
z 输入复数 模的符号表达式
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, SymbolicExpr::number, SymbolicExpr::power, lamina::ComplexSymbolic::real, SymbolicExpr::sqrt.
Referenced by lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector.
ComplexSymbolic lamina::complex_add(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数加法
a 加数 b 加数 和
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, lamina::make_complex, lamina::ComplexSymbolic::real.
std::shared_ptr< SymbolicExpr > lamina::complex_arg(const ComplexSymbolic &z)
计算复数的辐角
z 输入复数 辐角的符号表达式
References SymbolicExpr::atan2, lamina::ComplexSymbolic::imag, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_conj(const ComplexSymbolic &z)
计算复数的共轭
z 输入复数 共轭复数
References lamina::ComplexSymbolic::imag, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_div(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数除法
a 被除数 b 除数 商
References SymbolicExpr::add, SymbolicExpr::divide, lamina::ComplexSymbolic::imag, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::ComplexSymbolic::real.
Referenced by lamina::solve_complex_quadratic.
ComplexSymbolic lamina::complex_exp_form(std::shared_ptr< SymbolicExpr > r, std::shared_ptr< SymbolicExpr > theta)
将极坐标形式转换为指数形式复数 r*e^(i*theta)
r 模 theta 辐角 对应的符号复数
References SymbolicExpr::cos, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::sin.
Referenced by lamina::complex_trig_form, lamina::solve_complex_nth_root.
std::shared_ptr< SymbolicExpr > lamina::complex_locus_circle(const ComplexSymbolic &a, std::shared_ptr< SymbolicExpr > r, const std::string &z_var="z")
生成以 a 为圆心、r 为半径的复数轨迹方程 |z - a| = r
a 圆心复数 r 半径 z_var 复变量名，默认为 "z" 轨迹方程的符号表达式
References lamina::complex_abs, lamina::complex_sub, SymbolicExpr::eq, lamina::make_complex, SymbolicExpr::number, SymbolicExpr::variable.
std::shared_ptr< SymbolicExpr > lamina::complex_locus_perpendicular_bisector(const ComplexSymbolic &a, const ComplexSymbolic &b, const std::string &z_var="z")
生成复数 a 和 b 的中垂线轨迹方程 |z - a| = |z - b|
a 第一个复数点 b 第二个复数点 z_var 复变量名，默认为 "z" 轨迹方程的符号表达式
References lamina::complex_abs, lamina::complex_sub, SymbolicExpr::eq, lamina::make_complex, SymbolicExpr::number, SymbolicExpr::variable.
ComplexSymbolic lamina::complex_mul(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数乘法
a 乘数 b 乘数 积
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_sub(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数减法
a 被减数 b 减数 差
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
Referenced by lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector.
ComplexSymbolic lamina::complex_trig_form(std::shared_ptr< SymbolicExpr > r, std::shared_ptr< SymbolicExpr > theta)
将极坐标形式转换为三角形式复数 r*(cos(theta) + i*sin(theta))
r 模 theta 辐角 对应的符号复数
References lamina::complex_exp_form.
ComplexSymbolic lamina::make_complex(std::shared_ptr< SymbolicExpr > real, std::shared_ptr< SymbolicExpr > imag)
构造符号复数
real 实部表达式 imag 虚部表达式 符号复数对象
Referenced by lamina::complex_add, lamina::complex_conj, lamina::complex_div, lamina::complex_exp_form, lamina::complex_locus_circle, lamina::complex_locus_perpendicular_bisector, lamina::complex_mul, lamina::complex_sub, lamina::solve_complex_quadratic.
std::vector< ComplexSymbolic > lamina::solve_complex_nth_root(std::shared_ptr< SymbolicExpr > c, int n)
求复数 c 的 n 次方根
c 被开方的复数表达式 n 根的次数 n 个复数根的列表
References lamina::complex_exp_form, SymbolicExpr::number.
std::vector< ComplexSymbolic > lamina::solve_complex_quadratic(std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b, std::shared_ptr< SymbolicExpr > c)
求复系数一元二次方程 az^2 + bz + c = 0 的根
a 二次项系数 b 一次项系数 c 常数项 两个复数根
References SymbolicExpr::add, lamina::complex_div, lamina::make_complex, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::sqrt.