BigInt
Sign
mp_size_t BigInt::_alloc
Referenced by operator=, operator=, realloc_to.
mp_ptr BigInt::_data
Referenced by BigInt, BigInt, BigInt, BigInt, ~BigInt, add_abs, cmp_abs, factorial, gcd, get_digits, hash, is_odd, is_prime, multinomial, nCr, normalize, nPr, operator%, operator*, operator/, operator<<=, operator=, operator=, operator>>=, pow_mod, power, power, realloc_to, sqrt, sub_abs, to_double, to_int, ToString, trailing_zeros.
int BigInt::_sign
Referenced by BigInt, BigInt, BigInt, BigInt, Abs, factorial, gcd, is_perfect_square, is_prime, IsNegative, multinomial, nCr, negate, normalize, nPr, operator%, operator*, operator+, operator/, operator<, operator=, operator=, operator==, operator>>=, power, power, sqrt, to_double, to_int, ToString, zero.
mp_size_t BigInt::_size
Referenced by BigInt, BigInt, BigInt, BigInt, Abs, add_abs, cmp_abs, factorial, gcd, get_digits, hash, is_odd, is_perfect_square, is_prime, is_zero, multinomial, nCr, negate, normalize, nPr, operator bool, operator!, operator%, operator*, operator/, operator<<=, operator=, operator=, operator>>=, pow_mod, power, power, realloc_to, sqrt, sub_abs, to_double, to_int, ToString, trailing_zeros, zero.
bool BigInt::negative
Referenced by BigInt, BigInt, BigInt, BigInt, Abs, factorial, gcd, hash, multinomial, nCr, negate, normalize, nPr, operator%, operator*, operator+, operator/, operator=, operator=, operator>>=, power, sqrt, zero.
BigInt::BigInt()
默认构造，值为 0
Referenced by lcm, multinomial, nCr, nPr, operator*, operator+, operator/, pow_mod, power, power, sqrt.
BigInt::BigInt(BigInt &&other) noexcept
移动构造
References ZERO.
BigInt::BigInt(const BigInt &other)
拷贝构造
References _data, _sign, _size, negative, realloc_to, zero.
BigInt::BigInt(const std::string &str)
从十进制字符串构造
str 十进制数字字符串，可带正负号
References _data, _sign, _size, NEGATIVE, negative, normalize, POSITIVE, realloc_to, zero.
BigInt::BigInt(int val)
从 int 构造
BigInt::BigInt(long long val)
从 long long 构造
val 整数值
References _data, _sign, _size, NEGATIVE, negative, POSITIVE, realloc_to, zero.
BigInt::BigInt(unsigned int val)
从 unsigned int 构造
BigInt::BigInt(unsigned long long val)
从 unsigned long long 构造
val 无符号整数值
References _data, _sign, _size, negative, POSITIVE, realloc_to, zero.
BigInt::BigInt(unsigned long val)
从 unsigned long 构造
BigInt::~BigInt()
References _data, bigint_free.
BigInt BigInt::Abs() const
取绝对值
|*this|
References _sign, _size, negative, POSITIVE.
Referenced by Rational::abs, gcd, lcm, lamina::positive_divisors, Rational::simplify, Rational::to_float_string.
std::vector< uint64_t > BigInt::get_digits() const
获取 limb 数组的副本
各 limb 值组成的 vector
References _data, _size.
std::size_t BigInt::hash() const
计算哈希值
哈希值
References _data, _size, negative.
Referenced by Rational::hash.
bool BigInt::is_even() const
判断是否为偶数
References is_odd.
Referenced by lamina::is_even_integer_number, is_prime.
bool BigInt::is_odd() const
判断是否为奇数
References _data, _size.
Referenced by is_even, pow_mod, LimitVisitor::visit.
bool BigInt::is_perfect_square() const
判断是否为完全平方数
是完全平方数返回 true
References _sign, _size, NEGATIVE, sqrt.
bool BigInt::is_prime() const
素性测试（Miller-Rabin）
是素数返回 true
References _data, _sign, _size, is_even, NEGATIVE, pow_mod.
bool BigInt::is_zero() const
判断是否为零
References _size.
Referenced by gcd, lcm, operator<<=, operator>>=, lamina::positive_divisors, pow_mod, power, trailing_zeros, NormalizationVisitor::visit, NormalizationVisitor::visit.
bool BigInt::IsNegative() const
判断是否为负数
References _sign, NEGATIVE.
Referenced by lamina::is_positive_integer_number, Rational::simplify, lamina::symbolic_to_poly_recursive, NormalizationVisitor::visit.
BigInt BigInt::negate() const
取相反数
-*this
References _sign, _size, NEGATIVE, negative, POSITIVE.
Referenced by operator-.
void BigInt::normalize()
References _data, _sign, _size, NEGATIVE, negative, POSITIVE, ZERO.
Referenced by BigInt, add_abs, factorial, gcd, multinomial, nCr, nPr, operator%, operator*, operator/, operator<<=, operator>>=, power, power, sqrt, sub_abs.
BigInt::operator bool() const
References _size.
bool BigInt::operator!() const
References _size.
bool BigInt::operator!=(const BigInt &other) const
BigInt BigInt::operator%(const BigInt &other) const
取模运算符
other 模数 余数 std::domain_error 模数为零时抛出
References _data, _sign, _size, bigint_div_, NEGATIVE, negative, normalize, realloc_to.
BigInt & BigInt::operator%=(const BigInt &other)
BigInt BigInt::operator*(const BigInt &other) const
乘法运算符
References BigInt, _data, _sign, _size, bigint_mul_, NEGATIVE, negative, normalize, POSITIVE, realloc_to.
BigInt & BigInt::operator*=(const BigInt &other)
BigInt BigInt::operator+(const BigInt &other) const
加法运算符
References BigInt, _sign, add_abs, cmp_abs, NEGATIVE, negative, sub_abs, ZERO.
BigInt & BigInt::operator+=(const BigInt &other)
BigInt BigInt::operator-() const
一元负号运算符
References negate.
BigInt BigInt::operator-(const BigInt &other) const
减法运算符
BigInt & BigInt::operator-=(const BigInt &other)
BigInt BigInt::operator/(const BigInt &other) const
除法运算符（整数除法，截断）
other 除数 商 std::domain_error 除数为零时抛出
References BigInt, _data, _sign, _size, bigint_div_, NEGATIVE, negative, normalize, POSITIVE, realloc_to.
BigInt & BigInt::operator/=(const BigInt &other)
bool BigInt::operator<(const BigInt &other) const
References _sign, cmp_abs, POSITIVE, ZERO.
BigInt BigInt::operator<<(mp_size_t shift) const
左移运算符
BigInt & BigInt::operator<<=(mp_size_t shift)
左移赋值
shift 移位比特数 *this
References _data, _size, is_zero, normalize, realloc_to.
bool BigInt::operator<=(const BigInt &other) const
BigInt & BigInt::operator=(BigInt &&other) noexcept
移动赋值
References _alloc, _data, _sign, _size, bigint_free, negative.
BigInt & BigInt::operator=(const BigInt &other)
拷贝赋值
References _alloc, _data, _sign, _size, negative, realloc_to.
bool BigInt::operator==(const BigInt &other) const
References _sign, cmp_abs.
bool BigInt::operator>(const BigInt &other) const
bool BigInt::operator>=(const BigInt &other) const
BigInt BigInt::operator>>(mp_size_t shift) const
右移运算符
BigInt & BigInt::operator>>=(mp_size_t shift)
右移赋值
shift 移位比特数 *this
References _data, _sign, _size, is_zero, negative, normalize, POSITIVE.
BigInt BigInt::power(BigInt exp) const
整数幂运算（BigInt 指数）
exp 非负 BigInt 指数 this^exp std::domain_error 指数为负时抛出
References BigInt, _data, _sign, _size, is_zero, NEGATIVE, normalize, power.
BigInt BigInt::power(unsigned long exp) const
整数幂运算
exp 非负指数 this^exp
References BigInt, _data, _sign, _size, NEGATIVE, negative, normalize, POSITIVE, realloc_to.
Referenced by Rational::Rational, Rational::floor_without_sim, power, Rational::power, Rational::radicand_self, Rational::to_float_string.
void BigInt::realloc_to(mp_size_t new_alloc)
References _alloc, _data, _size, bigint_alloc, bigint_free.
Referenced by BigInt, BigInt, BigInt, BigInt, add_abs, factorial, gcd, multinomial, nCr, nPr, operator%, operator*, operator/, operator<<=, operator=, power, sqrt, sub_abs.
BigInt BigInt::sqrt() const
整数平方根（向下取整）
floor(sqrt(*this)) std::domain_error 负数时抛出
References BigInt, _data, _sign, _size, NEGATIVE, negative, normalize, POSITIVE, realloc_to.
Referenced by is_perfect_square, NormalizationVisitor::visit.
lmmc_real_t BigInt::to_double() const
转换为浮点数
对应的 double 值
References _data, _sign, _size, NEGATIVE, zero.
Referenced by Rational::to_double, NormalizationVisitor::visit, NormalizationVisitor::visit.
int BigInt::to_int() const
转换为 int（溢出时饱和到 int 范围）
对应的 int 值
References _data, _sign, _size, NEGATIVE, POSITIVE.
Referenced by lamina::symbolic_to_poly_recursive.
std::string BigInt::to_string() const
转换为十进制字符串（同 ToString）
References ToString.
Referenced by lamina::collect_power_exponents.
std::string BigInt::ToString() const
转换为十进制字符串
十进制表示的字符串
References _data, _sign, _size, NEGATIVE.
Referenced by Rational::to_float_string, to_string, Rational::to_string.
mp_size_t BigInt::trailing_zeros() const
计算末尾零比特数
二进制表示中末尾连续 0 的个数
References _data, _size, is_zero.
void BigInt::zero()
References _sign, _size, negative, ZERO.
Referenced by BigInt, BigInt, BigInt, BigInt, to_double.
static void BigInt::add_abs(BigInt &dst, const BigInt &a, const BigInt &b)
绝对值加法（内部使用）
dst 结果 a 加数 b 加数
References _data, _size, normalize, realloc_to.
Referenced by operator+.
static int BigInt::cmp_abs(const BigInt &a, const BigInt &b)
比较两个 BigInt 的绝对值
a 第一个操作数 b 第二个操作数 1 表示 |a|>|b|，-1 表示 |a|<|b|，0 表示相等
References _data, _size.
Referenced by operator+, operator<, operator==.
static BigInt BigInt::factorial(unsigned int n)
计算阶乘
n 非负整数 n!
References _data, _sign, _size, negative, normalize, POSITIVE, realloc_to.
Referenced by SymbolicExpr::series.
static BigInt BigInt::gcd(const BigInt &a, const BigInt &b)
计算最大公约数
a 第一个大整数 b 第二个大整数 gcd(|a|, |b|)
References _data, _sign, _size, Abs, is_zero, negative, normalize, POSITIVE, realloc_to.
Referenced by lamina::Polynomial< CoeffType >::gcd_coeff, lamina::gcd_coeff_impl, lcm, Rational::simplify.
static BigInt BigInt::lcm(const BigInt &a, const BigInt &b)
计算最小公倍数
a 第一个大整数 b 第二个大整数 lcm(|a|, |b|)
References BigInt, Abs, gcd, is_zero.
Referenced by lamina::find_rational_roots.
static BigInt BigInt::multinomial(unsigned int n, const std::vector< unsigned int > &r)
计算多项式系数（多重组合数）
n 总数（应等于 r 各元素之和） r 各组大小 n! / (r[0]! * r[1]! * ... * r[k]!) std::invalid_argument r 之和不等于 n 时抛出
References BigInt, _data, _sign, _size, negative, normalize, POSITIVE, realloc_to.
static BigInt BigInt::nCr(unsigned int n, unsigned int r)
计算组合数 C(n, r)
n 总数 r 选取数 n! / (r! * (n-r)!)
References BigInt, _data, _sign, _size, negative, normalize, POSITIVE, realloc_to.
static BigInt BigInt::nPr(unsigned int n, unsigned int r)
计算排列数 P(n, r)
n 总数 r 选取数 n! / (n-r)!
References BigInt, _data, _sign, _size, negative, normalize, POSITIVE, realloc_to.
static BigInt BigInt::pow_mod(const BigInt &base, const BigInt &exp, const BigInt &mod)
模幂运算
base 底数 exp 指数 mod 模数 base^exp mod mod std::runtime_error 模数为零时抛出
References BigInt, _data, _size, is_odd, is_zero.
Referenced by is_prime.
static void BigInt::sub_abs(BigInt &dst, const BigInt &a, const BigInt &b)
绝对值减法（内部使用，要求 |a| >= |b|）
dst 结果 a 被减数 b 减数
References _data, _size, normalize, realloc_to.
Referenced by operator+.