lamina::ParametricSolver
std::vector< std::map< std::string, std::shared_ptr< SymbolicExpr > > > lamina::ParametricSolver::solve_system(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns, const std::vector< std::string > &parameters)
求解含参方程组，返回所有解
equations 方程列表（每个表达式 = 0） unknowns 未知数名称列表 parameters 参数名称列表 解的列表，每个解为变量名到表达式的映射
References is_linear_in_unknowns, solve_linear_parametric, solve_polynomial_parametric.
Referenced by SymbolicExpr::solve_system, solve_system_piecewise.
PiecewiseSolution lamina::ParametricSolver::solve_system_piecewise(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns, const std::vector< std::string > &parameters)
求解含参方程组，返回按参数条件分段的解
equations 方程列表（每个表达式 = 0） unknowns 未知数名称列表 parameters 参数名称列表 分段解集
References lamina::PiecewiseSolution::cases, lamina::compute_determinant, lamina::PiecewiseSolution::Case::condition, lamina::depends_on_parameters, lamina::extract_coefficient, is_linear_in_unknowns, SymbolicExpr::number, lamina::PiecewiseSolution::Case::solutions, solve_system.
bool lamina::ParametricSolver::is_linear_in_unknowns(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns)
判断方程组是否关于未知数为线性
equations 方程列表 unknowns 未知数名称列表 线性返回 true
Referenced by solve_system, solve_system_piecewise.
std::vector< std::map< std::string, std::shared_ptr< SymbolicExpr > > > lamina::ParametricSolver::solve_linear_parametric(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns, const std::vector< std::string > &parameters)
求解关于未知数为线性的含参方程组
References SymbolicExpr::add, SymbolicExpr::divide, lamina::extract_coefficient, lamina::extract_constant_term, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::variable.
Referenced by solve_system.
std::vector< std::map< std::string, std::shared_ptr< SymbolicExpr > > > lamina::ParametricSolver::solve_polynomial_parametric(const std::vector< std::shared_ptr< SymbolicExpr > > &equations, const std::vector< std::string > &unknowns, const std::vector< std::string > &parameters)
求解关于未知数为多项式的含参方程组
References lamina::contains, lamina::Solver::groebner_basis, SymbolicExpr::solve, SymbolicExpr::variable.
Referenced by solve_system.