var annotated_dup =
[
    [ "anonymous_namespace{lmmc_lifecycle.cpp}", "dc/de1/namespaceanonymous__namespace_02lmmc__lifecycle_8cpp_03.html", [
      [ "LmmcLifecycle", "d6/d49/structanonymous__namespace_02lmmc__lifecycle_8cpp_03_1_1LmmcLifecycle.html", "d6/d49/structanonymous__namespace_02lmmc__lifecycle_8cpp_03_1_1LmmcLifecycle" ]
    ] ],
    [ "anonymous_namespace{symbolic_factor.cpp}", "dc/deb/namespaceanonymous__namespace_02symbolic__factor_8cpp_03.html", [
      [ "FactorVariablesVisitor", "d5/dd5/classanonymous__namespace_02symbolic__factor_8cpp_03_1_1FactorVariablesVisitor.html", "d5/dd5/classanonymous__namespace_02symbolic__factor_8cpp_03_1_1FactorVariablesVisitor" ]
    ] ],
    [ "lamina", "d1/d42/namespacelamina.html", [
      [ "anonymous_namespace{expression_analysis.cpp}", "d7/d75/namespacelamina_1_1anonymous__namespace_02expression__analysis_8cpp_03.html", [
        [ "FreeVariableQuery", "d2/d94/classlamina_1_1anonymous__namespace_02expression__analysis_8cpp_03_1_1FreeVariableQuery.html", "d2/d94/classlamina_1_1anonymous__namespace_02expression__analysis_8cpp_03_1_1FreeVariableQuery" ]
      ] ],
      [ "anonymous_namespace{integration_trig_substitution.cpp}", "db/d4f/namespacelamina_1_1anonymous__namespace_02integration__trig__substitution_8cpp_03.html", [
        [ "QuadRadical", "db/d4f/namespacelamina_1_1anonymous__namespace_02integration__trig__substitution_8cpp_03.html#db/d5d/structlamina_1_1anonymous__namespace_02integration__trig__substitution_8cpp_03_1_1QuadRadical", "db/d4f/namespacelamina_1_1anonymous__namespace_02integration__trig__substitution_8cpp_03_db/d5d/structlamina_1_1anonymous__namespace_02integration__trig__substitution_8cpp_03_1_1QuadRadical_dup" ]
      ] ],
      [ "anonymous_namespace{interval.cpp}", "dc/d09/namespacelamina_1_1anonymous__namespace_02interval_8cpp_03.html", [
        [ "CheckedInterval", "dc/d09/namespacelamina_1_1anonymous__namespace_02interval_8cpp_03.html#d5/ddd/structlamina_1_1anonymous__namespace_02interval_8cpp_03_1_1CheckedInterval", "dc/d09/namespacelamina_1_1anonymous__namespace_02interval_8cpp_03_d5/ddd/structlamina_1_1anonymous__namespace_02interval_8cpp_03_1_1CheckedInterval_dup" ],
        [ "ComparableEndpoint", "dc/d09/namespacelamina_1_1anonymous__namespace_02interval_8cpp_03.html#dc/df0/structlamina_1_1anonymous__namespace_02interval_8cpp_03_1_1ComparableEndpoint", "dc/d09/namespacelamina_1_1anonymous__namespace_02interval_8cpp_03_dc/df0/structlamina_1_1anonymous__namespace_02interval_8cpp_03_1_1ComparableEndpoint_dup" ]
      ] ],
      [ "anonymous_namespace{numeric_evaluation.cpp}", "df/d81/namespacelamina_1_1anonymous__namespace_02numeric__evaluation_8cpp_03.html", [
        [ "RecursionScope", "d7/de1/classlamina_1_1anonymous__namespace_02numeric__evaluation_8cpp_03_1_1RecursionScope.html", "d7/de1/classlamina_1_1anonymous__namespace_02numeric__evaluation_8cpp_03_1_1RecursionScope" ]
      ] ],
      [ "anonymous_namespace{numerical_integration.cpp}", "da/d1e/namespacelamina_1_1anonymous__namespace_02numerical__integration_8cpp_03.html", [
        [ "IntegrationEstimate", "da/d1e/namespacelamina_1_1anonymous__namespace_02numerical__integration_8cpp_03.html#d4/dce/structlamina_1_1anonymous__namespace_02numerical__integration_8cpp_03_1_1IntegrationEstimate", "da/d1e/namespacelamina_1_1anonymous__namespace_02numerical__integration_8cpp_03_d4/dce/structlamina_1_1anonymous__namespace_02numerical__integration_8cpp_03_1_1IntegrationEstimate_dup" ]
      ] ],
      [ "anonymous_namespace{poly_utils.cpp}", "d0/db5/namespacelamina_1_1anonymous__namespace_02poly__utils_8cpp_03.html", [
        [ "RecursionScope", "dd/d3e/classlamina_1_1anonymous__namespace_02poly__utils_8cpp_03_1_1RecursionScope.html", "dd/d3e/classlamina_1_1anonymous__namespace_02poly__utils_8cpp_03_1_1RecursionScope" ]
      ] ],
      [ "anonymous_namespace{quantity.cpp}", "d7/dd4/namespacelamina_1_1anonymous__namespace_02quantity_8cpp_03.html", [
        [ "QuantityView", "d7/dd4/namespacelamina_1_1anonymous__namespace_02quantity_8cpp_03.html#d9/d28/structlamina_1_1anonymous__namespace_02quantity_8cpp_03_1_1QuantityView", "d7/dd4/namespacelamina_1_1anonymous__namespace_02quantity_8cpp_03_d9/d28/structlamina_1_1anonymous__namespace_02quantity_8cpp_03_1_1QuantityView_dup" ]
      ] ],
      [ "anonymous_namespace{solver_assumptions.cpp}", "d9/d0c/namespacelamina_1_1anonymous__namespace_02solver__assumptions_8cpp_03.html", [
        [ "ContainsImaginaryVisitor", "da/d80/classlamina_1_1anonymous__namespace_02solver__assumptions_8cpp_03_1_1ContainsImaginaryVisitor.html", "da/d80/classlamina_1_1anonymous__namespace_02solver__assumptions_8cpp_03_1_1ContainsImaginaryVisitor" ]
      ] ],
      [ "anonymous_namespace{solver_groebner.cpp}", "df/d55/namespacelamina_1_1anonymous__namespace_02solver__groebner_8cpp_03.html", [
        [ "MonomialLess", "d2/de0/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1MonomialLess.html", "d2/de0/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1MonomialLess" ],
        [ "Poly", "d7/d2a/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1Poly.html", "d7/d2a/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1Poly" ],
        [ "PolyBuilder", "dc/d59/classlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1PolyBuilder.html", "dc/d59/classlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1PolyBuilder" ],
        [ "PolyContext", "dd/d9f/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1PolyContext.html", "dd/d9f/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1PolyContext" ],
        [ "SugarPair", "d4/d13/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1SugarPair.html", "d4/d13/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1SugarPair" ],
        [ "Term", "df/d55/namespacelamina_1_1anonymous__namespace_02solver__groebner_8cpp_03.html#d8/d5f/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1Term", "df/d55/namespacelamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_d8/d5f/structlamina_1_1anonymous__namespace_02solver__groebner_8cpp_03_1_1Term_dup" ]
      ] ],
      [ "anonymous_namespace{symbolic_gcd.cpp}", "dd/d37/namespacelamina_1_1anonymous__namespace_02symbolic__gcd_8cpp_03.html", [
        [ "RecursionFrame", "da/d3f/classlamina_1_1anonymous__namespace_02symbolic__gcd_8cpp_03_1_1RecursionFrame.html", "da/d3f/classlamina_1_1anonymous__namespace_02symbolic__gcd_8cpp_03_1_1RecursionFrame" ]
      ] ],
      [ "detail", "d0/d3a/namespacelamina_1_1detail.html", [
        [ "GaussianEliminator", "df/d30/classlamina_1_1detail_1_1GaussianEliminator.html", "df/d30/classlamina_1_1detail_1_1GaussianEliminator" ],
        [ "MonomialEnumerator", "de/d7c/classlamina_1_1detail_1_1MonomialEnumerator.html", "de/d7c/classlamina_1_1detail_1_1MonomialEnumerator" ],
        [ "MonomialLessUnder", "d9/d67/structlamina_1_1detail_1_1MonomialLessUnder.html", "d9/d67/structlamina_1_1detail_1_1MonomialLessUnder" ],
        [ "ResultPropagation", "da/d89/classlamina_1_1detail_1_1ResultPropagation.html", "da/d89/classlamina_1_1detail_1_1ResultPropagation" ],
        [ "SymbolicExprAccess", "dd/d4b/structlamina_1_1detail_1_1SymbolicExprAccess.html", "dd/d4b/structlamina_1_1detail_1_1SymbolicExprAccess" ],
        [ "SymbolicVisitor", "d4/dd1/classlamina_1_1detail_1_1SymbolicVisitor.html", "d4/dd1/classlamina_1_1detail_1_1SymbolicVisitor" ]
      ] ],
      [ "lsr", "d4/d53/namespacelamina_1_1lsr.html", [
        [ "anonymous_namespace{lsr_expr.cpp}", "d8/d6a/namespacelamina_1_1lsr_1_1anonymous__namespace_02lsr__expr_8cpp_03.html", [
          [ "ExprParser", "db/d6c/classlamina_1_1lsr_1_1anonymous__namespace_02lsr__expr_8cpp_03_1_1ExprParser.html", "db/d6c/classlamina_1_1lsr_1_1anonymous__namespace_02lsr__expr_8cpp_03_1_1ExprParser" ]
        ] ],
        [ "ApproxComplex", "d5/d92/structlamina_1_1lsr_1_1ApproxComplex.html", "d5/d92/structlamina_1_1lsr_1_1ApproxComplex" ],
        [ "Binding", "d4/d53/namespacelamina_1_1lsr.html#d5/ddb/structlamina_1_1lsr_1_1Binding", "d4/d53/namespacelamina_1_1lsr_d5/ddb/structlamina_1_1lsr_1_1Binding_dup" ],
        [ "EqvBudget", "d4/d53/namespacelamina_1_1lsr.html#d5/d34/structlamina_1_1lsr_1_1EqvBudget", "d4/d53/namespacelamina_1_1lsr_d5/d34/structlamina_1_1lsr_1_1EqvBudget_dup" ],
        [ "EqvOptions", "d4/d53/namespacelamina_1_1lsr.html#d5/d11/structlamina_1_1lsr_1_1EqvOptions", "d4/d53/namespacelamina_1_1lsr_d5/d11/structlamina_1_1lsr_1_1EqvOptions_dup" ],
        [ "ExprMatch", "d4/d53/namespacelamina_1_1lsr.html#d3/d04/structlamina_1_1lsr_1_1ExprMatch", "d4/d53/namespacelamina_1_1lsr_d3/d04/structlamina_1_1lsr_1_1ExprMatch_dup" ],
        [ "ExprMatchBinding", "d4/d53/namespacelamina_1_1lsr.html#dc/db5/structlamina_1_1lsr_1_1ExprMatchBinding", "d4/d53/namespacelamina_1_1lsr_dc/db5/structlamina_1_1lsr_1_1ExprMatchBinding_dup" ],
        [ "ExprSet", "d5/d68/classlamina_1_1lsr_1_1ExprSet.html", "d5/d68/classlamina_1_1lsr_1_1ExprSet" ],
        [ "NumberDomainSet", "d1/d88/classlamina_1_1lsr_1_1NumberDomainSet.html", "d1/d88/classlamina_1_1lsr_1_1NumberDomainSet" ]
      ] ],
      [ "ApproxReal", "df/dce/structlamina_1_1ApproxReal.html", "df/dce/structlamina_1_1ApproxReal" ],
      [ "AssumptionContext", "de/dc6/classlamina_1_1AssumptionContext.html", "de/dc6/classlamina_1_1AssumptionContext" ],
      [ "AssumptionDecl", "d7/dfa/classlamina_1_1AssumptionDecl.html", "d7/dfa/classlamina_1_1AssumptionDecl" ],
      [ "AsymptoteResult", "dc/d29/structlamina_1_1AsymptoteResult.html", "dc/d29/structlamina_1_1AsymptoteResult" ],
      [ "BerlekampResult", "db/d5f/structlamina_1_1BerlekampResult.html", "db/d5f/structlamina_1_1BerlekampResult" ],
      [ "CacheKey", "d9/d65/structlamina_1_1CacheKey.html", "d9/d65/structlamina_1_1CacheKey" ],
      [ "CacheKeyHash", "df/dd6/structlamina_1_1CacheKeyHash.html", "df/dd6/structlamina_1_1CacheKeyHash" ],
      [ "CancellationToken", "d5/d90/classlamina_1_1CancellationToken.html", "d5/d90/classlamina_1_1CancellationToken" ],
      [ "CasError", "d1/d42/namespacelamina.html#dc/dbb/structlamina_1_1CasError", "d1/d42/namespacelamina_dc/dbb/structlamina_1_1CasError_dup" ],
      [ "CharRoot", "d1/d42/namespacelamina.html#db/deb/structlamina_1_1CharRoot", "d1/d42/namespacelamina_db/deb/structlamina_1_1CharRoot_dup" ],
      [ "CholeskyDecomposition", "d1/d42/namespacelamina.html#de/db7/structlamina_1_1CholeskyDecomposition", "d1/d42/namespacelamina_de/db7/structlamina_1_1CholeskyDecomposition_dup" ],
      [ "ComplexSymbolic", "d1/d42/namespacelamina.html#df/dff/structlamina_1_1ComplexSymbolic", "d1/d42/namespacelamina_df/dff/structlamina_1_1ComplexSymbolic_dup" ],
      [ "ComputationContext", "df/dac/classlamina_1_1ComputationContext.html", "df/dac/classlamina_1_1ComputationContext" ],
      [ "Conditional", "d1/d42/namespacelamina.html#d6/d9f/structlamina_1_1Conditional", "d1/d42/namespacelamina_d6/d9f/structlamina_1_1Conditional_dup" ],
      [ "ConditionSet", "d1/d42/namespacelamina.html#d4/dbb/structlamina_1_1ConditionSet", "d1/d42/namespacelamina_d4/dbb/structlamina_1_1ConditionSet_dup" ],
      [ "ConvergenceInfo", "d1/d42/namespacelamina.html#d5/d4c/structlamina_1_1ConvergenceInfo", "d1/d42/namespacelamina_d5/d4c/structlamina_1_1ConvergenceInfo_dup" ],
      [ "CriticalPoint", "d8/db4/structlamina_1_1CriticalPoint.html", "d8/db4/structlamina_1_1CriticalPoint" ],
      [ "Diagnostic", "d1/d42/namespacelamina.html#db/d97/structlamina_1_1Diagnostic", "d1/d42/namespacelamina_db/d97/structlamina_1_1Diagnostic_dup" ],
      [ "DiagnosticEngine", "de/d08/classlamina_1_1DiagnosticEngine.html", "de/d08/classlamina_1_1DiagnosticEngine" ],
      [ "DimensionSignature", "d5/d2f/classlamina_1_1DimensionSignature.html", "d5/d2f/classlamina_1_1DimensionSignature" ],
      [ "Endpoint", "df/dd1/structlamina_1_1Endpoint.html", "df/dd1/structlamina_1_1Endpoint" ],
      [ "ExpBasePattern", "d1/d42/namespacelamina.html#d5/d6a/structlamina_1_1ExpBasePattern", "d1/d42/namespacelamina_d5/d6a/structlamina_1_1ExpBasePattern_dup" ],
      [ "FGLMPoly", "d4/d4e/structlamina_1_1FGLMPoly.html", "d4/d4e/structlamina_1_1FGLMPoly" ],
      [ "FiniteSolution", "d1/d42/namespacelamina.html#d7/db2/structlamina_1_1FiniteSolution", "d1/d42/namespacelamina_d7/db2/structlamina_1_1FiniteSolution_dup" ],
      [ "FrobeniusSolution", "d1/d42/namespacelamina.html#d9/d05/structlamina_1_1FrobeniusSolution", "d1/d42/namespacelamina_d9/d05/structlamina_1_1FrobeniusSolution_dup" ],
      [ "HenselLiftPair", "d1/d42/namespacelamina.html#d2/d09/structlamina_1_1HenselLiftPair", "d1/d42/namespacelamina_d2/d09/structlamina_1_1HenselLiftPair_dup" ],
      [ "IBPStrategy", "d1/d83/classlamina_1_1IBPStrategy.html", "d1/d83/classlamina_1_1IBPStrategy" ],
      [ "InequalitySolver", "db/d26/classlamina_1_1InequalitySolver.html", "db/d26/classlamina_1_1InequalitySolver" ],
      [ "InferenceEngine", "d2/d48/classlamina_1_1InferenceEngine.html", "d2/d48/classlamina_1_1InferenceEngine" ],
      [ "IntegralResult", "d1/d42/namespacelamina.html#d7/d09/structlamina_1_1IntegralResult", "d1/d42/namespacelamina_d7/d09/structlamina_1_1IntegralResult_dup" ],
      [ "IntegrationEntry", "d4/d48/structlamina_1_1IntegrationEntry.html", "d4/d48/structlamina_1_1IntegrationEntry" ],
      [ "IntegrationStep", "d1/d42/namespacelamina.html#dd/df8/structlamina_1_1IntegrationStep", "d1/d42/namespacelamina_dd/df8/structlamina_1_1IntegrationStep_dup" ],
      [ "IntegrationStrategy", "d3/d27/classlamina_1_1IntegrationStrategy.html", "d3/d27/classlamina_1_1IntegrationStrategy" ],
      [ "IntegrationTable", "dd/d53/classlamina_1_1IntegrationTable.html", "dd/d53/classlamina_1_1IntegrationTable" ],
      [ "Integrator", "d8/dbb/classlamina_1_1Integrator.html", "d8/dbb/classlamina_1_1Integrator" ],
      [ "Interval", "db/d7f/structlamina_1_1Interval.html", "db/d7f/structlamina_1_1Interval" ],
      [ "IntervalSolution", "d1/d42/namespacelamina.html#d3/dee/structlamina_1_1IntervalSolution", "d1/d42/namespacelamina_d3/dee/structlamina_1_1IntervalSolution_dup" ],
      [ "IntervalUnion", "de/d2c/classlamina_1_1IntervalUnion.html", "de/d2c/classlamina_1_1IntervalUnion" ],
      [ "InversePattern", "d1/d42/namespacelamina.html#d9/d52/structlamina_1_1InversePattern", "d1/d42/namespacelamina_d9/d52/structlamina_1_1InversePattern_dup" ],
      [ "IsolatedInterval", "d1/d42/namespacelamina.html#db/dfc/structlamina_1_1IsolatedInterval", "d1/d42/namespacelamina_db/dfc/structlamina_1_1IsolatedInterval_dup" ],
      [ "JordanDecomposition", "d1/d42/namespacelamina.html#da/d13/structlamina_1_1JordanDecomposition", "d1/d42/namespacelamina_da/d13/structlamina_1_1JordanDecomposition_dup" ],
      [ "LambertWPattern", "d1/d42/namespacelamina.html#d0/d98/structlamina_1_1LambertWPattern", "d1/d42/namespacelamina_d0/d98/structlamina_1_1LambertWPattern_dup" ],
      [ "LaurentResult", "d1/d42/namespacelamina.html#d1/d19/structlamina_1_1LaurentResult", "d1/d42/namespacelamina_d1/d19/structlamina_1_1LaurentResult_dup" ],
      [ "LinearSubstitutionStrategy", "d6/d86/classlamina_1_1LinearSubstitutionStrategy.html", "d6/d86/classlamina_1_1LinearSubstitutionStrategy" ],
      [ "LineSymbolic", "d1/d42/namespacelamina.html#da/dfd/structlamina_1_1LineSymbolic", "d1/d42/namespacelamina_da/dfd/structlamina_1_1LineSymbolic_dup" ],
      [ "LUDecomposition", "d1/d42/namespacelamina.html#d8/d06/structlamina_1_1LUDecomposition", "d1/d42/namespacelamina_d8/d06/structlamina_1_1LUDecomposition_dup" ],
      [ "Matcher", "d5/d68/classlamina_1_1Matcher.html", "d5/d68/classlamina_1_1Matcher" ],
      [ "MathResult", "d1/d42/namespacelamina.html#df/d15/structlamina_1_1MathResult", "d1/d42/namespacelamina_df/d15/structlamina_1_1MathResult_dup" ],
      [ "ModInt", "dc/d15/classlamina_1_1ModInt.html", "dc/d15/classlamina_1_1ModInt" ],
      [ "MonomialOrder", "da/d68/classlamina_1_1MonomialOrder.html", "da/d68/classlamina_1_1MonomialOrder" ],
      [ "MultiFactorResult", "d1/d42/namespacelamina.html#d8/d99/structlamina_1_1MultiFactorResult", "d1/d42/namespacelamina_d8/d99/structlamina_1_1MultiFactorResult_dup" ],
      [ "MultiPoly", "de/d3a/classlamina_1_1MultiPoly.html", "de/d3a/classlamina_1_1MultiPoly" ],
      [ "NodeLess", "d3/df4/structlamina_1_1NodeLess.html", "d3/df4/structlamina_1_1NodeLess" ],
      [ "NumericRoot", "d1/d42/namespacelamina.html#df/de4/structlamina_1_1NumericRoot", "d1/d42/namespacelamina_df/de4/structlamina_1_1NumericRoot_dup" ],
      [ "ODEClassification", "d1/d42/namespacelamina.html#da/d3f/structlamina_1_1ODEClassification", "d1/d42/namespacelamina_da/d3f/structlamina_1_1ODEClassification_dup" ],
      [ "ODESolution", "d1/d42/namespacelamina.html#de/dc3/structlamina_1_1ODESolution", "d1/d42/namespacelamina_de/dc3/structlamina_1_1ODESolution_dup" ],
      [ "ParametricSolver", "d6/da9/classlamina_1_1ParametricSolver.html", "d6/da9/classlamina_1_1ParametricSolver" ],
      [ "PartialFractionStrategy", "d6/d58/classlamina_1_1PartialFractionStrategy.html", "d6/d58/classlamina_1_1PartialFractionStrategy" ],
      [ "PeriodicCollector", "d5/d08/structlamina_1_1PeriodicCollector.html", "d5/d08/structlamina_1_1PeriodicCollector" ],
      [ "PiecewiseIntervalResult", "d2/d68/structlamina_1_1PiecewiseIntervalResult.html", "d2/d68/structlamina_1_1PiecewiseIntervalResult" ],
      [ "PiecewiseSolution", "d1/d42/namespacelamina.html#dd/d48/structlamina_1_1PiecewiseSolution", "d1/d42/namespacelamina_dd/d48/structlamina_1_1PiecewiseSolution_dup" ],
      [ "PlaneSymbolic", "d1/d42/namespacelamina.html#d8/db0/structlamina_1_1PlaneSymbolic", "d1/d42/namespacelamina_d8/db0/structlamina_1_1PlaneSymbolic_dup" ],
      [ "Polynomial", "d8/d1e/classlamina_1_1Polynomial.html", "d8/d1e/classlamina_1_1Polynomial" ],
      [ "PowerRuleStrategy", "d0/df8/classlamina_1_1PowerRuleStrategy.html", "d0/df8/classlamina_1_1PowerRuleStrategy" ],
      [ "PropertyStore", "d3/dba/classlamina_1_1PropertyStore.html", "d3/dba/classlamina_1_1PropertyStore" ],
      [ "QRDecomposition", "d1/d42/namespacelamina.html#d9/dd4/structlamina_1_1QRDecomposition", "d1/d42/namespacelamina_d9/dd4/structlamina_1_1QRDecomposition_dup" ],
      [ "QueryInterface", "df/de3/classlamina_1_1QueryInterface.html", "df/de3/classlamina_1_1QueryInterface" ],
      [ "RationalDecompositionStrategy", "de/d78/classlamina_1_1RationalDecompositionStrategy.html", "de/d78/classlamina_1_1RationalDecompositionStrategy" ],
      [ "Relation", "d1/d42/namespacelamina.html#dd/d91/structlamina_1_1Relation", "d1/d42/namespacelamina_dd/d91/structlamina_1_1Relation_dup" ],
      [ "RelationStore", "de/db6/classlamina_1_1RelationStore.html", "de/db6/classlamina_1_1RelationStore" ],
      [ "ReplacementVisitor", "d5/ddd/classlamina_1_1ReplacementVisitor.html", "d5/ddd/classlamina_1_1ReplacementVisitor" ],
      [ "ResourceLimits", "d1/d42/namespacelamina.html#d0/d6c/structlamina_1_1ResourceLimits", "d1/d42/namespacelamina_d0/d6c/structlamina_1_1ResourceLimits_dup" ],
      [ "Result", "d4/d81/classlamina_1_1Result.html", "d4/d81/classlamina_1_1Result" ],
      [ "Result&lt; void &gt;", "d4/db8/classlamina_1_1Result_3_01void_01_4.html", "d4/db8/classlamina_1_1Result_3_01void_01_4" ],
      [ "RewriteEngine", "d2/dbd/classlamina_1_1RewriteEngine.html", "d2/dbd/classlamina_1_1RewriteEngine" ],
      [ "RewriteVisitor", "d5/dd7/classlamina_1_1RewriteVisitor.html", "d5/dd7/classlamina_1_1RewriteVisitor" ],
      [ "RootWithIndex", "d1/d42/namespacelamina.html#de/d9e/structlamina_1_1RootWithIndex", "d1/d42/namespacelamina_de/d9e/structlamina_1_1RootWithIndex_dup" ],
      [ "Rule", "de/d71/structlamina_1_1Rule.html", "de/d71/structlamina_1_1Rule" ],
      [ "SearchInterval", "d1/d42/namespacelamina.html#d1/d65/structlamina_1_1SearchInterval", "d1/d42/namespacelamina_d1/d65/structlamina_1_1SearchInterval_dup" ],
      [ "SignChartEntry", "d1/d42/namespacelamina.html#d0/de6/structlamina_1_1SignChartEntry", "d1/d42/namespacelamina_d0/de6/structlamina_1_1SignChartEntry_dup" ],
      [ "SignHash", "db/dd2/structlamina_1_1SignHash.html", "db/dd2/structlamina_1_1SignHash" ],
      [ "SolutionSet", "d7/d6c/classlamina_1_1SolutionSet.html", "d7/d6c/classlamina_1_1SolutionSet" ],
      [ "SolveOptions", "d1/d42/namespacelamina.html#da/d00/structlamina_1_1SolveOptions", "d1/d42/namespacelamina_da/d00/structlamina_1_1SolveOptions_dup" ],
      [ "Solver", "d5/d6f/classlamina_1_1Solver.html", "d5/d6f/classlamina_1_1Solver" ],
      [ "SpecialFunctionStrategy", "df/d67/classlamina_1_1SpecialFunctionStrategy.html", "df/d67/classlamina_1_1SpecialFunctionStrategy" ],
      [ "SquareFreeDecomp", "d1/d42/namespacelamina.html#de/d2a/structlamina_1_1SquareFreeDecomp", "d1/d42/namespacelamina_de/d2a/structlamina_1_1SquareFreeDecomp_dup" ],
      [ "SubstitutionResult", "d1/d42/namespacelamina.html#d7/dd4/structlamina_1_1SubstitutionResult", "d1/d42/namespacelamina_d7/dd4/structlamina_1_1SubstitutionResult_dup" ],
      [ "SubstitutionStrategy", "d5/df5/classlamina_1_1SubstitutionStrategy.html", "d5/df5/classlamina_1_1SubstitutionStrategy" ],
      [ "SurfaceSymbolic", "d1/d42/namespacelamina.html#dd/d43/structlamina_1_1SurfaceSymbolic", "d1/d42/namespacelamina_dd/d43/structlamina_1_1SurfaceSymbolic_dup" ],
      [ "SVDDecomposition", "d1/d42/namespacelamina.html#dc/dfc/structlamina_1_1SVDDecomposition", "d1/d42/namespacelamina_dc/dfc/structlamina_1_1SVDDecomposition_dup" ],
      [ "SymbolicPolyCoeff", "d1/df9/structlamina_1_1SymbolicPolyCoeff.html", "d1/df9/structlamina_1_1SymbolicPolyCoeff" ],
      [ "TableLookupStrategy", "de/d21/classlamina_1_1TableLookupStrategy.html", "de/d21/classlamina_1_1TableLookupStrategy" ],
      [ "TfPolyBuildResult", "d2/dee/structlamina_1_1TfPolyBuildResult.html", "d2/dee/structlamina_1_1TfPolyBuildResult" ],
      [ "TfSquareFreeResult", "d3/d8c/structlamina_1_1TfSquareFreeResult.html", "d3/d8c/structlamina_1_1TfSquareFreeResult" ],
      [ "TransformResult", "d1/d42/namespacelamina.html#d6/d41/structlamina_1_1TransformResult", "d1/d42/namespacelamina_d6/d41/structlamina_1_1TransformResult_dup" ],
      [ "TransformTable", "de/d20/classlamina_1_1TransformTable.html", "de/d20/classlamina_1_1TransformTable" ],
      [ "TransformTableEntry", "d1/d42/namespacelamina.html#d8/df1/structlamina_1_1TransformTableEntry", "d1/d42/namespacelamina_d8/df1/structlamina_1_1TransformTableEntry_dup" ],
      [ "TransSubstitution", "d1/d42/namespacelamina.html#d4/d2b/structlamina_1_1TransSubstitution", "d1/d42/namespacelamina_d4/d2b/structlamina_1_1TransSubstitution_dup" ],
      [ "TransSubstitutionResult", "d1/d42/namespacelamina.html#db/db4/structlamina_1_1TransSubstitutionResult", "d1/d42/namespacelamina_db/db4/structlamina_1_1TransSubstitutionResult_dup" ],
      [ "TrigCombinationStrategy", "dd/ddb/classlamina_1_1TrigCombinationStrategy.html", "dd/ddb/classlamina_1_1TrigCombinationStrategy" ],
      [ "TrigSubstitutionStrategy", "d3/d9a/classlamina_1_1TrigSubstitutionStrategy.html", "d3/d9a/classlamina_1_1TrigSubstitutionStrategy" ],
      [ "UnitDefinition", "d1/d42/namespacelamina.html#dc/deb/structlamina_1_1UnitDefinition", "d1/d42/namespacelamina_dc/deb/structlamina_1_1UnitDefinition_dup" ],
      [ "UnitSystem", "de/dad/classlamina_1_1UnitSystem.html", "de/dad/classlamina_1_1UnitSystem" ],
      [ "WeierstrassStrategy", "d9/dc4/classlamina_1_1WeierstrassStrategy.html", "d9/dc4/classlamina_1_1WeierstrassStrategy" ]
    ] ],
    [ "AddNode", "d8/d2e/classAddNode.html", "d8/d2e/classAddNode" ],
    [ "BigInt", "da/d5b/classBigInt.html", "da/d5b/classBigInt" ],
    [ "ComplexNode", "da/d65/classComplexNode.html", "da/d65/classComplexNode" ],
    [ "DifferentiationVisitor", "d3/d1a/classDifferentiationVisitor.html", "d3/d1a/classDifferentiationVisitor" ],
    [ "ExpandVisitor", "db/d5d/classExpandVisitor.html", "db/d5d/classExpandVisitor" ],
    [ "FiniteSetNode", "df/db2/classFiniteSetNode.html", "df/db2/classFiniteSetNode" ],
    [ "FunctionNode", "d7/d06/classFunctionNode.html", "d7/d06/classFunctionNode" ],
    [ "IntervalNode", "d8/daa/classIntervalNode.html", "d8/daa/classIntervalNode" ],
    [ "Irrational", "d8/df2/classIrrational.html", "d8/df2/classIrrational" ],
    [ "LimitVisitor", "dd/d23/classLimitVisitor.html", "dd/d23/classLimitVisitor" ],
    [ "LogicalNode", "d9/d2c/classLogicalNode.html", "d9/d2c/classLogicalNode" ],
    [ "MatrixNode", "d3/d86/classMatrixNode.html", "d3/d86/classMatrixNode" ],
    [ "MembershipNode", "d5/d5d/classMembershipNode.html", "d5/d5d/classMembershipNode" ],
    [ "MultiplyNode", "dd/dce/classMultiplyNode.html", "dd/dce/classMultiplyNode" ],
    [ "NodeCompare", "d3/d84/structNodeCompare.html", "d3/d84/structNodeCompare" ],
    [ "NodeEqual", "d8/d71/structNodeEqual.html", "d8/d71/structNodeEqual" ],
    [ "NodeHash", "d3/d15/structNodeHash.html", "d3/d15/structNodeHash" ],
    [ "NormalizationVisitor", "d3/da1/classNormalizationVisitor.html", "d3/da1/classNormalizationVisitor" ],
    [ "NumberNode", "dc/dea/classNumberNode.html", "dc/dea/classNumberNode" ],
    [ "PiecewiseNode", "d3/d99/classPiecewiseNode.html", "d3/d99/classPiecewiseNode" ],
    [ "PowerNode", "d5/d72/classPowerNode.html", "d5/d72/classPowerNode" ],
    [ "PrintVisitor", "d5/d46/classPrintVisitor.html", "d5/d46/classPrintVisitor" ],
    [ "ProductNode", "d6/da7/classProductNode.html", "d6/da7/classProductNode" ],
    [ "QuantifierNode", "d5/d0c/classQuantifierNode.html", "d5/d0c/classQuantifierNode" ],
    [ "QuantityNode", "d4/da1/classQuantityNode.html", "d4/da1/classQuantityNode" ],
    [ "Rational", "d8/da7/classRational.html", "d8/da7/classRational" ],
    [ "RelationalNode", "d7/d58/classRelationalNode.html", "d7/d58/classRelationalNode" ],
    [ "SetBuilderNode", "dd/db0/classSetBuilderNode.html", "dd/db0/classSetBuilderNode" ],
    [ "SubstituteVisitor", "d2/d6b/classSubstituteVisitor.html", "d2/d6b/classSubstituteVisitor" ],
    [ "SummationNode", "db/da6/classSummationNode.html", "db/da6/classSummationNode" ],
    [ "SymbolicExpr", "dc/d25/classSymbolicExpr.html", "dc/d25/classSymbolicExpr" ],
    [ "SymbolicFactory", "d6/db0/classSymbolicFactory.html", "d6/db0/classSymbolicFactory" ],
    [ "SymbolicNode", "dc/dc3/classSymbolicNode.html", "dc/dc3/classSymbolicNode" ],
    [ "TransformNode", "db/dac/classTransformNode.html", "db/dac/classTransformNode" ],
    [ "UninterpretedFunctionNode", "d8/d09/classUninterpretedFunctionNode.html", "d8/d09/classUninterpretedFunctionNode" ],
    [ "Value", "dc/dcb/classValue.html", "dc/dcb/classValue" ],
    [ "VariableNode", "d5/d93/classVariableNode.html", "d5/d93/classVariableNode" ],
    [ "VariablesVisitor", "d3/d37/classVariablesVisitor.html", "d3/d37/classVariablesVisitor" ]
];