var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "visitors", "dir_4e5658a7286517e9c5b1437feaf10aed.html", "dir_4e5658a7286517e9c5b1437feaf10aed" ],
    [ "assumption.hpp", "de/db0/assumption_8hpp.html", "de/db0/assumption_8hpp" ],
    [ "assumption_context.hpp", "d4/d10/assumption__context_8hpp.html", "d4/d10/assumption__context_8hpp" ],
    [ "bigint.hpp", "d8/d09/bigint_8hpp.html", "d8/d09/bigint_8hpp" ],
    [ "fglm.hpp", "df/d77/fglm_8hpp.html", "df/d77/fglm_8hpp" ],
    [ "inequality_solver.hpp", "d1/d0e/inequality__solver_8hpp.html", "d1/d0e/inequality__solver_8hpp" ],
    [ "inference_engine.hpp", "d8/dcd/inference__engine_8hpp.html", "d8/dcd/inference__engine_8hpp" ],
    [ "integration.hpp", "d9/d15/integration_8hpp.html", "d9/d15/integration_8hpp" ],
    [ "interval.hpp", "dc/de2/interval_8hpp.html", "dc/de2/interval_8hpp" ],
    [ "irrational.hpp", "d4/d49/irrational_8hpp.html", "d4/d49/irrational_8hpp" ],
    [ "matcher.hpp", "d1/da4/matcher_8hpp.html", "d1/da4/matcher_8hpp" ],
    [ "modular_arithmetic.hpp", "d6/d47/modular__arithmetic_8hpp.html", "d6/d47/modular__arithmetic_8hpp" ],
    [ "monomial_order.hpp", "db/d4d/monomial__order_8hpp.html", "db/d4d/monomial__order_8hpp" ],
    [ "newton_raphson.hpp", "d5/d53/newton__raphson_8hpp.html", "d5/d53/newton__raphson_8hpp" ],
    [ "parametric_solver.hpp", "d4/da6/parametric__solver_8hpp.html", "d4/da6/parametric__solver_8hpp" ],
    [ "poly_utils.hpp", "d9/d39/poly__utils_8hpp.html", "d9/d39/poly__utils_8hpp" ],
    [ "polynomial.hpp", "d0/d3e/polynomial_8hpp.html", "d0/d3e/polynomial_8hpp" ],
    [ "property_store.hpp", "d7/dd8/property__store_8hpp.html", "d7/dd8/property__store_8hpp" ],
    [ "query_interface.hpp", "d9/dbb/query__interface_8hpp.html", "d9/dbb/query__interface_8hpp" ],
    [ "rational.hpp", "d1/de8/rational_8hpp.html", "d1/de8/rational_8hpp" ],
    [ "relation_store.hpp", "d1/ddb/relation__store_8hpp.html", "d1/ddb/relation__store_8hpp" ],
    [ "root_of_utils.hpp", "d4/d0a/root__of__utils_8hpp.html", "d4/d0a/root__of__utils_8hpp" ],
    [ "solve_polynomial.hpp", "d2/d12/solve__polynomial_8hpp.html", "d2/d12/solve__polynomial_8hpp" ],
    [ "solve_strategies.hpp", "d5/dd2/solve__strategies_8hpp.html", "d5/dd2/solve__strategies_8hpp" ],
    [ "solve_transcendental.hpp", "d8/d7f/solve__transcendental_8hpp.html", "d8/d7f/solve__transcendental_8hpp" ],
    [ "solver.hpp", "d2/d1c/solver_8hpp.html", "d2/d1c/solver_8hpp" ],
    [ "symbolic.hpp", "d5/df2/symbolic_8hpp.html", "d5/df2/symbolic_8hpp" ],
    [ "symbolic_ast.hpp", "d9/d89/symbolic__ast_8hpp.html", "d9/d89/symbolic__ast_8hpp" ],
    [ "symbolic_complex.hpp", "d7/ddb/symbolic__complex_8hpp.html", "d7/ddb/symbolic__complex_8hpp" ],
    [ "symbolic_geometry.hpp", "da/d47/symbolic__geometry_8hpp.html", "da/d47/symbolic__geometry_8hpp" ],
    [ "symbolic_implicit_diff.hpp", "dd/d84/symbolic__implicit__diff_8hpp.html", "dd/d84/symbolic__implicit__diff_8hpp" ],
    [ "symbolic_matrix.hpp", "d4/d7d/symbolic__matrix_8hpp.html", "d4/d7d/symbolic__matrix_8hpp" ],
    [ "symbolic_ode.hpp", "d1/d51/symbolic__ode_8hpp.html", "d1/d51/symbolic__ode_8hpp" ],
    [ "symbolic_vector_geometry.hpp", "d0/d33/symbolic__vector__geometry_8hpp.html", "d0/d33/symbolic__vector__geometry_8hpp" ],
    [ "value.hpp", "d6/dda/value_8hpp.html", "d6/dda/value_8hpp" ]
];