var hierarchy =
[
    [ "BigInt", "da/d5b/classBigInt.html", null ],
    [ "Irrational", "d8/df2/classIrrational.html", null ],
    [ "lamina::anonymous_namespace{solver.cpp}::MonomialLess", "d2/d29/structlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1MonomialLess.html", null ],
    [ "lamina::anonymous_namespace{solver.cpp}::Poly", "dc/d69/structlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1Poly.html", null ],
    [ "lamina::anonymous_namespace{solver.cpp}::PolyContext", "d3/d79/structlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1PolyContext.html", null ],
    [ "lamina::anonymous_namespace{solver.cpp}::SugarPair", "d2/d40/structlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1SugarPair.html", null ],
    [ "lamina::anonymous_namespace{solver.cpp}::Term", "d3/d3c/namespacelamina_1_1anonymous__namespace_02solver_8cpp_03.html#d7/d4b/structlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1Term", null ],
    [ "lamina::AssumptionContext", "de/dc6/classlamina_1_1AssumptionContext.html", null ],
    [ "lamina::AssumptionContext::Scope", "de/dc6/classlamina_1_1AssumptionContext.html#d4/d31/structlamina_1_1AssumptionContext_1_1Scope", null ],
    [ "lamina::ComplexSymbolic", "d1/d42/namespacelamina.html#df/dff/structlamina_1_1ComplexSymbolic", null ],
    [ "lamina::detail::GaussianEliminator", "df/d30/classlamina_1_1detail_1_1GaussianEliminator.html", null ],
    [ "lamina::detail::MonomialEnumerator", "de/d7c/classlamina_1_1detail_1_1MonomialEnumerator.html", null ],
    [ "lamina::detail::MonomialEnumerator::HeapCmp", "d9/d84/structlamina_1_1detail_1_1MonomialEnumerator_1_1HeapCmp.html", null ],
    [ "lamina::detail::MonomialLessUnder", "d9/d67/structlamina_1_1detail_1_1MonomialLessUnder.html", null ],
    [ "lamina::Endpoint", "df/dd1/structlamina_1_1Endpoint.html", null ],
    [ "lamina::ExpBasePattern", "d1/d42/namespacelamina.html#d5/d6a/structlamina_1_1ExpBasePattern", null ],
    [ "lamina::FGLMPoly", "d4/d4e/structlamina_1_1FGLMPoly.html", null ],
    [ "lamina::InequalitySolver", "db/d26/classlamina_1_1InequalitySolver.html", null ],
    [ "lamina::InferenceEngine", "d2/d48/classlamina_1_1InferenceEngine.html", null ],
    [ "lamina::IntegrationEntry", "d4/d48/structlamina_1_1IntegrationEntry.html", null ],
    [ "lamina::IntegrationStrategy", "d3/d27/classlamina_1_1IntegrationStrategy.html", [
      [ "lamina::IBPStrategy", "d1/d83/classlamina_1_1IBPStrategy.html", null ],
      [ "lamina::LinearSubstitutionStrategy", "d6/d86/classlamina_1_1LinearSubstitutionStrategy.html", null ],
      [ "lamina::PartialFractionStrategy", "d6/d58/classlamina_1_1PartialFractionStrategy.html", null ],
      [ "lamina::PowerRuleStrategy", "d0/df8/classlamina_1_1PowerRuleStrategy.html", null ],
      [ "lamina::RationalDecompositionStrategy", "de/d78/classlamina_1_1RationalDecompositionStrategy.html", null ],
      [ "lamina::SpecialFunctionStrategy", "df/d67/classlamina_1_1SpecialFunctionStrategy.html", null ],
      [ "lamina::SubstitutionStrategy", "d5/df5/classlamina_1_1SubstitutionStrategy.html", null ],
      [ "lamina::TableLookupStrategy", "de/d21/classlamina_1_1TableLookupStrategy.html", null ],
      [ "lamina::TrigCombinationStrategy", "dd/ddb/classlamina_1_1TrigCombinationStrategy.html", null ]
    ] ],
    [ "lamina::IntegrationTable", "dd/d53/classlamina_1_1IntegrationTable.html", null ],
    [ "lamina::Integrator", "d8/dbb/classlamina_1_1Integrator.html", null ],
    [ "lamina::Integrator::CycleState", "d8/dbb/classlamina_1_1Integrator.html#dc/dbf/structlamina_1_1Integrator_1_1CycleState", null ],
    [ "lamina::Interval", "db/d7f/structlamina_1_1Interval.html", null ],
    [ "lamina::IntervalUnion", "de/d2c/classlamina_1_1IntervalUnion.html", null ],
    [ "lamina::InversePattern", "d1/d42/namespacelamina.html#d9/d52/structlamina_1_1InversePattern", null ],
    [ "lamina::LambertWPattern", "d1/d42/namespacelamina.html#d0/d98/structlamina_1_1LambertWPattern", null ],
    [ "lamina::LineSymbolic", "d1/d42/namespacelamina.html#da/dfd/structlamina_1_1LineSymbolic", null ],
    [ "lamina::Matcher", "d5/d68/classlamina_1_1Matcher.html", null ],
    [ "lamina::ModInt", "dc/d15/classlamina_1_1ModInt.html", null ],
    [ "lamina::MonomialOrder", "da/d68/classlamina_1_1MonomialOrder.html", null ],
    [ "lamina::MultipleIntegralEngine", "d0/d72/classlamina_1_1MultipleIntegralEngine.html", null ],
    [ "lamina::MultipleIntegralEngine::IntegrationStep", "d0/d72/classlamina_1_1MultipleIntegralEngine.html#d5/de6/structlamina_1_1MultipleIntegralEngine_1_1IntegrationStep", null ],
    [ "lamina::NodeLess", "d3/df4/structlamina_1_1NodeLess.html", null ],
    [ "lamina::NumericRoot", "d1/d42/namespacelamina.html#df/de4/structlamina_1_1NumericRoot", null ],
    [ "lamina::ParametricSolver", "d6/da9/classlamina_1_1ParametricSolver.html", null ],
    [ "lamina::PiecewiseIntervalResult", "d2/d68/structlamina_1_1PiecewiseIntervalResult.html", null ],
    [ "lamina::PiecewiseIntervalResult::Case", "d2/d68/structlamina_1_1PiecewiseIntervalResult.html#d7/d68/structlamina_1_1PiecewiseIntervalResult_1_1Case", null ],
    [ "lamina::PiecewiseSolution", "d1/d42/namespacelamina.html#dd/d48/structlamina_1_1PiecewiseSolution", null ],
    [ "lamina::PiecewiseSolution::Case", "d1/d42/namespacelamina.html#da/d35/structlamina_1_1PiecewiseSolution_1_1Case", null ],
    [ "lamina::PlaneSymbolic", "d1/d42/namespacelamina.html#d8/db0/structlamina_1_1PlaneSymbolic", null ],
    [ "lamina::Polynomial< CoeffType >", "d8/d1e/classlamina_1_1Polynomial.html", null ],
    [ "lamina::PropertyStore", "d3/dba/classlamina_1_1PropertyStore.html", null ],
    [ "lamina::PropertyStore::SymbolProperties", "d3/dba/classlamina_1_1PropertyStore.html#d3/d1d/structlamina_1_1PropertyStore_1_1SymbolProperties", null ],
    [ "lamina::QueryInterface", "df/de3/classlamina_1_1QueryInterface.html", null ],
    [ "lamina::Relation", "d1/d42/namespacelamina.html#dd/d91/structlamina_1_1Relation", null ],
    [ "lamina::RelationStore", "de/db6/classlamina_1_1RelationStore.html", null ],
    [ "lamina::RewriteEngine", "d2/dbd/classlamina_1_1RewriteEngine.html", null ],
    [ "lamina::RootWithIndex", "d1/d42/namespacelamina.html#de/d9e/structlamina_1_1RootWithIndex", null ],
    [ "lamina::Rule", "de/d71/structlamina_1_1Rule.html", null ],
    [ "lamina::SignChartEntry", "d1/d42/namespacelamina.html#d0/de6/structlamina_1_1SignChartEntry", null ],
    [ "lamina::SignHash", "db/dd2/structlamina_1_1SignHash.html", null ],
    [ "lamina::SolveOptions", "d1/d42/namespacelamina.html#da/d00/structlamina_1_1SolveOptions", null ],
    [ "lamina::Solver", "d5/d6f/classlamina_1_1Solver.html", null ],
    [ "lamina::SubstitutionResult", "d1/d42/namespacelamina.html#d7/dd4/structlamina_1_1SubstitutionResult", null ],
    [ "lamina::SymbolicPolyCoeff", "d1/df9/structlamina_1_1SymbolicPolyCoeff.html", null ],
    [ "NodeCompare", "d3/d84/structNodeCompare.html", null ],
    [ "NodeEqual", "d8/d71/structNodeEqual.html", null ],
    [ "NodeHash", "d3/d15/structNodeHash.html", null ],
    [ "Rational", "d8/da7/classRational.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "SymbolicExpr", "dc/d25/classSymbolicExpr.html", null ]
    ] ],
    [ "std::streambuf", null, [
      [ "_NullBuffer", "dc/d83/class__NullBuffer.html", null ]
    ] ],
    [ "SymbolicFactory", "d6/db0/classSymbolicFactory.html", null ],
    [ "SymbolicNode", "dc/dc3/classSymbolicNode.html", [
      [ "AddNode", "d8/d2e/classAddNode.html", null ],
      [ "FunctionNode", "d7/d06/classFunctionNode.html", null ],
      [ "LogicalNode", "d9/d2c/classLogicalNode.html", null ],
      [ "MatrixNode", "d3/d86/classMatrixNode.html", null ],
      [ "MultiplyNode", "dd/dce/classMultiplyNode.html", null ],
      [ "NumberNode", "dc/dea/classNumberNode.html", null ],
      [ "PowerNode", "d5/d72/classPowerNode.html", null ],
      [ "RelationalNode", "d7/d58/classRelationalNode.html", null ],
      [ "VariableNode", "d5/d93/classVariableNode.html", null ]
    ] ],
    [ "SymbolicVisitor", "da/dcb/classSymbolicVisitor.html", [
      [ "DifferentiationVisitor", "d3/d1a/classDifferentiationVisitor.html", null ],
      [ "ExpandVisitor", "db/d5d/classExpandVisitor.html", null ],
      [ "IntegrationVisitor", "d0/d2d/classIntegrationVisitor.html", null ],
      [ "LimitVisitor", "dd/d23/classLimitVisitor.html", null ],
      [ "NormalizationVisitor", "d3/da1/classNormalizationVisitor.html", null ],
      [ "PrintVisitor", "d5/d46/classPrintVisitor.html", null ],
      [ "SubstituteVisitor", "d2/d6b/classSubstituteVisitor.html", null ],
      [ "VariablesVisitor", "d3/d37/classVariablesVisitor.html", null ],
      [ "lamina::ReplacementVisitor", "d5/ddd/classlamina_1_1ReplacementVisitor.html", null ],
      [ "lamina::RewriteVisitor", "d5/dd7/classlamina_1_1RewriteVisitor.html", null ],
      [ "lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor", "d0/d2c/classlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1ContainsImaginaryVisitor.html", null ],
      [ "lamina::anonymous_namespace{solver.cpp}::PolyBuilder", "d7/d8e/classlamina_1_1anonymous__namespace_02solver_8cpp_03_1_1PolyBuilder.html", null ]
    ] ],
    [ "SymbolicVisitor::DepthGuard", "d2/d1a/structSymbolicVisitor_1_1DepthGuard.html", null ],
    [ "Value", "dc/dcb/classValue.html", null ]
];