solver.cpp
using lamina::anonymous_namespace{solver.cpp}::Monomial = typedef std::vector<int>
using lamina::anonymous_namespace{solver.cpp}::PolyTerms = typedef std::map<Monomial, Rational, MonomialLess>
static std::shared_ptr< NumberNode > lamina::add_number_nodes(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
References lamina::Rational.
Referenced by lamina::multiply_no_expand.
Poly lamina::anonymous_namespace{solver.cpp}::add_poly(const Poly &a, const Poly &b)
References lamina::anonymous_namespace{solver.cpp}::add_poly, lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::anonymous_namespace{solver.cpp}::add_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
bool lamina::anonymous_namespace{solver.cpp}::chain_criterion(const std::vector< Poly > &G, size_t i, size_t j, const std::set< std::pair< size_t, size_t > > &processed_pairs)
References lamina::anonymous_namespace{solver.cpp}::divides_mono, lamina::anonymous_namespace{solver.cpp}::lcm_mono.
Referenced by lamina::Solver::groebner_basis.
static bool lamina::collect_denominator_factors(const std::shared_ptr< SymbolicNode > &node, std::vector< std::shared_ptr< SymbolicNode > > &den_factors, std::vector< std::shared_ptr< SymbolicExpr > > &den_constraints)
References lamina::collect_denominator_factors, SymbolicFactory::create_number, SymbolicFactory::create_power, lamina::get_integer_value, lamina::is_polynomial_node.
Referenced by lamina::collect_denominator_factors, lamina::Solver::solve_polynomial_system.
int lamina::anonymous_namespace{solver.cpp}::compute_spoly_sugar(const Poly &f, const Poly &g)
References lamina::anonymous_namespace{solver.cpp}::lcm_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Poly::sugar.
Referenced by lamina::Solver::groebner_basis.
static bool lamina::anonymous_namespace{solver.cpp}::contains_imaginary(const std::shared_ptr< SymbolicExpr > &expr)
Check if a solution expression contains imaginary components (sqrt of negative).
References lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::found.
Referenced by lamina::solve_with_assumptions.
bool lamina::anonymous_namespace{solver.cpp}::coprime_leading_monomials(const Poly &f, const Poly &g)
References lamina::anonymous_namespace{solver.cpp}::Poly::is_zero, lamina::anonymous_namespace{solver.cpp}::Poly::LM.
Referenced by lamina::Solver::groebner_basis.
Monomial lamina::anonymous_namespace{solver.cpp}::div_mono(const Monomial &num, const Monomial &den)
References lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::num.
Referenced by lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::s_poly.
bool lamina::anonymous_namespace{solver.cpp}::divides_mono(const Monomial &a, const Monomial &b)
References lamina::anonymous_namespace{solver.cpp}::divides_mono.
Referenced by lamina::anonymous_namespace{solver.cpp}::chain_criterion, lamina::anonymous_namespace{solver.cpp}::divides_mono, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::Solver::reduced_groebner_basis.
SymbolicExpr lamina::anonymous_namespace{solver.cpp}::from_poly(const Poly &p, const std::vector< std::string > &vars)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_power, SymbolicFactory::create_variable, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
SymbolicExpr lamina::anonymous_namespace{solver.cpp}::from_poly_ext(const Poly &p, const PolyContext &ctx, const std::vector< std::string > &original_vars)
References lamina::anonymous_namespace{solver.cpp}::PolyContext::aux_to_node, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_power, SymbolicFactory::create_variable, lamina::anonymous_namespace{solver.cpp}::PolyContext::ext_vars, lamina::anonymous_namespace{solver.cpp}::PolyContext::num_original_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::Solver::groebner_basis, lamina::Solver::reduced_groebner_basis.
void lamina::gaussian_eliminate(std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &A, size_t m, size_t n, std::vector< size_t > &pivot_col_for_row, int &sign)
对增广矩阵进行高斯消元
A 增广矩阵（符号表达式元素） m 行数 n 列数 pivot_col_for_row 输出各行的主元列号 sign 输出行交换的符号（+1 或 -1）
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power.
Referenced by lamina::Solver::solve_linear_system, SymbolicExpr::solve_system.
static bool lamina::get_integer_value(const std::shared_ptr< SymbolicNode > &node, long long &value)
References lamina::num.
Referenced by lamina::collect_denominator_factors, lamina::is_polynomial_node.
static bool lamina::anonymous_namespace{solver.cpp}::is_integer_value(double v)
Check if a numeric value is an integer (within tolerance).
Referenced by lamina::solve_with_assumptions.
static bool lamina::is_polynomial_node(const std::shared_ptr< SymbolicNode > &node)
References lamina::get_integer_value, lamina::is_polynomial_node.
Referenced by lamina::collect_denominator_factors, lamina::is_polynomial_node, lamina::Solver::solve_polynomial_system.
static std::pair< SymbolicExpr, SymbolicExpr > lamina::isolate_linear_coeff(const SymbolicExpr &expr, const std::string &var)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_variable, SymbolicExpr::root, lamina::to_ptr.
Referenced by lamina::Solver::solve_linear_system.
Monomial lamina::anonymous_namespace{solver.cpp}::lcm_mono(const Monomial &a, const Monomial &b)
References lamina::anonymous_namespace{solver.cpp}::lcm_mono.
Referenced by lamina::anonymous_namespace{solver.cpp}::chain_criterion, lamina::anonymous_namespace{solver.cpp}::compute_spoly_sugar, lamina::anonymous_namespace{solver.cpp}::lcm_mono, lamina::anonymous_namespace{solver.cpp}::s_poly.
Monomial lamina::anonymous_namespace{solver.cpp}::mul_mono(const Monomial &a, const Monomial &b)
References lamina::anonymous_namespace{solver.cpp}::mul_mono.
Referenced by lamina::anonymous_namespace{solver.cpp}::mul_mono, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::mul_poly_term.
Poly lamina::anonymous_namespace{solver.cpp}::mul_poly(const Poly &a, const Poly &b)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::mul_mono, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
Poly lamina::anonymous_namespace{solver.cpp}::mul_poly_term(const Poly &p, const Term &t)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Term::coeff, lamina::anonymous_namespace{solver.cpp}::Term::mono, lamina::anonymous_namespace{solver.cpp}::mul_mono, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::s_poly.
static std::shared_ptr< SymbolicExpr > lamina::multiply_factors(const std::vector< std::shared_ptr< SymbolicNode > > &factors)
References SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::Solver::solve_polynomial_system.
static std::shared_ptr< SymbolicExpr > lamina::multiply_no_expand(const std::shared_ptr< SymbolicNode > &term, const std::vector< std::shared_ptr< SymbolicNode > > &den_factors)
References lamina::add_number_nodes, lamina::multiply_number_nodes, lamina::num, SymbolicExpr::number.
Referenced by lamina::Solver::solve_polynomial_system.
static std::shared_ptr< NumberNode > lamina::multiply_number_nodes(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
References lamina::Rational.
Referenced by lamina::multiply_no_expand.
Poly lamina::anonymous_namespace{solver.cpp}::reduce(Poly p, const std::vector< Poly > &G)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Term::coeff, lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::anonymous_namespace{solver.cpp}::divides_mono, lamina::anonymous_namespace{solver.cpp}::Poly::is_zero, lamina::anonymous_namespace{solver.cpp}::Poly::LC, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Poly::LT, lamina::anonymous_namespace{solver.cpp}::Term::mono, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::sub_poly, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::Solver::groebner_basis, lamina::Solver::ideal_membership, lamina::Solver::reduced_groebner_basis.
Poly lamina::anonymous_namespace{solver.cpp}::s_poly(const Poly &f, const Poly &g)
References lamina::anonymous_namespace{solver.cpp}::Term::coeff, lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LC, lamina::anonymous_namespace{solver.cpp}::lcm_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Term::mono, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::Rational, lamina::anonymous_namespace{solver.cpp}::sub_poly.
Referenced by lamina::Solver::groebner_basis.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_with_assumptions(const std::shared_ptr< SymbolicExpr > &equation, const std::string &variable, const AssumptionContext *ctx=nullptr)
Solve an equation with assumption-based domain filtering.
Calls the existing SymbolicExpr::solve() to compute all solutions, then applies domain filtering based on the variable's declared domain in the AssumptionContext. Solutions that violate the domain constraint are excluded. Domain filtering rules: Real: exclude solutions containing sqrt(-1) or non-real numeric values PositiveInt: exclude non-integer or <= 0 solutions NonNegative (Natural): exclude solutions evaluating to < 0 equation The equation to solve (equal to zero, or RelationalNode) variable The variable name to solve for ctx Optional assumption context; if nullptr, all solutions returned unfiltered Filtered solutions preserving original order
References lamina::Complex, lamina::anonymous_namespace{solver.cpp}::contains_imaginary, lamina::AssumptionContext::get_domain, lamina::AssumptionContext::has_sign, lamina::Integer, lamina::anonymous_namespace{solver.cpp}::is_integer_value, lamina::Natural, lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::Positive, lamina::PositiveInt, lamina::Rational, lamina::Real, SymbolicExpr::solve, lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value.
Poly lamina::anonymous_namespace{solver.cpp}::sub_poly(const Poly &a, const Poly &b)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::Rational, lamina::anonymous_namespace{solver.cpp}::sub_poly, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::s_poly, lamina::anonymous_namespace{solver.cpp}::sub_poly.
Poly lamina::anonymous_namespace{solver.cpp}::to_poly(const SymbolicExpr &expr, const std::vector< std::string > &vars)
References lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_result, SymbolicExpr::root.
Poly lamina::anonymous_namespace{solver.cpp}::to_poly(const SymbolicExpr &expr, PolyContext &ctx)
References lamina::anonymous_namespace{solver.cpp}::PolyContext::ext_vars, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_result, SymbolicExpr::root.
Referenced by lamina::Solver::elimination_ideal, lamina::Solver::groebner_basis, lamina::Solver::ideal_membership, lamina::Solver::reduced_groebner_basis.
static std::shared_ptr< SymbolicExpr > lamina::to_ptr(const SymbolicExpr &expr)
Referenced by lamina::isolate_linear_coeff, lamina::Solver::solve_polynomial_system.
static bool lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value(const std::shared_ptr< SymbolicExpr > &expr, double &out_value)
Try to extract a numeric double value from a solution expression. Returns true if the expression is a pure numeric value, and sets out_value.
References lamina::num.
Referenced by lamina::solve_with_assumptions.