lamina::AssumptionContext
std::vector<Scope> lamina::AssumptionContext::scope_stack_
Referenced by AssumptionContext, assume, assume_domain, assume_sign, current_properties, current_properties, current_relations, current_relations, depth, get_boundedness, get_bounds, get_domain, get_parity, get_signs, has_domain, has_sign, pop, push.
lamina::AssumptionContext::AssumptionContext()
References scope_stack_.
void lamina::AssumptionContext::assume(const SymbolicExpr &relation)
Store a relational constraint. The expression's root must be a RelationalNode. Throws std::invalid_argument if expression is null/empty or root is not RelationalNode.
References SymbolicExpr::root, scope_stack_.
void lamina::AssumptionContext::assume_domain(const std::string &variable, Domain domain)
Declare domain for a variable in the current scope. Throws std::invalid_argument if variable name is empty.
References scope_stack_.
void lamina::AssumptionContext::assume_sign(const std::string &variable, Sign sign)
Declare sign for a variable in the current scope. Throws std::invalid_argument if variable name is empty.
References scope_stack_.
PropertyStore & lamina::AssumptionContext::current_properties()
Access the current scope's PropertyStore (mutable, for declarations).
References scope_stack_.
Referenced by lamina::InferenceEngine::query_integer, lamina::InferenceEngine::query_negative, lamina::InferenceEngine::query_nonnegative, lamina::InferenceEngine::query_nonpositive, lamina::InferenceEngine::query_nonzero, lamina::InferenceEngine::query_positive, lamina::InferenceEngine::query_real.
const PropertyStore & lamina::AssumptionContext::current_properties() const
Access the current scope's PropertyStore (const).
References scope_stack_.
RelationStore & lamina::AssumptionContext::current_relations()
Access the current scope's RelationStore (mutable).
References scope_stack_.
const RelationStore & lamina::AssumptionContext::current_relations() const
Access the current scope's RelationStore (const).
References scope_stack_.
int lamina::AssumptionContext::depth() const
Return the current nesting depth (number of scopes on the stack).
References scope_stack_.
Boundedness lamina::AssumptionContext::get_boundedness(const std::string &symbol) const
Get boundedness for a symbol (read-through).
References scope_stack_, lamina::Unknown.
std::optional< Interval > lamina::AssumptionContext::get_bounds(const std::string &symbol) const
Get interval bounds for a symbol (read-through).
References scope_stack_.
Referenced by lamina::InferenceEngine::propagate_bounds.
Domain lamina::AssumptionContext::get_domain(const std::string &symbol) const
Get the most specific domain for a symbol (read-through).
References lamina::Complex, scope_stack_.
Referenced by lamina::solve_with_assumptions.
Parity lamina::AssumptionContext::get_parity(const std::string &symbol) const
Get parity for a symbol (read-through).
References scope_stack_, lamina::Unknown.
std::unordered_set< Sign, SignHash > lamina::AssumptionContext::get_signs(const std::string &symbol) const
Get all signs for a symbol (read-through).
References scope_stack_.
bool lamina::AssumptionContext::has_domain(const std::string &symbol, Domain domain) const
Check if a symbol has at least the given domain specificity (read-through).
References lamina::Complex, scope_stack_.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules.
bool lamina::AssumptionContext::has_sign(const std::string &symbol, Sign sign) const
Check if a symbol has a specific sign (read-through all scopes).
References scope_stack_.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules, lamina::solve_with_assumptions.
Tribool lamina::AssumptionContext::is_integer(const SymbolicExpr &expr) const
Query whether the expression is an integer. Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_integer, SymbolicExpr::root.
Tribool lamina::AssumptionContext::is_negative(const SymbolicExpr &expr) const
Query whether the expression is negative (< 0). Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_negative, SymbolicExpr::root.
Referenced by NormalizationVisitor::try_assumption_simplify.
Tribool lamina::AssumptionContext::is_nonnegative(const SymbolicExpr &expr) const
Query whether the expression is non-negative (>= 0). Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_nonnegative, SymbolicExpr::root.
Referenced by NormalizationVisitor::try_assumption_simplify.
Tribool lamina::AssumptionContext::is_nonzero(const SymbolicExpr &expr) const
Query whether the expression is non-zero (!= 0). Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_nonzero, SymbolicExpr::root.
Tribool lamina::AssumptionContext::is_positive(const SymbolicExpr &expr) const
Query whether the expression is positive (> 0). Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_positive, SymbolicExpr::root.
Referenced by NormalizationVisitor::try_assumption_simplify.
Tribool lamina::AssumptionContext::is_real(const SymbolicExpr &expr) const
Query whether the expression is real. Throws std::invalid_argument if expression has null root.
References lamina::QueryInterface::query_real, SymbolicExpr::root.
Referenced by NormalizationVisitor::try_assumption_simplify.
void lamina::AssumptionContext::pop()
Pop the current scope. Throws std::runtime_error if at root scope.
References scope_stack_.
void lamina::AssumptionContext::push()
Push a new scope onto the stack.
References scope_stack_.