Rational
BigInt Rational::denominator
Referenced by Rational, floor_without_sim, get_denominator, hash, is_integer, operator*, operator+, operator-, operator/, operator<, operator==, power, power_self, radicand_self, reciprocal, simplify, sqrt_self, to_double, to_float_string, to_float_string, to_string.
BigInt Rational::numerator
Referenced by Rational, abs, floor_without_sim, get_numerator, hash, is_zero, operator*, operator+, operator-, operator-, operator/, operator<, operator==, power, power_self, radicand_self, reciprocal, simplify, sqrt_self, to_BigInt, to_double, to_float_string, to_float_string, to_string.
std::pair< uint64_t, uint64_t > Rational::detect_repeating_pattern(std::vector< short > &n)
检测小数位序列中的循环节起止位置
n 小数位数字序列 pair(循环节起始索引, 循环节结束索引)
Referenced by Rational.
void Rational::floor_without_sim(const int64_t &n)
References denominator, numerator, BigInt::power.
Referenced by floor, radicand_self, sqrt_self.
void Rational::simplify()
References BigInt::Abs, denominator, BigInt::gcd, BigInt::IsNegative, numerator.
Referenced by Rational, Rational, Rational, lamina::extract_coeff_value< Rational >, floor, from_double.
Rational::Rational()
默认构造，值为 0
Referenced by from_double, operator*, operator+, operator-, operator/, power, radicand_self, reciprocal, sqrt_self.
Rational::Rational(const BigInt &num)
从 BigInt 构造整数有理数
num 分子（分母为 1）
Rational::Rational(const BigInt &num, const BigInt &den)
从分子分母构造有理数
num 分子 den 分母（不可为零）
References simplify.
Rational::Rational(const std::string &num)
从字符串构造有理数，支持小数、科学计数法、循环小数
num 数字字符串
References denominator, detect_repeating_pattern, numerator, BigInt::power, simplify.
Rational::Rational(int num)
从 int 构造整数有理数
num 整数值
Rational::Rational(int num, int den)
从 int 分子分母构造有理数
num 分子 den 分母
References simplify.
Rational Rational::abs() const
取绝对值
|*this|
References BigInt::Abs, numerator.
Referenced by lamina::cauchy_bound.
void Rational::floor(const int64_t &n)
截断到指定精度（就地修改）
n 精度位数
References floor_without_sim, simplify.
Referenced by radicand_self, sqrt_self.
BigInt Rational::get_denominator() const
获取分母
References denominator.
Referenced by NormalizationVisitor::visit, NormalizationVisitor::visit, NormalizationVisitor::visit.
BigInt Rational::get_numerator() const
获取分子
References numerator.
Referenced by NormalizationVisitor::visit, NormalizationVisitor::visit, NormalizationVisitor::visit.
std::size_t Rational::hash() const
计算哈希值
哈希值
References denominator, BigInt::hash, numerator.
bool Rational::is_integer() const
判断是否为整数（分母为 1）
References denominator.
Referenced by lamina::extract_coeff_value< BigInt >, to_BigInt, to_string.
bool Rational::is_zero() const
判断是否为零
References numerator.
Referenced by lamina::FGLMPoly::add_term, lamina::cauchy_bound, operator/, power, reciprocal, to_double, to_float_string.
bool Rational::operator!=(const Rational &other) const
Rational Rational::operator*(const Rational &other) const
有理数乘法
References Rational, denominator, numerator.
Rational Rational::operator+(const Rational &other) const
有理数加法
References Rational, denominator, numerator.
Rational Rational::operator-() const
一元负号运算符
References numerator.
Rational Rational::operator-(const Rational &other) const
有理数减法
References Rational, denominator, numerator.
Rational Rational::operator/(const Rational &other) const
有理数除法
other 除数 商 std::runtime_error 除数为零时抛出
References Rational, denominator, is_zero, numerator.
bool Rational::operator<(const Rational &other) const
References denominator, numerator.
bool Rational::operator<=(const Rational &other) const
bool Rational::operator==(const Rational &other) const
References denominator, numerator.
bool Rational::operator>(const Rational &other) const
bool Rational::operator>=(const Rational &other) const
Rational Rational::power(const BigInt &exponent) const
有理数整数幂
exponent 指数（可为负） this^exponent std::runtime_error 零的负幂或 0^0 时抛出
References Rational, denominator, is_zero, numerator, BigInt::power.
Referenced by power_self, radicand_self.
Rational Rational::power(const Rational &exponent, size_t n)
有理数的有理数幂（返回新值）
exponent 有理数指数 n 精度位数 结果的有理近似
References power_self.
void Rational::power_self(const Rational &exponent, size_t n)
有理数的有理数幂（就地修改）
exponent 有理数指数 n 精度位数
References denominator, numerator, power, radicand_self.
Referenced by power.
Rational Rational::radicand(const BigInt &radical, int64_t n)
计算 n 次方根（返回新值）
radical 根次数 n 精度位数 n 次方根的有理近似
References radicand_self.
void Rational::radicand_self(const BigInt &radical, int64_t n)
牛顿迭代法计算 n 次方根（就地修改）
radical 根次数 n 精度位数
References Rational, denominator, floor, floor_without_sim, numerator, power, BigInt::power.
Referenced by power_self, radicand.
Rational Rational::reciprocal() const
取倒数
1 / *this std::runtime_error 零的倒数时抛出
References Rational, denominator, is_zero, numerator.
Rational Rational::sqrt(int64_t n) const
计算平方根（返回新值）
n 精度位数 平方根的有理近似
References sqrt_self.
void Rational::sqrt_self(int64_t n)
牛顿迭代法计算平方根（就地修改）
n 精度位数
References Rational, denominator, floor, floor_without_sim, numerator.
Referenced by sqrt.
BigInt Rational::to_BigInt() const
转换为 BigInt（仅当为整数时有效）
对应的 BigInt std::runtime_error 非整数时抛出
References is_integer, numerator.
Referenced by lamina::extract_coeff_value< BigInt >.
lmmc_real_t Rational::to_double() const
转换为浮点数
对应的 double 值
References denominator, is_zero, numerator, BigInt::to_double.
Referenced by lamina::find_roots_with_multiplicity.
std::string Rational::to_float_string()
转换为十进制小数字符串（自动检测循环节）
小数字符串，循环部分用括号标记
References BigInt::Abs, denominator, numerator.
std::string Rational::to_float_string(int64_t n) const
转换为指定精度的十进制小数字符串
n 小数位数（正数为小数点后位数，负数为整数部分截断位数） 定精度小数字符串
References denominator, is_zero, numerator, BigInt::power, BigInt::ToString.
std::string Rational::to_string() const
转换为分数字符串（如 "3/4"）
字符串表示
References denominator, is_integer, numerator, BigInt::ToString.
static Rational Rational::from_double(double value)
从 double 构造有理数
value 浮点数值 对应的精确有理数
References Rational, simplify.
Referenced by lamina::convert_to_rational_poly, lamina::extract_coeff_value< Rational >, lamina::solve_numeric, Irrational::to_symbolic, lamina::try_convert_to_rational_poly.