normalization_visitor.hpp
std::shared_ptr< NumberNode > add_numbers(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
两个数值节点相加
a 加数节点 b 加数节点 和的数值节点
Referenced by NormalizationVisitor::expand_product, NormalizationVisitor::visit, NormalizationVisitor::visit.
bool check_negative_arg(const std::shared_ptr< SymbolicNode > &arg, std::shared_ptr< SymbolicNode > &out_positive)
检查节点是否为负数或带负系数，若是则输出其正值部分
arg 待检查的节点 out_positive 输出参数，存放取正后的节点 若节点为负则返回 true
Referenced by NormalizationVisitor::visit.
int get_node_degree_helper(const std::shared_ptr< SymbolicNode > &node)
计算 AST 节点的多项式次数
node 输入节点 节点对应的多项式次数
References get_node_degree_helper.
Referenced by get_node_degree_helper, NodeCompare::operator().
bool get_pi_coeff(const std::shared_ptr< SymbolicNode > &node, Rational &k)
提取节点中 π 的有理系数（如 2π/3 中的 2/3）
node 待检查的节点 k 输出参数，存放 π 的有理系数 若节点为 k*π 形式则返回 true
Referenced by NormalizationVisitor::visit.
std::shared_ptr< NumberNode > multiply_numbers(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
两个数值节点相乘
a 乘数节点 b 乘数节点 积的数值节点
Referenced by NormalizationVisitor::expand_product, NormalizationVisitor::visit.