symbolic_vector_geometry.hpp
std::vector< std::shared_ptr< SymbolicExpr > > lamina::line_plane_intersection(const LineSymbolic &line, const PlaneSymbolic &plane)
计算直线与平面的交点
line 直线 plane 平面 交点坐标向量
References SymbolicExpr::add, lamina::PlaneSymbolic::d, lamina::LineSymbolic::direction, SymbolicExpr::divide, SymbolicExpr::multiply, lamina::PlaneSymbolic::normal, SymbolicExpr::number, lamina::LineSymbolic::point, lamina::vector_dot.
PlaneSymbolic lamina::plane_general(std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b, std::shared_ptr< SymbolicExpr > c, std::shared_ptr< SymbolicExpr > d)
由一般方程系数构造平面 ax + by + cz = d
a x 方向法向量分量 b y 方向法向量分量 c z 方向法向量分量 d 常数项 构造的 PlaneSymbolic 对象
std::shared_ptr< SymbolicExpr > lamina::point_plane_distance(const std::vector< std::shared_ptr< SymbolicExpr > > &point, const PlaneSymbolic &plane)
计算点到平面的距离
point 空间点坐标 plane 平面 距离的符号表达式
References FunctionNode::Abs, SymbolicExpr::add, lamina::PlaneSymbolic::d, SymbolicExpr::divide, SymbolicExpr::multiply, lamina::PlaneSymbolic::normal, SymbolicExpr::number, SymbolicExpr::sqrt, lamina::vector_dot.
std::shared_ptr< SymbolicExpr > lamina::skew_lines_distance(const LineSymbolic &l1, const LineSymbolic &l2)
计算两条异面直线之间的距离
l1 第一条直线 l2 第二条直线 距离的符号表达式
References FunctionNode::Abs, SymbolicExpr::add, lamina::LineSymbolic::direction, SymbolicExpr::divide, SymbolicExpr::multiply, SymbolicExpr::number, lamina::LineSymbolic::point, SymbolicExpr::sqrt, lamina::vector_cross, lamina::vector_dot.
double lamina::vector_angle(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个向量的夹角（弧度）
a 向量 a 的各分量 b 向量 b 的各分量 夹角的数值（弧度）
std::vector< std::shared_ptr< SymbolicExpr > > lamina::vector_cross(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个三维符号向量的叉积
a 向量 a 的各分量 b 向量 b 的各分量 叉积结果向量的各分量
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::skew_lines_distance.
std::shared_ptr< SymbolicExpr > lamina::vector_dot(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个符号向量的点积
a 向量 a 的各分量 b 向量 b 的各分量 点积结果的符号表达式
References SymbolicExpr::multiply.
Referenced by lamina::line_plane_intersection, lamina::point_plane_distance, lamina::skew_lines_distance.