lamina::InequalitySolver
IntervalUnion lamina::InequalitySolver::solve_inequalities(const std::vector< std::pair< std::shared_ptr< SymbolicExpr >, InequalityType > > &inequalities, const std::string &variable)
求解不等式组（取交集）
inequalities 不等式列表，每项为 (表达式, 不等式类型) variable 求解变量名 解集
References lamina::IntervalUnion::entire_line, lamina::IntervalUnion::intersect, lamina::IntervalUnion::is_empty, solve_inequality.
IntervalUnion lamina::InequalitySolver::solve_inequality(const std::shared_ptr< SymbolicExpr > &expr, InequalityType type, const std::string &variable)
求解单个不等式
expr 不等式左端表达式（右端为 0） type 不等式类型 variable 求解变量名 解集
References build_sign_chart, lamina::depends_on_var, lamina::IntervalUnion::empty, lamina::IntervalUnion::entire_line, lamina::find_roots_with_multiplicity, lamina::GreaterEqual, lamina::GreaterThan, lamina::LessEqual, lamina::LessThan, lamina::roots_equal, select_intervals.
Referenced by solve_inequalities, solve_parametric_inequality.
PiecewiseIntervalResult lamina::InequalitySolver::solve_parametric_inequality(const std::shared_ptr< SymbolicExpr > &expr, InequalityType type, const std::string &variable, const std::vector< std::string > &parameters)
求解含参数的不等式，返回分段结果
expr 不等式左端表达式 type 不等式类型 variable 求解变量名 parameters 参数名列表 分段解集
References SymbolicExpr::add, LogicalNode::And, build_parametric_solution, lamina::PiecewiseIntervalResult::cases, lamina::Polynomial< CoeffType >::coeffs, lamina::PiecewiseIntervalResult::Case::condition, lamina::Polynomial< CoeffType >::degree, lamina::depends_on_any_param, lamina::depends_on_var, lamina::IntervalUnion::empty, lamina::IntervalUnion::entire_line, RelationalNode::EQ, lamina::GreaterEqual, RelationalNode::GT, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, lamina::LessEqual, RelationalNode::LT, SymbolicExpr::multiply, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::root_less_than, lamina::PiecewiseIntervalResult::Case::solution, solve_inequality, solve_parametric_inequality, lamina::solve_symbolic_poly, SymbolicExpr::variable.
Referenced by solve_parametric_inequality.
IntervalUnion lamina::InequalitySolver::solve_rational_inequality(const std::shared_ptr< SymbolicExpr > &numerator, const std::shared_ptr< SymbolicExpr > &denominator, InequalityType type, const std::string &variable)
求解有理不等式 numerator/denominator ≷ 0
numerator 分子表达式 denominator 分母表达式 type 不等式类型 variable 求解变量名 解集
References lamina::depends_on_var, lamina::determine_leading_sign, lamina::IntervalUnion::empty, lamina::Interval::entire_line, lamina::IntervalUnion::entire_line, lamina::find_roots_with_multiplicity, lamina::GreaterEqual, lamina::GreaterThan, lamina::LessThan, lamina::Interval::lower, lamina::Endpoint::neg_inf, lamina::Endpoint::open, lamina::Interval::point, lamina::Endpoint::pos_inf, lamina::root_less_than, lamina::roots_equal, lamina::Interval::upper.
IntervalUnion lamina::InequalitySolver::build_parametric_solution(const std::vector< std::shared_ptr< SymbolicExpr > > &symbolic_roots, const std::vector< int > &multiplicities, int leading_sign, InequalityType type)
References SymbolicExpr::add, lamina::IntervalUnion::empty, lamina::IntervalUnion::entire_line, lamina::GreaterEqual, lamina::GreaterThan, lamina::LessThan, lamina::Interval::lower, SymbolicExpr::multiply, lamina::Endpoint::neg_inf, SymbolicExpr::number, lamina::Endpoint::open, lamina::Interval::point, lamina::Endpoint::pos_inf, lamina::Interval::upper.
Referenced by solve_parametric_inequality.
std::vector< SignChartEntry > lamina::InequalitySolver::build_sign_chart(const std::shared_ptr< SymbolicExpr > &poly, const std::string &variable, const std::vector< std::shared_ptr< SymbolicExpr > > &roots, const std::vector< int > &multiplicities)
References lamina::determine_leading_sign, lamina::Interval::entire_line, lamina::Interval::lower, lamina::Endpoint::neg_inf, lamina::Endpoint::open, lamina::Endpoint::pos_inf, lamina::Interval::upper.
Referenced by solve_inequality.
IntervalUnion lamina::InequalitySolver::select_intervals(const std::vector< SignChartEntry > &chart, InequalityType type, const std::vector< std::shared_ptr< SymbolicExpr > > &roots, const std::vector< int > &multiplicities)
References lamina::GreaterEqual, lamina::GreaterThan, lamina::LessThan, lamina::Interval::point, lamina::roots_equal.
Referenced by solve_inequality.