parametric_solver.cpp
static std::shared_ptr< SymbolicExpr > lamina::compute_determinant(const std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &matrix, size_t n)
References SymbolicExpr::add, lamina::compute_determinant, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::compute_determinant, lamina::ParametricSolver::solve_system_piecewise.
static bool lamina::depends_on_parameters(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &parameters)
References lamina::contains.
Referenced by lamina::ParametricSolver::solve_system_piecewise.
static std::shared_ptr< SymbolicExpr > lamina::extract_coefficient(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
Referenced by lamina::extract_constant_term, lamina::ParametricSolver::solve_linear_parametric, lamina::ParametricSolver::solve_system_piecewise.
static std::shared_ptr< SymbolicExpr > lamina::extract_constant_term(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &unknowns)
References lamina::extract_coefficient, SymbolicExpr::number.
Referenced by lamina::ParametricSolver::solve_linear_parametric.