NumberNode
std::variant<BigInt, Rational, lmmc_real_t> NumberNode::value
数值，支持大整数、有理数、浮点数
Referenced by clone, compare_same_type, compute_hash, lamina::QueryInterface::is_nan_number, is_one, is_positive, is_zero, PrintVisitor::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
NumberNode::NumberNode(const BigInt &v)
NumberNode::NumberNode(const Rational &v)
NumberNode::NumberNode(lmmc_real_t v)
NumberNode::NumberNode(std::variant< BigInt, Rational, lmmc_real_t > v)
void NumberNode::accept(SymbolicVisitor &visitor) override
接受 Visitor 访问。
References SymbolicVisitor::visit.
std::shared_ptr< SymbolicNode > NumberNode::clone() const override
深拷贝当前节点及其子树。
References value.
Referenced by ExpandVisitor::visit, LimitVisitor::visit, NormalizationVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, SubstituteVisitor::visit, IntegrationVisitor::visit.
int SymbolicNode::compare(const SymbolicNode &other) const
与另一个节点进行全序比较。
other 待比较的节点 小于返回 -1，等于返回 0，大于返回 1
References SymbolicNode::compare_same_type, SymbolicNode::type_priority.
Referenced by VariableNode::compare_same_type, PowerNode::compare_same_type.
bool SymbolicNode::equals(const SymbolicNode &other) const
判断两个节点是否结构相等。
other 待比较的节点 相等返回 true
References SymbolicNode::compare_same_type, SymbolicNode::hash, SymbolicNode::type_priority.
std::size_t SymbolicNode::hash() const
获取节点哈希值（带缓存）。
哈希值
References SymbolicNode::cached_hash, SymbolicNode::compute_hash, SymbolicNode::hash_computed.
Referenced by MatrixNode::compute_hash, SymbolicNode::equals.
bool NumberNode::is_number() const override
判断节点是否为数值节点。
bool NumberNode::is_one() const override
判断节点数值是否为 1。
References value.
bool NumberNode::is_positive() const override
判断节点是否可证明为严格正数（非数值节点默认返回 false）。
References value.
bool NumberNode::is_zero() const override
判断节点数值是否为 0。
References value.
int NumberNode::type_priority() const override
返回节点类型的排序优先级，用于规范化排序。
int NumberNode::compare_same_type(const SymbolicNode &other) const override
与同类型节点进行比较（由子类实现）。
References value.
std::size_t NumberNode::compute_hash() const override
计算当前节点的哈希值（由子类实现）。
References value.
std::atomic<std::size_t> SymbolicNode::cached_hash
Referenced by SymbolicNode::hash.
std::atomic<bool> SymbolicNode::hash_computed
Referenced by SymbolicNode::hash.