solve_transcendental.cpp
constexpr int lamina::MAX_TRANSCENDENTAL_DEPTH
Referenced by lamina::solve_transcendental_impl.
static void lamina::collect_transcendental_subexprs(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< std::shared_ptr< SymbolicExpr > > &candidates)
References lamina::collect_transcendental_subexprs, FunctionNode::Cos, lamina::depends_on_var, FunctionNode::Exp, FunctionNode::Sin, FunctionNode::Tan.
Referenced by lamina::collect_transcendental_subexprs, lamina::detect_substitution.
static std::optional< ExpBasePattern > lamina::decompose_exp_base_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References lamina::depends_on_var, SymbolicExpr::multiply, SymbolicExpr::number, lamina::try_evaluate_numeric.
Referenced by lamina::solve_transcendental_impl.
static std::optional< LambertWPattern > lamina::decompose_lambert_w_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References lamina::depends_on_var, FunctionNode::Exp, SymbolicExpr::multiply, lamina::nodes_equal, SymbolicExpr::number.
Referenced by lamina::solve_transcendental_impl.
static std::optional< InversePattern > lamina::decompose_trig_exp_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References FunctionNode::Cos, SymbolicFactory::create_multiply, lamina::depends_on_var, SymbolicExpr::divide, FunctionNode::Exp, FunctionNode::Ln, SymbolicExpr::multiply, SymbolicExpr::number, FunctionNode::Sin, FunctionNode::Tan.
Referenced by lamina::solve_transcendental_impl.
static void lamina::deduplicate_candidates(std::vector< std::shared_ptr< SymbolicExpr > > &candidates)
Referenced by lamina::detect_substitution.
std::optional< SubstitutionResult > lamina::detect_substitution(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
检测表达式中可用的换元模式。
expr 待分析的表达式 var 目标变量名 若检测到有效换元则返回 SubstitutionResult，否则返回 nullopt
References lamina::collect_transcendental_subexprs, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_power, lamina::deduplicate_candidates, lamina::depends_on_var, SymbolicExpr::exp, lamina::has_exp_k_var_terms, lamina::rewrite_exp_as_u_power, SymbolicExpr::variable.
Referenced by lamina::solve_transcendental_impl.
static int lamina::extract_exp_multiplier(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References FunctionNode::Exp.
Referenced by lamina::has_exp_k_var_terms, lamina::rewrite_exp_as_u_power.
static bool lamina::has_exp_k_var_terms(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References lamina::extract_exp_multiplier, lamina::has_exp_k_var_terms.
Referenced by lamina::detect_substitution, lamina::has_exp_k_var_terms.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_cos(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, lamina::make_arccos, lamina::make_pi, SymbolicExpr::multiply, SymbolicExpr::number, lamina::try_evaluate_numeric.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_exp(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::ln, lamina::try_evaluate_numeric.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_exp_base(const std::shared_ptr< SymbolicExpr > &base, const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::divide, SymbolicExpr::ln, lamina::try_evaluate_numeric.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_cos(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References lamina::make_arccos, lamina::try_evaluate_numeric.
Referenced by lamina::invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_exp(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References SymbolicExpr::ln, lamina::try_evaluate_numeric.
Referenced by lamina::invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_power(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var, int n)
References SymbolicExpr::divide, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::try_evaluate_numeric.
Referenced by lamina::invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_sin(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References lamina::make_arcsin, lamina::try_evaluate_numeric.
Referenced by lamina::invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_tan(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References lamina::make_arctan.
Referenced by lamina::invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_lambert_w(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::lambertw.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_ln(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::exp.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_sin(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, lamina::make_arcsin, lamina::make_pi, SymbolicExpr::multiply, SymbolicExpr::number, lamina::try_evaluate_numeric.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_substitution_h(const std::shared_ptr< SymbolicExpr > &h_expr, const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References SymbolicExpr::add, FunctionNode::Cos, lamina::depends_on_var, FunctionNode::Exp, lamina::invert_h_cos, lamina::invert_h_exp, lamina::invert_h_power, lamina::invert_h_sin, lamina::invert_h_tan, SymbolicExpr::multiply, SymbolicExpr::number, FunctionNode::Sin, SymbolicExpr::solve, FunctionNode::Tan.
Referenced by lamina::solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_tan(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, lamina::make_arctan, lamina::make_pi, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::solve_transcendental_impl.
static std::shared_ptr< SymbolicExpr > lamina::make_arccos(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcCos.
Referenced by lamina::invert_cos, lamina::invert_h_cos.
static std::shared_ptr< SymbolicExpr > lamina::make_arcsin(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcSin.
Referenced by lamina::invert_h_sin, lamina::invert_sin.
static std::shared_ptr< SymbolicExpr > lamina::make_arctan(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcTan.
static std::shared_ptr< SymbolicExpr > lamina::make_pi()
References SymbolicExpr::number.
Referenced by lamina::invert_cos, lamina::invert_sin, lamina::invert_tan.
static bool lamina::nodes_equal(const std::shared_ptr< SymbolicNode > &a, const std::shared_ptr< SymbolicNode > &b)
Referenced by lamina::decompose_lambert_w_pattern.
static std::shared_ptr< SymbolicNode > lamina::rewrite_exp_as_u_power(const std::shared_ptr< SymbolicNode > &node, const std::string &var, const std::string &u_var)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_power, lamina::extract_exp_multiplier, lamina::rewrite_exp_as_u_power.
Referenced by lamina::detect_substitution, lamina::rewrite_exp_as_u_power.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_inner_equation(const std::shared_ptr< SymbolicExpr > &inner, const std::shared_ptr< SymbolicExpr > &value, const std::string &var, int depth)
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::solve, lamina::solve_transcendental_impl.
Referenced by lamina::solve_transcendental_impl.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_transcendental(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
求解超越方程（三角、指数、对数类型）。
expr 待求解的表达式（视为等于零） var 求解变量名 所有根的符号表达式列表
References lamina::solve_transcendental_impl.
Referenced by lamina::solve_dispatch.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_transcendental_impl(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, int depth)
References FunctionNode::Cos, lamina::decompose_exp_base_pattern, lamina::decompose_lambert_w_pattern, lamina::decompose_trig_exp_pattern, lamina::detect_substitution, FunctionNode::Exp, lamina::invert_cos, lamina::invert_exp, lamina::invert_exp_base, lamina::invert_lambert_w, lamina::invert_ln, lamina::invert_sin, lamina::invert_substitution_h, lamina::invert_tan, FunctionNode::Ln, lamina::SolveOptions::max_roots, lamina::MAX_TRANSCENDENTAL_DEPTH, FunctionNode::Sin, SymbolicExpr::solve, lamina::solve_inner_equation, FunctionNode::Tan.
Referenced by lamina::solve_inner_equation, lamina::solve_transcendental.
static bool lamina::try_evaluate_numeric(const std::shared_ptr< SymbolicExpr > &expr, lmmc_real_t &out)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands.
Referenced by lamina::decompose_exp_base_pattern, lamina::invert_cos, lamina::invert_exp, lamina::invert_exp_base, lamina::invert_h_cos, lamina::invert_h_exp, lamina::invert_h_power, lamina::invert_h_sin, lamina::invert_sin.