lamina::anonymous_namespace{solver.cpp}
using lamina::anonymous_namespace{solver.cpp}::Monomial = typedef std::vector<int>
using lamina::anonymous_namespace{solver.cpp}::PolyTerms = typedef std::map<Monomial, Rational, MonomialLess>
Poly lamina::anonymous_namespace{solver.cpp}::add_poly(const Poly &a, const Poly &b)
References add_poly, lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by add_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
bool lamina::anonymous_namespace{solver.cpp}::chain_criterion(const std::vector< Poly > &G, size_t i, size_t j, const std::set< std::pair< size_t, size_t > > &processed_pairs)
References divides_mono, lcm_mono.
Referenced by lamina::Solver::groebner_basis.
int lamina::anonymous_namespace{solver.cpp}::compute_spoly_sugar(const Poly &f, const Poly &g)
References lcm_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Poly::sugar.
Referenced by lamina::Solver::groebner_basis.
static bool lamina::anonymous_namespace{solver.cpp}::contains_imaginary(const std::shared_ptr< SymbolicExpr > &expr)
Check if a solution expression contains imaginary components (sqrt of negative).
References lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::found.
Referenced by lamina::solve_with_assumptions.
bool lamina::anonymous_namespace{solver.cpp}::coprime_leading_monomials(const Poly &f, const Poly &g)
References lamina::anonymous_namespace{solver.cpp}::Poly::is_zero, lamina::anonymous_namespace{solver.cpp}::Poly::LM.
Referenced by lamina::Solver::groebner_basis.
Monomial lamina::anonymous_namespace{solver.cpp}::div_mono(const Monomial &num, const Monomial &den)
References div_mono, lamina::num.
Referenced by div_mono, reduce, s_poly.
bool lamina::anonymous_namespace{solver.cpp}::divides_mono(const Monomial &a, const Monomial &b)
References divides_mono.
Referenced by chain_criterion, divides_mono, reduce, lamina::Solver::reduced_groebner_basis.
SymbolicExpr lamina::anonymous_namespace{solver.cpp}::from_poly(const Poly &p, const std::vector< std::string > &vars)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_power, SymbolicFactory::create_variable, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
SymbolicExpr lamina::anonymous_namespace{solver.cpp}::from_poly_ext(const Poly &p, const PolyContext &ctx, const std::vector< std::string > &original_vars)
References lamina::anonymous_namespace{solver.cpp}::PolyContext::aux_to_node, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_power, SymbolicFactory::create_variable, lamina::anonymous_namespace{solver.cpp}::PolyContext::ext_vars, lamina::anonymous_namespace{solver.cpp}::PolyContext::num_original_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::Solver::groebner_basis, lamina::Solver::reduced_groebner_basis.
static bool lamina::anonymous_namespace{solver.cpp}::is_integer_value(double v)
Check if a numeric value is an integer (within tolerance).
Referenced by lamina::solve_with_assumptions.
Monomial lamina::anonymous_namespace{solver.cpp}::lcm_mono(const Monomial &a, const Monomial &b)
References lcm_mono.
Referenced by chain_criterion, compute_spoly_sugar, lcm_mono, s_poly.
Monomial lamina::anonymous_namespace{solver.cpp}::mul_mono(const Monomial &a, const Monomial &b)
References mul_mono.
Referenced by mul_mono, mul_poly, mul_poly_term.
Poly lamina::anonymous_namespace{solver.cpp}::mul_poly(const Poly &a, const Poly &b)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, mul_mono, mul_poly, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by mul_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
Poly lamina::anonymous_namespace{solver.cpp}::mul_poly_term(const Poly &p, const Term &t)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Term::coeff, lamina::anonymous_namespace{solver.cpp}::Term::mono, mul_mono, mul_poly_term, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by mul_poly_term, reduce, s_poly.
Poly lamina::anonymous_namespace{solver.cpp}::reduce(Poly p, const std::vector< Poly > &G)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::anonymous_namespace{solver.cpp}::Term::coeff, div_mono, divides_mono, lamina::anonymous_namespace{solver.cpp}::Poly::is_zero, lamina::anonymous_namespace{solver.cpp}::Poly::LC, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Poly::LT, lamina::anonymous_namespace{solver.cpp}::Term::mono, mul_poly_term, lamina::anonymous_namespace{solver.cpp}::Poly::num_vars, sub_poly, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by lamina::Solver::groebner_basis, lamina::Solver::ideal_membership, lamina::Solver::reduced_groebner_basis.
Poly lamina::anonymous_namespace{solver.cpp}::s_poly(const Poly &f, const Poly &g)
References lamina::anonymous_namespace{solver.cpp}::Term::coeff, div_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LC, lcm_mono, lamina::anonymous_namespace{solver.cpp}::Poly::LM, lamina::anonymous_namespace{solver.cpp}::Term::mono, mul_poly_term, lamina::Rational, sub_poly.
Referenced by lamina::Solver::groebner_basis.
Poly lamina::anonymous_namespace{solver.cpp}::sub_poly(const Poly &a, const Poly &b)
References lamina::anonymous_namespace{solver.cpp}::Poly::add_term, lamina::Rational, sub_poly, lamina::anonymous_namespace{solver.cpp}::Poly::terms.
Referenced by reduce, s_poly, sub_poly.
Poly lamina::anonymous_namespace{solver.cpp}::to_poly(const SymbolicExpr &expr, const std::vector< std::string > &vars)
References lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_result, SymbolicExpr::root.
Poly lamina::anonymous_namespace{solver.cpp}::to_poly(const SymbolicExpr &expr, PolyContext &ctx)
References lamina::anonymous_namespace{solver.cpp}::PolyContext::ext_vars, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::get_result, SymbolicExpr::root.
Referenced by lamina::Solver::elimination_ideal, lamina::Solver::groebner_basis, lamina::Solver::ideal_membership, lamina::Solver::reduced_groebner_basis.
static bool lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value(const std::shared_ptr< SymbolicExpr > &expr, double &out_value)
Try to extract a numeric double value from a solution expression. Returns true if the expression is a pure numeric value, and sets out_value.
References lamina::num.
Referenced by lamina::solve_with_assumptions.