lamina::MonomialOrder
MonomialOrderType lamina::MonomialOrder::type_
Referenced by operator(), type.
lamina::MonomialOrder::MonomialOrder(MonomialOrderType type)
构造指定类型的单项式序
type 序的类型
bool lamina::MonomialOrder::operator()(const Monomial &a, const Monomial &b) const
比较两个单项式的大小
a 左操作数 b 右操作数 a > b 时返回 true（按当前序）
References compare_deglex, compare_grevlex, compare_lex, lamina::DegLex, lamina::DegRevLex, lamina::GrevLex, lamina::Lex, type_.
MonomialOrderType lamina::MonomialOrder::type() const
获取序的类型
References type_.
static MonomialOrder lamina::MonomialOrder::deglex()
创建分次字典序
References lamina::DegLex.
static MonomialOrder lamina::MonomialOrder::degrevlex()
创建分次逆字典序（DegRevLex）
References lamina::DegRevLex.
static MonomialOrder lamina::MonomialOrder::grevlex()
创建分次逆字典序
References lamina::GrevLex.
Referenced by lamina::grevlex_to_lex.
static MonomialOrder lamina::MonomialOrder::lex()
创建字典序
References lamina::Lex.
Referenced by lamina::grevlex_to_lex.
static bool lamina::MonomialOrder::compare_deglex(const Monomial &a, const Monomial &b)
References compare_lex, lamina::total_degree.
Referenced by operator().
static bool lamina::MonomialOrder::compare_grevlex(const Monomial &a, const Monomial &b)
References lamina::total_degree.
Referenced by operator().
static bool lamina::MonomialOrder::compare_lex(const Monomial &a, const Monomial &b)
Referenced by compare_deglex, operator().