lamina::InferenceEngine
Tribool lamina::InferenceEngine::query_positive(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_sign, infer_function_property, infer_multiply_sign, infer_power_property, lamina::Negative, lamina::NonPositive, lamina::num, lamina::Positive, lamina::Rational, SymbolicExpr::root, lamina::True, lamina::Unknown, lamina::Zero.
Referenced by infer_add_sign, infer_function_domain, infer_function_property, infer_multiply_sign, infer_power_property, lamina::QueryInterface::query_positive, query_sign_of.
Tribool lamina::InferenceEngine::query_negative(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_sign, infer_function_property, infer_multiply_sign, infer_power_property, lamina::Negative, lamina::NonNegative, lamina::num, lamina::Positive, lamina::Rational, SymbolicExpr::root, lamina::True, lamina::Unknown, lamina::Zero.
Referenced by infer_add_sign, infer_multiply_sign, lamina::QueryInterface::query_negative, query_sign_of.
Tribool lamina::InferenceEngine::query_nonnegative(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_sign, infer_function_property, infer_multiply_sign, infer_power_property, lamina::Negative, lamina::NonNegative, lamina::num, lamina::Rational, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by infer_add_sign, infer_function_domain, infer_function_property, infer_multiply_sign, infer_power_property, lamina::QueryInterface::query_nonnegative, query_sign_of.
Tribool lamina::InferenceEngine::query_nonpositive(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_sign, infer_function_property, infer_multiply_sign, infer_power_property, lamina::NonPositive, lamina::num, lamina::Positive, lamina::Rational, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by infer_add_sign, infer_multiply_sign, query_sign_of.
Tribool lamina::InferenceEngine::query_real(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, infer_add_domain, infer_function_domain, infer_multiply_domain, infer_power_domain, lamina::num, lamina::Real, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by infer_add_domain, infer_function_domain, infer_function_property, infer_multiply_domain, infer_power_domain, infer_power_property, query_domain_of, lamina::QueryInterface::query_real.
Tribool lamina::InferenceEngine::query_integer(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_domain, infer_function_domain, infer_multiply_domain, infer_power_domain, lamina::Integer, lamina::num, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by infer_add_domain, infer_function_domain, infer_multiply_domain, infer_power_domain, query_domain_of, lamina::QueryInterface::query_integer.
Tribool lamina::InferenceEngine::query_nonzero(const SymbolicExpr &expr) const
References ctx_, lamina::AssumptionContext::current_properties, lamina::False, infer_add_sign, infer_function_property, infer_multiply_sign, infer_power_property, lamina::Negative, lamina::NonZero, lamina::num, lamina::Positive, SymbolicExpr::root, lamina::True, lamina::Unknown, lamina::Zero.
Referenced by infer_multiply_sign, infer_power_property, lamina::QueryInterface::query_nonzero, query_sign_of.
Tribool lamina::InferenceEngine::infer_add_sign(const AddNode &node, Sign target) const
References lamina::False, lamina::Negative, lamina::NonNegative, lamina::NonPositive, AddNode::operands, lamina::Positive, query_negative, query_nonnegative, query_nonpositive, query_positive, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive.
Tribool lamina::InferenceEngine::infer_multiply_sign(const MultiplyNode &node, Sign target) const
References lamina::False, lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, MultiplyNode::operands, lamina::Positive, query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive, SymbolicExpr::root, lamina::True, lamina::Unknown, lamina::Zero.
Referenced by query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive.
Tribool lamina::InferenceEngine::infer_power_property(const PowerNode &node, Sign target) const
References PowerNode::base, PowerNode::exponent, lamina::False, lamina::is_even_integer_number, lamina::is_integer_number, lamina::is_positive_integer_number, lamina::is_zero_number, lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, query_nonnegative, query_nonzero, query_positive, query_real, SymbolicExpr::root, lamina::True, lamina::Unknown, lamina::Zero.
Referenced by query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive.
Tribool lamina::InferenceEngine::infer_function_property(const FunctionNode &node, Sign target) const
References FunctionNode::Abs, FunctionNode::ArcCos, FunctionNode::ArcSin, FunctionNode::ArcTan, FunctionNode::arguments, FunctionNode::Cos, FunctionNode::Exp, lamina::False, FunctionNode::Ln, lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, query_nonnegative, query_positive, query_real, SymbolicExpr::root, FunctionNode::Sin, FunctionNode::Sqrt, FunctionNode::Tan, lamina::True, FunctionNode::type, lamina::Unknown, lamina::Zero.
Referenced by query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive.
Tribool lamina::InferenceEngine::infer_add_domain(const AddNode &node, Domain target) const
References lamina::Integer, AddNode::operands, query_integer, query_real, lamina::Real, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by query_integer, query_real.
Tribool lamina::InferenceEngine::infer_multiply_domain(const MultiplyNode &node, Domain target) const
References lamina::Integer, MultiplyNode::operands, query_integer, query_real, lamina::Real, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by query_integer, query_real.
Tribool lamina::InferenceEngine::infer_power_domain(const PowerNode &node, Domain target) const
References PowerNode::base, PowerNode::exponent, lamina::Integer, lamina::is_integer_number, lamina::is_positive_integer_number, lamina::is_zero_number, query_integer, query_real, lamina::Real, SymbolicExpr::root, lamina::True, lamina::Unknown.
Referenced by query_integer, query_real.
Tribool lamina::InferenceEngine::infer_function_domain(const FunctionNode &node, Domain target) const
References FunctionNode::Abs, FunctionNode::ArcCos, FunctionNode::ArcSin, FunctionNode::ArcTan, FunctionNode::arguments, FunctionNode::Cos, FunctionNode::Exp, lamina::Integer, FunctionNode::Ln, query_integer, query_nonnegative, query_positive, query_real, lamina::Real, SymbolicExpr::root, FunctionNode::Sin, FunctionNode::Sqrt, FunctionNode::Tan, lamina::True, FunctionNode::type, lamina::Unknown.
Referenced by query_integer, query_real.
Tribool lamina::InferenceEngine::query_sign_of(const SymbolicExpr &expr, Sign sign) const
References lamina::False, lamina::Negative, lamina::NonNegative, lamina::NonPositive, lamina::NonZero, lamina::Positive, query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive, lamina::True, lamina::Unknown, lamina::Zero.
Tribool lamina::InferenceEngine::query_domain_of(const SymbolicExpr &expr, Domain domain) const
References lamina::Integer, query_integer, query_real, lamina::Real, lamina::Unknown.
constexpr int lamina::InferenceEngine::MAX_MONOTONICITY_DEPTH
Referenced by apply_monotonicity_rules.
const AssumptionContext& lamina::InferenceEngine::ctx_
Referenced by apply_monotonicity_rules, propagate_bounds, query_integer, query_negative, query_nonnegative, query_nonpositive, query_nonzero, query_positive, query_real.
lamina::InferenceEngine::InferenceEngine(const AssumptionContext &ctx)
Construct an InferenceEngine bound to an AssumptionContext.
ctx The AssumptionContext used to query sub-expression properties
void lamina::InferenceEngine::apply_monotonicity_rules(const Relation &rel, RelationStore &store, PropertyStore &prop_store, int depth=0)
Apply monotonicity deduction rules when a new relation is added.
For relations like x > y where both operands have appropriate domain assumptions, deduces new relations (e.g., ln(x) > ln(y) when both are Positive). rel The newly added relation store The RelationStore to add deduced relations to prop_store The PropertyStore for checking domain assumptions depth Current recursion depth (stops at MAX_MONOTONICITY_DEPTH)
References lamina::RelationStore::add_relation, apply_monotonicity_rules, lamina::collect_power_exponents, ctx_, FunctionNode::Exp, RelationalNode::GT, lamina::AssumptionContext::has_domain, lamina::RelationStore::has_relation, lamina::AssumptionContext::has_sign, lamina::Relation::lhs, FunctionNode::Ln, MAX_MONOTONICITY_DEPTH, lamina::NonNegative, lamina::Relation::op, lamina::Positive, lamina::Real, lamina::Relation::rhs, SymbolicExpr::root, FunctionNode::Sqrt.
Referenced by apply_monotonicity_rules.
std::optional< Interval > lamina::InferenceEngine::propagate_bounds(const SymbolicExpr &expr) const
Propagate interval bounds through an expression tree.
expr The expression to propagate bounds for The propagated interval, or std::nullopt if bounds cannot be determined
References FunctionNode::Cos, ctx_, lamina::endpoint_to_double, lamina::AssumptionContext::get_bounds, lamina::is_exponent_neg_one, lamina::is_exponent_two, lamina::make_interval, lamina::num, propagate_bounds, SymbolicExpr::root, FunctionNode::Sin.
Referenced by propagate_bounds.