lamina::Integrator
CycleState lamina::Integrator::cycle_state_
Referenced by check_cycle, integrate, integrate_recursive.
int lamina::Integrator::max_depth_
Referenced by integrate_recursive.
std::vector<std::unique_ptr<IntegrationStrategy> > lamina::Integrator::strategies_
Referenced by Integrator, add_strategy, dispatch_strategies.
IntegrationTable lamina::Integrator::table_
lamina::Integrator::Integrator()
References strategies_.
void lamina::Integrator::add_strategy(std::unique_ptr< IntegrationStrategy > strategy, int position=-1)
添加积分策略
strategy 策略对象 position 插入位置，-1 表示追加到末尾
References strategies_.
SymbolicExpr lamina::Integrator::integrate(const SymbolicExpr &expr, const std::string &var_name)
计算不定积分
expr 被积表达式 var_name 积分变量名 积分结果表达式
References apply_linearity, cycle_state_, lamina::Integrator::CycleState::history, integrate_recursive.
Referenced by apply_linearity, lamina::MultipleIntegralEngine::evaluate, SymbolicExpr::integrate, integrate_def.
SymbolicExpr lamina::Integrator::integrate_def(const SymbolicExpr &expr, const std::string &var_name, const SymbolicExpr &lower, const SymbolicExpr &upper)
计算定积分
expr 被积表达式 var_name 积分变量名 lower 积分下限 upper 积分上限 定积分结果表达式
References SymbolicExpr::add, FunctionNode::Calculus_Integral, integrate, integrate_def, lamina::make_expr_ptr, SymbolicExpr::number, SymbolicExpr::root, SymbolicExpr::simplify, SymbolicExpr::substitute, lamina::sym_sub, SymbolicExpr::to_numeric, SymbolicExpr::variable.
Referenced by lamina::MultipleIntegralEngine::evaluate, integrate_def.
std::shared_ptr< SymbolicExpr > lamina::Integrator::integrate_recursive(const SymbolicExpr &expr, const std::string &var, int depth=0)
递归积分入口
expr 被积表达式 var 积分变量名 depth 当前递归深度 积分结果，失败返回 nullptr
References check_cycle, cycle_state_, dispatch_strategies, lamina::Integrator::CycleState::history, SymbolicExpr::is_number, lamina::make_expr_ptr, make_integral_node, max_depth_, SymbolicExpr::multiply, resolve_cycle, lamina::valid_dependency, SymbolicExpr::variable.
Referenced by integrate, lamina::IBPStrategy::try_integrate.
int lamina::Integrator::max_depth() const
获取最大递归深度
Referenced by lamina::TrigCombinationStrategy::integrate_even_case, lamina::TrigCombinationStrategy::integrate_odd_case, lamina::TrigCombinationStrategy::integrate_sec_power, lamina::TrigCombinationStrategy::integrate_sin_m_cos_n, lamina::TrigCombinationStrategy::integrate_tan_power.
void lamina::Integrator::set_max_depth(int d)
设置最大递归深度
d 深度值
IntegrationTable & lamina::Integrator::table()
获取积分表（可修改）
Referenced by lamina::TableLookupStrategy::try_integrate.
const IntegrationTable & lamina::Integrator::table() const
获取积分表（只读）
bool lamina::Integrator::depends_on(const SymbolicExpr &expr, const std::string &var)
判断表达式是否依赖指定变量
expr 表达式 var 变量名 依赖返回 true
References lamina::depends_on_var, SymbolicExpr::root.
Referenced by lamina::MultipleIntegralEngine::evaluate, lamina::RationalDecompositionStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > lamina::Integrator::apply_linearity(const SymbolicExpr &expr, const std::string &var)
References integrate, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::simplify, lamina::valid_dependency.
Referenced by integrate.
std::shared_ptr< SymbolicExpr > lamina::Integrator::check_cycle(const SymbolicExpr &expr, const std::string &var)
References cycle_state_, SymbolicExpr::divide, lamina::Integrator::CycleState::history, lamina::make_expr_ptr, SymbolicExpr::multiply, lamina::valid_dependency, SymbolicExpr::variable.
Referenced by integrate_recursive.
std::shared_ptr< SymbolicExpr > lamina::Integrator::dispatch_strategies(const SymbolicExpr &expr, const std::string &var, int depth)
References err_stream, strategies_.
Referenced by integrate_recursive.
void lamina::Integrator::resolve_cycle(std::shared_ptr< SymbolicExpr > &result, size_t cycle_idx)
References SymbolicExpr::divide, SymbolicExpr::number, lamina::sym_sub, lamina::valid_dependency.
Referenced by integrate_recursive.
std::shared_ptr< SymbolicExpr > lamina::Integrator::make_integral_node(const SymbolicExpr &expr, const std::string &var)
References FunctionNode::Calculus_Integral, SymbolicExpr::root, SymbolicExpr::variable.
Referenced by integrate_recursive.