lamina::Interval
Endpoint lamina::Interval::lower
下端点
Referenced by lamina::InequalitySolver::build_parametric_solution, lamina::InequalitySolver::build_sign_chart, lamina::can_merge, lamina::IntervalUnion::complement, contains, lamina::IntervalUnion::intersect, is_empty, is_entire_line, lamina::make_interval, lamina::parse_single_interval, lamina::InequalitySolver::solve_rational_inequality, lamina::IntervalUnion::to_string.
Endpoint lamina::Interval::upper
上端点
Referenced by lamina::InequalitySolver::build_parametric_solution, lamina::InequalitySolver::build_sign_chart, lamina::can_merge, lamina::IntervalUnion::complement, contains, lamina::IntervalUnion::intersect, is_empty, is_entire_line, lamina::make_interval, lamina::IntervalUnion::normalize, lamina::parse_single_interval, lamina::InequalitySolver::solve_rational_inequality, lamina::IntervalUnion::to_string.
bool lamina::Interval::contains(double value) const
判断数值是否在区间内
value 待判断的数值 包含返回 true
References lamina::endpoint_is_numeric, lamina::endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lower, upper.
bool lamina::Interval::is_empty() const
判断区间是否为空
空区间返回 true
References lamina::endpoint_is_numeric, lamina::endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lower, upper.
bool lamina::Interval::is_entire_line() const
判断区间是否为整条实数轴
是整条实数轴返回 true
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lower, upper.
Interval lamina::Interval::empty()
构造空区间
空区间
References SymbolicExpr::number, lamina::Endpoint::open.
Interval lamina::Interval::entire_line()
构造整条实数轴 (-∞, +∞)
全实数轴区间
References lamina::Endpoint::neg_inf, lamina::Endpoint::pos_inf.
Referenced by lamina::InequalitySolver::build_sign_chart, lamina::IntervalUnion::entire_line, lamina::InequalitySolver::solve_rational_inequality.
Interval lamina::Interval::point(std::shared_ptr< SymbolicExpr > val)
构造单点区间 [val, val]
val 点值 单点区间
References lamina::Endpoint::closed.
Referenced by lamina::InequalitySolver::build_parametric_solution, lamina::InequalitySolver::select_intervals, lamina::InequalitySolver::solve_rational_inequality.