lamina::SymbolicPolyCoeff
std::shared_ptr<SymbolicExpr> lamina::SymbolicPolyCoeff::val
内部符号表达式
Referenced by operator*, operator+, operator-, operator-, operator/, operator==, ToString.
lamina::SymbolicPolyCoeff::SymbolicPolyCoeff()
默认构造，值为 0
Referenced by operator*, operator+, operator-, operator-, operator/.
lamina::SymbolicPolyCoeff::SymbolicPolyCoeff(int v)
从整数构造
v 整数值
lamina::SymbolicPolyCoeff::SymbolicPolyCoeff(std::shared_ptr< SymbolicExpr > v)
从符号表达式构造
v 符号表达式
bool lamina::SymbolicPolyCoeff::operator!=(const SymbolicPolyCoeff &other) const
SymbolicPolyCoeff lamina::SymbolicPolyCoeff::operator*(const SymbolicPolyCoeff &other) const
乘法
References SymbolicPolyCoeff, SymbolicExpr::multiply, val.
SymbolicPolyCoeff lamina::SymbolicPolyCoeff::operator+(const SymbolicPolyCoeff &other) const
加法
References SymbolicPolyCoeff, SymbolicExpr::add, val.
SymbolicPolyCoeff lamina::SymbolicPolyCoeff::operator-() const
取负
References SymbolicPolyCoeff, SymbolicExpr::multiply, SymbolicExpr::number, val.
SymbolicPolyCoeff lamina::SymbolicPolyCoeff::operator-(const SymbolicPolyCoeff &other) const
减法
References SymbolicPolyCoeff, SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, val.
SymbolicPolyCoeff lamina::SymbolicPolyCoeff::operator/(const SymbolicPolyCoeff &other) const
除法
References SymbolicPolyCoeff, SymbolicExpr::divide, val.
bool lamina::SymbolicPolyCoeff::operator==(const SymbolicPolyCoeff &other) const
判等（通过化简差为零判断）
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, val.
std::string lamina::SymbolicPolyCoeff::ToString() const
转换为字符串
符号表达式的字符串表示
References val.
SymbolicPolyCoeff abs(const SymbolicPolyCoeff &s)
取绝对值（符号系数不做实际操作）