lamina::anonymous_namespace{solver.cpp}::Poly
size_t lamina::anonymous_namespace{solver.cpp}::Poly::num_vars
Referenced by lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
int lamina::anonymous_namespace{solver.cpp}::Poly::sugar
Referenced by lamina::anonymous_namespace{solver.cpp}::compute_spoly_sugar.
PolyTerms lamina::anonymous_namespace{solver.cpp}::Poly::terms
Referenced by lamina::anonymous_namespace{solver.cpp}::add_poly, lamina::anonymous_namespace{solver.cpp}::from_poly, lamina::anonymous_namespace{solver.cpp}::from_poly_ext, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::sub_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
lamina::anonymous_namespace{solver.cpp}::Poly::Poly()
lamina::anonymous_namespace{solver.cpp}::Poly::Poly(size_t n)
void lamina::anonymous_namespace{solver.cpp}::Poly::add_term(const Monomial &m, const Rational &c)
Referenced by lamina::anonymous_namespace{solver.cpp}::add_poly, lamina::anonymous_namespace{solver.cpp}::mul_poly, lamina::anonymous_namespace{solver.cpp}::mul_poly_term, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::sub_poly, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit.
bool lamina::anonymous_namespace{solver.cpp}::Poly::is_zero() const
Referenced by lamina::anonymous_namespace{solver.cpp}::coprime_leading_monomials, lamina::anonymous_namespace{solver.cpp}::reduce.
Rational lamina::anonymous_namespace{solver.cpp}::Poly::LC() const
Referenced by lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::s_poly.
Monomial lamina::anonymous_namespace{solver.cpp}::Poly::LM() const
Referenced by lamina::anonymous_namespace{solver.cpp}::compute_spoly_sugar, lamina::anonymous_namespace{solver.cpp}::coprime_leading_monomials, lamina::anonymous_namespace{solver.cpp}::reduce, lamina::anonymous_namespace{solver.cpp}::s_poly.
Term lamina::anonymous_namespace{solver.cpp}::Poly::LT() const
Referenced by lamina::anonymous_namespace{solver.cpp}::reduce.