lamina::ModInt
int64_t lamina::ModInt::mod_
Referenced by inverse, modulus, operator*, operator+, operator-, operator-, operator<, operator==, pow.
int64_t lamina::ModInt::val_
Referenced by ModInt, inverse, is_zero, operator*, operator+, operator-, operator-, operator<, operator==, pow, value.
lamina::ModInt::ModInt()
默认构造，值为 0，模为 2
Referenced by inverse, operator*, operator+, operator-, operator-, pow.
lamina::ModInt::ModInt(int64_t v, int64_t p)
构造模整数
v 整数值（自动取模归约到 [0, p)） p 模数
References val_.
ModInt lamina::ModInt::inverse() const
求模逆元
当前值在模 mod_ 下的乘法逆元 std::domain_error 若值为 0 或不可逆
References ModInt, lamina::extended_gcd, mod_, val_.
Referenced by operator/, pow.
bool lamina::ModInt::is_zero() const
判断是否为零
References val_.
int64_t lamina::ModInt::modulus() const
获取模数
References mod_.
Referenced by pow.
bool lamina::ModInt::operator!=(const ModInt &other) const
判不等
ModInt lamina::ModInt::operator*(const ModInt &other) const
模乘法
References ModInt, mod_, val_.
ModInt lamina::ModInt::operator+(const ModInt &other) const
模加法
References ModInt, mod_, val_.
ModInt lamina::ModInt::operator-() const
取负
References ModInt, mod_, val_.
ModInt lamina::ModInt::operator-(const ModInt &other) const
模减法
References ModInt, mod_, val_.
ModInt lamina::ModInt::operator/(const ModInt &other) const
模除法（乘以逆元）
References inverse.
bool lamina::ModInt::operator<(const ModInt &other) const
小于比较（先比模数，再比值）
References mod_, val_.
bool lamina::ModInt::operator==(const ModInt &other) const
判等
References mod_, val_.
bool lamina::ModInt::operator>(const ModInt &other) const
大于比较
int64_t lamina::ModInt::value() const
获取当前值
References val_.
static ModInt lamina::ModInt::pow(ModInt base, int64_t exp)
模幂运算
base 底数 exp 指数（可为负，负指数先求逆） base^exp mod p
References ModInt, inverse, mod_, modulus, val_.