PowerNode
std::shared_ptr<SymbolicNode> PowerNode::base
底数
Referenced by clone, compare_same_type, compute_hash, lamina::convert_to_rational_poly, lamina::depends_on_var, lamina::expr_has_free_variables, lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property, lamina::is_purely_numeric, SymbolicExpr::poly_gcd, lamina::try_evaluate_numeric, DifferentiationVisitor::visit, ExpandVisitor::visit, LimitVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::visit, VariablesVisitor::visit, SubstituteVisitor::visit, IntegrationVisitor::visit.
std::shared_ptr<SymbolicNode> PowerNode::exponent
指数
Referenced by clone, compare_same_type, compute_hash, lamina::convert_to_rational_poly, lamina::depends_on_var, lamina::expr_has_free_variables, lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property, lamina::is_purely_numeric, SymbolicExpr::poly_gcd, lamina::try_evaluate_numeric, DifferentiationVisitor::visit, ExpandVisitor::visit, LimitVisitor::visit, NormalizationVisitor::visit, PrintVisitor::visit, lamina::ReplacementVisitor::visit, lamina::RewriteVisitor::visit, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::visit, VariablesVisitor::visit, SubstituteVisitor::visit, IntegrationVisitor::visit.
PowerNode::PowerNode(std::shared_ptr< SymbolicNode > b, std::shared_ptr< SymbolicNode > e)
void PowerNode::accept(SymbolicVisitor &visitor) override
接受 Visitor 访问。
References SymbolicVisitor::visit.
std::shared_ptr< SymbolicNode > PowerNode::clone() const override
深拷贝当前节点及其子树。
References base, exponent.
Referenced by IntegrationVisitor::visit.
int SymbolicNode::compare(const SymbolicNode &other) const
与另一个节点进行全序比较。
other 待比较的节点 小于返回 -1，等于返回 0，大于返回 1
References SymbolicNode::compare_same_type, SymbolicNode::type_priority.
Referenced by VariableNode::compare_same_type, compare_same_type.
bool SymbolicNode::equals(const SymbolicNode &other) const
判断两个节点是否结构相等。
other 待比较的节点 相等返回 true
References SymbolicNode::compare_same_type, SymbolicNode::hash, SymbolicNode::type_priority.
std::size_t SymbolicNode::hash() const
获取节点哈希值（带缓存）。
哈希值
References SymbolicNode::cached_hash, SymbolicNode::compute_hash, SymbolicNode::hash_computed.
Referenced by MatrixNode::compute_hash, SymbolicNode::equals.
virtual bool SymbolicNode::is_number() const
判断节点是否为数值节点。
virtual bool SymbolicNode::is_one() const
判断节点数值是否为 1。
virtual bool SymbolicNode::is_positive() const
判断节点是否可证明为严格正数（非数值节点默认返回 false）。
virtual bool SymbolicNode::is_zero() const
判断节点数值是否为 0。
Referenced by MatrixNode::compute_hash.
int PowerNode::type_priority() const override
返回节点类型的排序优先级，用于规范化排序。
Referenced by compute_hash.
int PowerNode::compare_same_type(const SymbolicNode &other) const override
与同类型节点进行比较（由子类实现）。
References base, SymbolicNode::compare, exponent.
std::size_t PowerNode::compute_hash() const override
计算当前节点的哈希值（由子类实现）。
References base, exponent, hash_combine, type_priority.
std::atomic<std::size_t> SymbolicNode::cached_hash
Referenced by SymbolicNode::hash.
std::atomic<bool> SymbolicNode::hash_computed
Referenced by SymbolicNode::hash.