solve_visitor.cpp
std::shared_ptr< SymbolicExpr > get_coeff(const Polynomial< SymbolicPolyCoeff > &p, int deg)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::number.
Referenced by SymbolicExpr::solve, lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, solve_polynomial_closed, lamina::solve_symbolic_poly, SymbolicExpr::solve_system.
static std::vector< std::shared_ptr< SymbolicExpr > > solve_polynomial_closed(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_cubic, lamina::solve_quartic.
Referenced by lamina::solve_dispatch.