modular_arithmetic.hpp
constexpr int64_t lamina::MODULAR_PRIMES[][]
预定义的大素数表，用于模运算多素数方案
constexpr size_t lamina::NUM_MODULAR_PRIMES
预定义素数表的长度
std::pair< int64_t, int64_t > lamina::crt(int64_t r1, int64_t m1, int64_t r2, int64_t m2)
中国剩余定理（两模数）
r1 第一个余数 m1 第一个模数 r2 第二个余数 m2 第二个模数 pair(合并余数, 合并模数 m1*m2) std::domain_error 若模数不互素
References lamina::extended_gcd.
Referenced by lamina::multi_crt.
int64_t lamina::extended_gcd(int64_t a, int64_t b, int64_t &s, int64_t &t)
扩展欧几里得算法，求 gcd(a, b) 及 Bezout 系数
a 第一个整数 b 第二个整数 s 输出 Bezout 系数 s，满足 a*s + b*t = gcd(a,b) t 输出 Bezout 系数 t gcd(a, b)
Referenced by lamina::crt, lamina::ModInt::inverse, lamina::rational_reconstruction.
std::vector< int64_t > lamina::generate_good_primes(int count, const std::vector< int64_t > &leading_coeffs, uint64_t start_from=1000000000ULL)
生成指定数量的好素数
count 需要的素数个数 leading_coeffs 首项系数列表（用于过滤） start_from 搜索起始值 好素数列表
References lamina::is_good_prime.
bool lamina::is_good_prime(int64_t p, const std::vector< int64_t > &leading_coeffs)
判断素数 p 是否为"好素数"（不整除任何首项系数）
p 待检测素数 leading_coeffs 首项系数列表 若 p 不整除任何系数则返回 true
Referenced by lamina::generate_good_primes.
uint64_t lamina::lammp_gcd(uint64_t a, uint64_t b)
计算两个无符号整数的最大公约数（调用 LAMMP）
a 第一个无符号整数 b 第二个无符号整数 gcd(a, b)
bool lamina::lammp_is_prime(uint64_t n)
判断无符号整数是否为素数
n 待判断的整数 是素数返回 true
uint64_t lamina::lammp_next_prime(uint64_t n)
求大于 n 的下一个素数
n 起始值 大于 n 的最小素数
std::pair< int64_t, int64_t > lamina::multi_crt(const std::vector< int64_t > &residues, const std::vector< int64_t > &primes)
多模数中国剩余定理
residues 余数列表 primes 对应的模数列表（两两互素） pair(合并余数, 合并模数) std::invalid_argument 若输入为空或大小不匹配
References lamina::crt.
std::pair< int64_t, int64_t > lamina::rational_reconstruction(int64_t x, int64_t m)
有理数重构：从模像 x mod m 恢复有理数 a/b
x 模像值 m 模数 pair(分子 a, 分母 b)；失败时返回 (0, 0)
References lamina::extended_gcd.