interval.cpp
static bool lamina::can_merge(const Interval &a, const Interval &b)
References lamina::endpoint_is_numeric, lamina::endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, lamina::Interval::upper.
Referenced by lamina::IntervalUnion::normalize.
static int lamina::compare_endpoints_lower(const Endpoint &a, const Endpoint &b)
References lamina::endpoint_is_numeric, lamina::endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::IntervalUnion::intersect.
static int lamina::compare_endpoints_upper(const Endpoint &a, const Endpoint &b)
References lamina::endpoint_is_numeric, lamina::endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::IntervalUnion::intersect, lamina::max_upper.
static bool lamina::endpoint_is_numeric(const Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::can_merge, lamina::compare_endpoints_lower, lamina::compare_endpoints_upper, lamina::Interval::contains, lamina::Interval::is_empty.
static double lamina::endpoint_numeric_value(const Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::can_merge, lamina::compare_endpoints_lower, lamina::compare_endpoints_upper, lamina::Interval::contains, lamina::Interval::is_empty.
static Endpoint lamina::max_upper(const Endpoint &a, const Endpoint &b)
References lamina::compare_endpoints_upper.
Referenced by lamina::IntervalUnion::normalize.
static bool lamina::parse_endpoint_value(const std::string &str, size_t &pos, Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::parse_numeric_value, lamina::skip_ws, lamina::starts_with_at, lamina::Endpoint::value.
Referenced by lamina::parse_single_interval.
static std::shared_ptr< SymbolicExpr > lamina::parse_numeric_value(const std::string &str, size_t &pos)
References SymbolicExpr::number.
Referenced by lamina::parse_endpoint_value.
static bool lamina::parse_single_interval(const std::string &str, size_t &pos, Interval &iv)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, lamina::parse_endpoint_value, lamina::skip_ws, lamina::Interval::upper.
Referenced by lamina::IntervalUnion::parse.
static size_t lamina::skip_ws(const std::string &str, size_t pos)
Referenced by lamina::IntervalUnion::parse, lamina::parse_endpoint_value, lamina::parse_single_interval.
static bool lamina::starts_with_at(const std::string &str, size_t pos, const std::string &prefix)
Referenced by lamina::IntervalUnion::parse, lamina::parse_endpoint_value.