Value
using Value::DataType = std::variant< std::nullptr_t, int, lmmc_real_t, ::BigInt, ::Rational, ::Irrational, std::shared_ptr<SymbolicExpr>, std::vector<Value>, std::vector<std::vector<Value> >>
内部存储的 variant 类型
Type
DataType Value::data
实际存储的数据
Referenced by Value, as_irrational, as_number, as_rational, as_symbolic, dot_product, is_numeric, matrix_multiply, operator<, operator==, to_string, vector_add.
Type Value::type
当前值的类型
Referenced by Value, as_irrational, as_number, as_rational, as_symbolic, as_symbolic_compatible, is_array, is_bigint, is_float, is_infinity, is_int, is_irrational, is_matrix, is_null, is_numeric, is_rational, is_string, is_symbolic, operator<, operator==, to_string.
std::string Value::_str_cache
字符串构造时的缓存（兼容旧测试）
Referenced by operator<, operator==, to_string.
Value::Value()
默认构造，初始化为 Null
Referenced by dot_product, matrix_multiply, vector_add.
Value::Value(const ::BigInt &bi)
Value::Value(const ::Irrational &ir)
Value::Value(const ::Rational &r)
Value::Value(const char *s)
Value::Value(const std::shared_ptr< SymbolicExpr > &sym)
Value::Value(const std::string &s)
Value::Value(const std::vector< std::vector< Value > > &mat)
Value::Value(const std::vector< Value > &arr)
References Array, data, is_matrix, Matrix, type.
Value::Value(int i)
Value::Value(lmmc_real_t f)
References Infinity.
Value::Value(std::nullptr_t)
Value::~Value()=default
::Irrational Value::as_irrational() const
将值转换为无理数表示
无理数对象
References BigInt, data, Float, Int, Irrational, Rational, type.
Referenced by as_symbolic.
lmmc_real_t Value::as_number() const
将值转换为浮点数
浮点数近似值，非数值类型返回 0.0
References BigInt, data, Float, Infinity, Int, Irrational, Rational, Symbolic, type.
Referenced by vector_add.
::Rational Value::as_rational() const
将值转换为有理数
有理数表示，非数值类型返回 0
References BigInt, data, Float, Int, Irrational, Rational, type.
Referenced by as_symbolic.
std::shared_ptr< SymbolicExpr > Value::as_symbolic() const
将值转换为符号表达式
符号表达式智能指针，不可转换时返回数值 0
References as_irrational, as_rational, BigInt, data, Float, SymbolicExpr::infinity, Infinity, Int, Irrational, SymbolicExpr::matrix, Matrix, SymbolicExpr::number, Rational, Symbolic, Irrational::to_symbolic, type.
bool Value::as_symbolic_compatible() const
判断值是否可转换为符号表达式
若可转换则返回 true
References BigInt, Float, Int, Irrational, Matrix, Rational, Symbolic, type.
Value Value::dot_product(const Value &other) const
向量点积
other 另一个向量 点积标量值
References Value, data, is_array, is_numeric.
bool Value::is_array() const
References Array, type.
Referenced by dot_product, vector_add.
bool Value::is_bigint() const
References BigInt, type.
bool Value::is_float() const
References Float, type.
bool Value::is_infinity() const
References Infinity, type.
bool Value::is_int() const
References Int, type.
bool Value::is_irrational() const
References Irrational, type.
bool Value::is_matrix() const
References Matrix, type.
Referenced by Value, matrix_multiply.
bool Value::is_null() const
References Null, type.
bool Value::is_numeric() const
References BigInt, data, Float, Int, Irrational, Rational, Symbolic, type.
Referenced by dot_product, matrix_multiply, vector_add.
bool Value::is_rational() const
References Rational, type.
bool Value::is_string() const
References String, type.
bool Value::is_symbolic() const
References Symbolic, type.
Value Value::matrix_multiply(const Value &other) const
矩阵乘法
other 右矩阵 乘积矩阵
References Value, data, is_matrix, is_numeric.
bool Value::operator<(const Value &other) const
References _str_cache, data, String, type.
bool Value::operator==(const Value &other) const
References _str_cache, data, String, type.
std::string Value::to_string() const
将值转换为可读字符串
格式化的字符串表示
References _str_cache, Array, BigInt, data, Float, Infinity, Int, Irrational, Matrix, Null, Rational, String, Symbolic, to_string, type.
Referenced by to_string.
Value Value::vector_add(const Value &other) const
向量加法
other 另一个向量 逐元素相加的结果向量
References Value, as_number, data, is_array, is_numeric.