solve_polynomial.hpp
std::vector< Rational > lamina::find_rational_roots(const Polynomial< Rational > &poly)
查找有理系数多项式的所有有理根。
poly 有理系数多项式 有理根列表
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::eval, lamina::Polynomial< CoeffType >::is_zero, BigInt::lcm, lamina::Polynomial< CoeffType >::lead_coeff, lamina::positive_divisors, lamina::Rational, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::solve_by_factoring.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_biquadratic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::string &var)
求解双二次方程 ax⁴ + bx² + c = 0。
a 四次项系数 b 二次项系数 c 常数项 var 求解变量名 所有根的符号表达式列表
References lamina::is_purely_numeric, lamina::negate, SymbolicExpr::number, lamina::solve_quadratic_internal, SymbolicExpr::sqrt.
Referenced by lamina::solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_by_factoring(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
通过因式分解求解多项式方程。
poly 符号系数多项式 var 求解变量名 所有根的符号表达式列表
References lamina::convert_to_rational_poly, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::is_zero, lamina::make_rootof_solutions, SymbolicExpr::number, lamina::Rational, lamina::rational_to_symbolic_poly, lamina::solve_closed_form_poly, lamina::square_free_factorization.
Referenced by lamina::find_roots_with_multiplicity, lamina::solve_dispatch, lamina::solve_symbolic_poly.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_cubic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::string &var)
使用三次公式求解三次方程 ax³ + bx² + cx + d = 0。
a 三次项系数 b 二次项系数 c 一次项系数 d 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, lamina::cbrt_expr, SymbolicExpr::divide, lamina::is_purely_numeric, SymbolicExpr::multiply, lamina::negate, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_linear_internal, lamina::solve_quadratic_internal, SymbolicExpr::sqrt, lamina::sub.
Referenced by lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, solve_polynomial_closed, lamina::solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_quartic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::shared_ptr< SymbolicExpr > &e, const std::string &var)
使用四次公式求解四次方程 ax⁴ + bx³ + cx² + dx + e = 0。
a 四次项系数 b 三次项系数 c 二次项系数 d 一次项系数 e 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, SymbolicExpr::divide, lamina::is_purely_numeric, SymbolicExpr::multiply, lamina::negate, lamina::num, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_biquadratic, lamina::solve_cubic, lamina::solve_quadratic_internal, SymbolicExpr::sqrt, lamina::sub.
Referenced by lamina::solve_closed_form_from_poly, lamina::solve_closed_form_poly, solve_polynomial_closed.
std::vector< std::pair< Polynomial< Rational >, int > > lamina::square_free_factorization(const Polynomial< Rational > &poly)
对有理系数多项式进行无平方因子分解。
poly 有理系数多项式 因子与重数的列表
References lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::gcd, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::make_monic.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, lamina::find_roots_with_multiplicity, lamina::solve_by_factoring.