symbolic_ast.hpp
using NodeMap = std::unordered_map<std::shared_ptr<SymbolicNode>, T, NodeHash, NodeEqual>
using NodeSet = std::unordered_set<std::shared_ptr<SymbolicNode>, NodeHash, NodeEqual>
void hash_combine(std::size_t &seed, std::size_t value)
将一个哈希值混合到种子中，用于组合多个字段的哈希。
seed 当前哈希种子，混合后就地更新 value 要混合的哈希值
Referenced by AddNode::compute_hash, MultiplyNode::compute_hash, PowerNode::compute_hash, FunctionNode::compute_hash, MatrixNode::compute_hash, RelationalNode::compute_hash, LogicalNode::compute_hash.