lamina::RationalDecompositionStrategy
bool lamina::RationalDecompositionStrategy::extract_rational(const SymbolicExpr &expr, const std::string &var, Polynomial< Rational > &P_out, Polynomial< Rational > &Q_out)
把被积表达式拆解为 P(x)/Q(x)（P、Q 均为有理系数多项式）。
expr 被积表达式 var 积分变量名 P_out 输出参数：分子多项式 Q_out 输出参数：分母多项式 成功识别为有理函数返回 true；表达式含 sin/exp/log/非整数指数等 非多项式部分时返回 false
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::gcd, lamina::Rational, SymbolicExpr::root, lamina::Polynomial< CoeffType >::trim.
Referenced by try_integrate.
bool lamina::RationalDecompositionStrategy::factor_denominator(const Polynomial< Rational > &Q, std::vector< std::pair< Polynomial< Rational >, int > > &factors_out)
把 Q 分解为线性 (x-r) 与不可约二次 (x²+px+q) 因子的集合。
Q 分母多项式 factors_out 输出：(因子, 重数) 列表；每个因子是首一线性或首一不可约二次 全部分解为线性/不可约二次因子返回 true；含有更高次不可约因子或 有理根定理无法穷尽线性因子时返回 false
References lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::find_rational_roots, lamina::Polynomial< CoeffType >::make_monic, lamina::Rational, lamina::square_free_factorization, lamina::Polynomial< CoeffType >::variable_name.
Referenced by try_integrate.
std::shared_ptr< SymbolicExpr > lamina::RationalDecompositionStrategy::integrate_term(const Polynomial< Rational > &numerator, const Polynomial< Rational > &factor, int power, const std::string &var)
对单个部分分式项 numerator(x)/factor(x)^power 求积分。
支持的形式： factor 是 x-r：power=1 → A·ln(x-r)；power≥2 → -A/((power-1)·(x-r)^(power-1)) factor 是不可约二次 x²+px+q：power=1 → 拆为 (B/2)·ln(q(x)) + (D-Bp/2)·(2/√(4q-p²))·arctan((2x+p)/√(4q-p²))；power≥2 暂以未求值积分节点返回 numerator 分子多项式（线性因子时为常数；二次因子时为 B·x+C） factor 单个因子多项式（首一线性或首一不可约二次） power 因子的幂指数（≥1） var 积分变量名 该项的原函数表达式
References SymbolicExpr::add, FunctionNode::Calculus_Integral, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::ln, lamina::make_arctan, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::Rational, SymbolicExpr::sqrt, SymbolicExpr::variable.
Referenced by try_integrate.
std::string lamina::RationalDecompositionStrategy::name() const override
获取策略名称
策略名称字符串
void lamina::RationalDecompositionStrategy::poly_divide(const Polynomial< Rational > &P, const Polynomial< Rational > &Q, Polynomial< Rational > &quotient_out, Polynomial< Rational > &remainder_out)
多项式长除法：P = Q·quotient + remainder。
P 被除多项式 Q 除多项式（不能为零） quotient_out 输出：商多项式 remainder_out 输出：余式多项式（deg(remainder) < deg(Q)）
References lamina::Polynomial< CoeffType >::div_mod.
Referenced by try_integrate.
bool lamina::RationalDecompositionStrategy::solve_coefficients(const Polynomial< Rational > &P, const Polynomial< Rational > &Q, const std::vector< std::pair< Polynomial< Rational >, int > > &factors, std::vector< Polynomial< Rational > > &numerators_out)
求解部分分式各项的待定系数。
对线性因子 (x-r) 重数 m，引入 m 个常数系数 A_1..A_m；对不可约二次因子 q(x) 重数 m，引入 m 对线性系数 (B_l, C_l)。通过比较多项式系数构造方阵并用 gaussian_eliminate 求解。 P 部分分式分解的目标多项式（真分式的分子，deg(P) < deg(Q)） Q 部分分式分解的目标分母 factors 因子分解（来自 factor_denominator） numerators_out 输出：与 (factor_index, l) 一一对应的分子多项式列表， 每个分子要么是常数 (A)，要么是一次多项式 (B·x + C) 系数解唯一存在时返回 true；系统无解或退化时返回 false
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::Rational, lamina::Polynomial< CoeffType >::variable_name.
Referenced by try_integrate.
std::shared_ptr< SymbolicExpr > lamina::RationalDecompositionStrategy::try_integrate(const SymbolicExpr &expr, const std::string &var, Integrator &ctx, int depth=0) override
尝试对表达式进行积分
expr 被积表达式 var 积分变量名 ctx 积分器上下文 depth 当前递归深度 积分结果，失败返回 nullptr
References SymbolicExpr::add, FunctionNode::Calculus_Integral, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Integrator::depends_on, extract_rational, factor_denominator, integrate_term, SymbolicExpr::multiply, SymbolicExpr::number, poly_divide, SymbolicExpr::power, lamina::Rational, SymbolicExpr::root, solve_coefficients, SymbolicExpr::variable, lamina::Polynomial< CoeffType >::variable_name.