root_of_utils.cpp
static bool lamina::expr_has_free_variables(const std::shared_ptr< SymbolicNode > &node)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands, MatrixNode::storage.
Referenced by lamina::try_convert_to_rational_poly.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::make_rootof_solutions(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
为不可约多项式构造 RootOf 解表达式列表。
poly 符号系数多项式 var 求解变量名 RootOf 表达式列表，每个元素对应多项式的一个根
References lamina::Polynomial< CoeffType >::degree, SymbolicExpr::root_of, lamina::symbolic_poly_to_expr.
Referenced by lamina::solve_by_factoring, lamina::solve_dispatch.
std::optional< lmmc_real_t > lamina::rootof_evaluate(const std::shared_ptr< SymbolicExpr > &rootof_expr)
对 RootOf 表达式进行数值求值。
rootof_expr RootOf 符号表达式 若求值成功则返回数值结果，否则返回 nullopt
References lamina::isolate_real_roots, lamina::SolveOptions::max_newton_iterations, lamina::newton_raphson, SymbolicExpr::number, FunctionNode::RootOf, lamina::SolveOptions::tolerance, lamina::try_convert_to_rational_poly.
std::shared_ptr< SymbolicExpr > lamina::rootof_simplify(const std::shared_ptr< SymbolicExpr > &rootof_expr)
化简 RootOf 表达式（如可用根式表示则转换为闭式）。
rootof_expr RootOf 符号表达式 化简后的符号表达式
References FunctionNode::RootOf, lamina::rootof_simplify, lamina::solve_closed_form_from_poly, lamina::sort_roots_by_convention.
Referenced by lamina::rootof_simplify.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_closed_form_from_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::solve_cubic, lamina::solve_quartic, SymbolicExpr::sqrt.
Referenced by lamina::rootof_simplify.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::sort_roots_by_convention(const std::vector< std::shared_ptr< SymbolicExpr > > &roots)
References lamina::RootWithIndex::eval_success, lamina::RootWithIndex::expr, lamina::RootWithIndex::imag_part, lamina::RootWithIndex::is_real, lamina::RootWithIndex::real_part, lamina::try_eval_complex.
Referenced by lamina::rootof_simplify.
static std::shared_ptr< SymbolicExpr > lamina::symbolic_poly_to_expr(const Polynomial< SymbolicPolyCoeff > &poly)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::variable, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::make_rootof_solutions.
static bool lamina::try_convert_to_rational_poly(const Polynomial< SymbolicPolyCoeff > &sym_poly, Polynomial< Rational > &out_poly)
References lamina::Polynomial< CoeffType >::coeffs, lamina::expr_has_free_variables, Rational::from_double, lamina::Rational, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::rootof_evaluate.
static std::pair< std::complex< double >, bool > lamina::try_eval_complex(const std::shared_ptr< SymbolicExpr > &expr)
Referenced by lamina::sort_roots_by_convention.