NormalizationVisitor
std::shared_ptr<SymbolicNode> NormalizationVisitor::result
规范化结果节点
Referenced by get_result, visit, visit, visit, visit, visit, visit, visit, visit, visit.
const lamina::AssumptionContext* NormalizationVisitor::assumptions_
Referenced by try_assumption_simplify, visit, visit.
NormalizationVisitor::NormalizationVisitor()
Default constructor (backward compatible, no assumptions).
NormalizationVisitor::NormalizationVisitor(const lamina::AssumptionContext *ctx)
Construct with an optional AssumptionContext for assumption-aware simplification.
std::shared_ptr< SymbolicNode > NormalizationVisitor::expand_product(const std::shared_ptr< SymbolicNode > &lhs, const std::shared_ptr< SymbolicNode > &rhs)
展开两个节点的乘积（分配律）
lhs 左操作数 rhs 右操作数 展开后的 AST 节点
References add_numbers, expand_product, multiply_numbers.
Referenced by expand_product, ExpandVisitor::visit, visit, ExpandVisitor::visit.
std::shared_ptr< SymbolicNode > NormalizationVisitor::get_result() const
获取规范化结果
化简后的 AST 节点
References result.
Referenced by SymbolicExpr::differentiate, SymbolicExpr::simplify, SymbolicExpr::substitute, LimitVisitor::visit, LimitVisitor::visit, visit, LimitVisitor::visit, visit, LimitVisitor::visit, IntegrationVisitor::visit.
void NormalizationVisitor::visit(AddNode &node) override
References add_numbers, AddNode::operands, result.
void NormalizationVisitor::visit(FunctionNode &node) override
References FunctionNode::Abs, FunctionNode::ArcSin, FunctionNode::ArcTan, FunctionNode::arguments, assumptions_, check_negative_arg, FunctionNode::Cos, FunctionNode::Exp, Rational::get_denominator, Rational::get_numerator, get_pi_coeff, get_result, FunctionNode::Infinity, BigInt::IsNegative, FunctionNode::LambertW, FunctionNode::Ln, FunctionNode::Log, result, FunctionNode::Sin, BigInt::sqrt, FunctionNode::Sqrt, FunctionNode::Tan, try_assumption_simplify, FunctionNode::type.
void NormalizationVisitor::visit(LogicalNode &node) override
References LogicalNode::left, LogicalNode::op, result, LogicalNode::right.
void NormalizationVisitor::visit(MatrixNode &node) override
References MatrixNode::cols, result, MatrixNode::rows, MatrixNode::storage.
void NormalizationVisitor::visit(MultiplyNode &node) override
References add_numbers, assumptions_, expand_product, Rational::get_denominator, Rational::get_numerator, get_result, BigInt::is_zero, multiply_numbers, MultiplyNode::operands, result, BigInt::to_double.
void NormalizationVisitor::visit(NumberNode &node) override
References NumberNode::clone, result.
void NormalizationVisitor::visit(PowerNode &node) override
References PowerNode::base, SymbolicFactory::create_multiply, PowerNode::exponent, Rational::get_denominator, Rational::get_numerator, BigInt::is_zero, result, BigInt::to_double.
void NormalizationVisitor::visit(RelationalNode &node) override
References RelationalNode::left, RelationalNode::op, result, RelationalNode::right.
void NormalizationVisitor::visit(VariableNode &node) override
References VariableNode::clone, result.
std::shared_ptr< SymbolicNode > NormalizationVisitor::try_assumption_simplify(const std::shared_ptr< SymbolicNode > &node)
Attempt assumption-based simplification on a node.
Applies the following rules when an AssumptionContext is available: sqrt(x²) → x when x is NonNegative sqrt(x²) → abs(x) when x is Real (but not NonNegative) abs(x) → x when x is Positive abs(x) → -x when x is Negative node The node to attempt simplification on Simplified node if a rule applied, or nullptr if no rule matched
References FunctionNode::Abs, assumptions_, lamina::AssumptionContext::is_negative, lamina::AssumptionContext::is_nonnegative, lamina::AssumptionContext::is_positive, lamina::AssumptionContext::is_real, FunctionNode::Sqrt, lamina::True.
Referenced by visit.
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.