lamina::FGLMPoly
size_t lamina::FGLMPoly::num_vars
变量个数
Referenced by from_monomial, reduce, zero.
std::vector<std::pair<Monomial, Rational> > lamina::FGLMPoly::terms
项列表
Referenced by add_term, lamina::fglm_convert, is_zero, LC, LM, normalize, lamina::detail::poly_to_vector, reduce, sort_terms.
lamina::FGLMPoly::FGLMPoly()
默认构造
Referenced by zero.
lamina::FGLMPoly::FGLMPoly(size_t n)
构造指定变量数的零多项式
n 变量个数
void lamina::FGLMPoly::add_term(const Monomial &m, const Rational &c)
添加一项
m 单项式 c 系数（零系数不添加）
References Rational::is_zero, terms.
Referenced by lamina::fglm_convert, from_monomial, reduce.
bool lamina::FGLMPoly::is_zero() const
判断是否为零多项式
References terms.
Referenced by lamina::fglm_convert, reduce.
Rational lamina::FGLMPoly::LC() const
获取首项系数
References lamina::Rational, terms.
Referenced by lamina::fglm_convert, reduce.
Monomial lamina::FGLMPoly::LM() const
获取首项单项式
References terms.
Referenced by lamina::fglm_convert, lamina::is_zero_dimensional, reduce.
void lamina::FGLMPoly::normalize()
合并同类项并去除零项
References terms.
Referenced by lamina::fglm_convert, reduce.
FGLMPoly lamina::FGLMPoly::reduce(const std::vector< FGLMPoly > &basis, const MonomialOrder &order) const
对给定基进行多项式约化
basis Gröbner 基 order 单项式序 约化后的余式
References add_term, lamina::divides_monomial, is_zero, LC, LM, normalize, num_vars, sort_terms, terms.
Referenced by lamina::normal_form.
void lamina::FGLMPoly::sort_terms(const MonomialOrder &order)
按指定单项式序排序各项
order 单项式序
References terms.
Referenced by lamina::fglm_convert, reduce.
static FGLMPoly lamina::FGLMPoly::from_monomial(const Monomial &m, size_t num_vars)
从单项式构造多项式（系数为 1）
m 单项式 num_vars 变量个数 仅含一项的多项式
References add_term, num_vars, lamina::Rational.
Referenced by lamina::fglm_convert.
static FGLMPoly lamina::FGLMPoly::zero(size_t num_vars)
构造零多项式
num_vars 变量个数 零多项式
References FGLMPoly, num_vars.