SymbolicVisitor
int SymbolicVisitor::current_depth
Referenced by SymbolicVisitor::DepthGuard::DepthGuard, SymbolicVisitor::DepthGuard::~DepthGuard.
constexpr int SymbolicVisitor::MAX_DEPTH
Referenced by SymbolicVisitor::DepthGuard::DepthGuard.
virtual SymbolicVisitor::~SymbolicVisitor()=default
virtual void SymbolicVisitor::visit(AddNode &node)=0
virtual void SymbolicVisitor::visit(FunctionNode &node)=0
virtual void SymbolicVisitor::visit(LogicalNode &node)
virtual void SymbolicVisitor::visit(MatrixNode &node)=0
virtual void SymbolicVisitor::visit(MultiplyNode &node)=0
virtual void SymbolicVisitor::visit(NumberNode &node)=0
Referenced by NumberNode::accept, VariableNode::accept, AddNode::accept, MultiplyNode::accept, PowerNode::accept, FunctionNode::accept, MatrixNode::accept, RelationalNode::accept, LogicalNode::accept.
virtual void SymbolicVisitor::visit(PowerNode &node)=0
virtual void SymbolicVisitor::visit(RelationalNode &node)
virtual void SymbolicVisitor::visit(VariableNode &node)=0