lamina
Boundedness
Symbol has finite bounds
Domain
Complex numbers (default, least specific)
InequalityType
严格大于
MonomialOrderType
字典序
Parity
Even integer
Sign
0
SolveStrategy
闭式公式求解
Tribool
Property definitely holds
using lamina::MatchMap = typedef std::unordered_map<std::string, SymbolicExpr>
匹配结果映射，通配符名称 → 绑定的表达式
using lamina::Monomial = typedef std::vector<int>
单项式类型，以整数向量表示各变量的指数
constexpr int lamina::MAX_TRANSCENDENTAL_DEPTH
Referenced by solve_transcendental_impl.
constexpr int64_t lamina::MODULAR_PRIMES[][]
预定义的大素数表，用于模运算多素数方案
constexpr size_t lamina::NUM_MODULAR_PRIMES
预定义素数表的长度
static std::shared_ptr< SymbolicExpr > lamina::acos_expr(const std::shared_ptr< SymbolicExpr > &x)
References FunctionNode::ArcCos.
static std::shared_ptr< NumberNode > lamina::add_number_nodes(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
References Rational.
Referenced by multiply_no_expand.
std::shared_ptr< SymbolicExpr > lamina::arc_length_x(std::shared_ptr< SymbolicExpr > fx, std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b)
计算函数 f(x) 在 [a, b] 上的弧长
fx 曲线函数表达式 f(x) a 区间左端点 b 区间右端点 弧长的符号表达式
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::sqrt.
std::shared_ptr< SymbolicExpr > lamina::arc_length_y(std::shared_ptr< SymbolicExpr > fy, std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b)
计算函数 f(y) 在 [a, b] 上的弧长
fy 曲线函数表达式 f(y) a 区间左端点 b 区间右端点 弧长的符号表达式
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::sqrt.
std::optional< NumericRoot > lamina::bisection(const std::shared_ptr< SymbolicExpr > &f, const std::string &var, lmmc_real_t lo, lmmc_real_t hi, const SolveOptions &opts)
二分法求根。
f 目标函数表达式 var 求解变量名 lo 区间下界（要求 f(lo) 与 f(hi) 异号） hi 区间上界 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
Referenced by newton_raphson.
static bool lamina::can_merge(const Interval &a, const Interval &b)
References endpoint_is_numeric, endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, lamina::Interval::upper.
Referenced by lamina::IntervalUnion::normalize.
static Rational lamina::cauchy_bound(const Polynomial< Rational > &poly)
References Rational::abs, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, Rational::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, Rational.
Referenced by isolate_real_roots.
static std::shared_ptr< SymbolicExpr > lamina::cbrt_expr(const std::shared_ptr< SymbolicExpr > &x)
References SymbolicExpr::number, SymbolicExpr::power, Rational.
Referenced by solve_cubic.
static bool lamina::collect_denominator_factors(const std::shared_ptr< SymbolicNode > &node, std::vector< std::shared_ptr< SymbolicNode > > &den_factors, std::vector< std::shared_ptr< SymbolicExpr > > &den_constraints)
References collect_denominator_factors, SymbolicFactory::create_number, SymbolicFactory::create_power, get_integer_value, is_polynomial_node.
Referenced by collect_denominator_factors, lamina::Solver::solve_polynomial_system.
static std::vector< int > lamina::collect_power_exponents(const RelationStore &store, const std::string &lhs_name, const std::string &rhs_name)
Helper: collect positive integer exponents that appear in PowerNode expressions within the RelationStore involving the given variable names.
References lamina::RelationStore::get_relations, is_positive_integer_number, BigInt::to_string.
Referenced by lamina::InferenceEngine::apply_monotonicity_rules.
static void lamina::collect_transcendental_subexprs(const std::shared_ptr< SymbolicNode > &node, const std::string &var, std::vector< std::shared_ptr< SymbolicExpr > > &candidates)
References collect_transcendental_subexprs, FunctionNode::Cos, depends_on_var, FunctionNode::Exp, FunctionNode::Sin, FunctionNode::Tan.
Referenced by collect_transcendental_subexprs, detect_substitution.
static int lamina::compare_endpoints_lower(const Endpoint &a, const Endpoint &b)
References endpoint_is_numeric, endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::IntervalUnion::intersect.
static int lamina::compare_endpoints_upper(const Endpoint &a, const Endpoint &b)
References endpoint_is_numeric, endpoint_numeric_value, lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::IntervalUnion::intersect, max_upper.
std::shared_ptr< SymbolicExpr > lamina::complex_abs(const ComplexSymbolic &z)
计算复数的模
z 输入复数 模的符号表达式
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, SymbolicExpr::number, SymbolicExpr::power, lamina::ComplexSymbolic::real, SymbolicExpr::sqrt.
Referenced by complex_locus_circle, complex_locus_perpendicular_bisector.
ComplexSymbolic lamina::complex_add(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数加法
a 加数 b 加数 和
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, make_complex, lamina::ComplexSymbolic::real.
std::shared_ptr< SymbolicExpr > lamina::complex_arg(const ComplexSymbolic &z)
计算复数的辐角
z 输入复数 辐角的符号表达式
References SymbolicExpr::atan2, lamina::ComplexSymbolic::imag, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_conj(const ComplexSymbolic &z)
计算复数的共轭
z 输入复数 共轭复数
References lamina::ComplexSymbolic::imag, make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_div(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数除法
a 被除数 b 除数 商
References SymbolicExpr::add, SymbolicExpr::divide, lamina::ComplexSymbolic::imag, make_complex, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::ComplexSymbolic::real.
Referenced by solve_complex_quadratic.
ComplexSymbolic lamina::complex_exp_form(std::shared_ptr< SymbolicExpr > r, std::shared_ptr< SymbolicExpr > theta)
将极坐标形式转换为指数形式复数 r*e^(i*theta)
r 模 theta 辐角 对应的符号复数
References SymbolicExpr::cos, make_complex, SymbolicExpr::multiply, SymbolicExpr::sin.
Referenced by complex_trig_form, solve_complex_nth_root.
std::shared_ptr< SymbolicExpr > lamina::complex_locus_circle(const ComplexSymbolic &a, std::shared_ptr< SymbolicExpr > r, const std::string &z_var="z")
生成以 a 为圆心、r 为半径的复数轨迹方程 |z - a| = r
a 圆心复数 r 半径 z_var 复变量名，默认为 "z" 轨迹方程的符号表达式
References complex_abs, complex_sub, SymbolicExpr::eq, make_complex, SymbolicExpr::number, SymbolicExpr::variable.
std::shared_ptr< SymbolicExpr > lamina::complex_locus_perpendicular_bisector(const ComplexSymbolic &a, const ComplexSymbolic &b, const std::string &z_var="z")
生成复数 a 和 b 的中垂线轨迹方程 |z - a| = |z - b|
a 第一个复数点 b 第二个复数点 z_var 复变量名，默认为 "z" 轨迹方程的符号表达式
References complex_abs, complex_sub, SymbolicExpr::eq, make_complex, SymbolicExpr::number, SymbolicExpr::variable.
ComplexSymbolic lamina::complex_mul(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数乘法
a 乘数 b 乘数 积
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
ComplexSymbolic lamina::complex_sub(const ComplexSymbolic &a, const ComplexSymbolic &b)
复数减法
a 被减数 b 减数 差
References SymbolicExpr::add, lamina::ComplexSymbolic::imag, make_complex, SymbolicExpr::multiply, SymbolicExpr::number, lamina::ComplexSymbolic::real.
Referenced by complex_locus_circle, complex_locus_perpendicular_bisector.
ComplexSymbolic lamina::complex_trig_form(std::shared_ptr< SymbolicExpr > r, std::shared_ptr< SymbolicExpr > theta)
将极坐标形式转换为三角形式复数 r*(cos(theta) + i*sin(theta))
r 模 theta 辐角 对应的符号复数
References complex_exp_form.
static std::shared_ptr< SymbolicExpr > lamina::compute_determinant(const std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &matrix, size_t n)
References SymbolicExpr::add, compute_determinant, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by compute_determinant, lamina::ParametricSolver::solve_system_piecewise.
bool lamina::contains(const SymbolicExpr &expr, const std::string &var)
判断符号表达式是否包含指定变量
expr 符号表达式 var 变量名 包含该变量返回 true
References depends_on_var, SymbolicExpr::root.
Referenced by depends_on_parameters, lamina::ParametricSolver::solve_polynomial_parametric, lamina::Solver::solve_polynomial_system.
static bool lamina::convert_to_rational_poly(const Polynomial< SymbolicPolyCoeff > &sym_poly, Polynomial< Rational > &out_poly)
References FunctionNode::arguments, PowerNode::base, lamina::Polynomial< CoeffType >::coeffs, PowerNode::exponent, Rational::from_double, AddNode::operands, MultiplyNode::operands, Rational, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by solve_by_factoring.
static int lamina::count_sign_changes(const std::vector< Rational > &values)
References Rational.
Referenced by sturm_sign_changes_at, sturm_sign_changes_at_neg_inf, sturm_sign_changes_at_pos_inf.
std::pair< int64_t, int64_t > lamina::crt(int64_t r1, int64_t m1, int64_t r2, int64_t m2)
中国剩余定理（两模数）
r1 第一个余数 m1 第一个模数 r2 第二个余数 m2 第二个模数 pair(合并余数, 合并模数 m1*m2) std::domain_error 若模数不互素
References extended_gcd.
Referenced by multi_crt.
static std::optional< ExpBasePattern > lamina::decompose_exp_base_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References depends_on_var, SymbolicExpr::multiply, SymbolicExpr::number, try_evaluate_numeric.
Referenced by solve_transcendental_impl.
static std::optional< LambertWPattern > lamina::decompose_lambert_w_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References depends_on_var, FunctionNode::Exp, SymbolicExpr::multiply, nodes_equal, SymbolicExpr::number.
Referenced by solve_transcendental_impl.
static std::optional< InversePattern > lamina::decompose_trig_exp_pattern(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
References FunctionNode::Cos, SymbolicFactory::create_multiply, depends_on_var, SymbolicExpr::divide, FunctionNode::Exp, FunctionNode::Ln, SymbolicExpr::multiply, SymbolicExpr::number, FunctionNode::Sin, FunctionNode::Tan.
Referenced by solve_transcendental_impl.
static void lamina::deduplicate_candidates(std::vector< std::shared_ptr< SymbolicExpr > > &candidates)
Referenced by detect_substitution.
static bool lamina::depends_on_any_param(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &parameters)
References depends_on_var.
Referenced by lamina::InequalitySolver::solve_parametric_inequality.
static bool lamina::depends_on_parameters(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &parameters)
References contains.
Referenced by lamina::ParametricSolver::solve_system_piecewise.
bool lamina::depends_on_var(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
判断符号节点是否依赖指定变量
node 符号节点 var 变量名 包含该变量返回 true
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, RelationalNode::left, LogicalNode::left, VariableNode::name, AddNode::operands, MultiplyNode::operands, RelationalNode::right, LogicalNode::right, MatrixNode::storage.
Referenced by collect_transcendental_subexprs, contains, decompose_exp_base_pattern, decompose_lambert_w_pattern, decompose_trig_exp_pattern, lamina::Integrator::depends_on, depends_on_any_param, detect_substitution, lamina::LinearSubstitutionStrategy::extract_linear_arg, invert_substitution_h, lamina::IntegrationTable::load_defaults, lamina::anonymous_namespace{integration.cpp}::rd_is_const_in, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality, symbolic_to_poly_recursive, lamina::LinearSubstitutionStrategy::try_integrate, lamina::anonymous_namespace{solver.cpp}::PolyBuilder::visit, IntegrationVisitor::visit.
std::optional< SubstitutionResult > lamina::detect_substitution(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
检测表达式中可用的换元模式。
expr 待分析的表达式 var 目标变量名 若检测到有效换元则返回 SubstitutionResult，否则返回 nullopt
References collect_transcendental_subexprs, SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_power, deduplicate_candidates, depends_on_var, SymbolicExpr::exp, has_exp_k_var_terms, rewrite_exp_as_u_power, SymbolicExpr::variable.
Referenced by solve_transcendental_impl.
static int lamina::determine_leading_sign(const Polynomial< SymbolicPolyCoeff > &poly)
References lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::lead_coeff, num.
Referenced by lamina::InequalitySolver::build_sign_chart, lamina::InequalitySolver::solve_rational_inequality.
bool lamina::divides_monomial(const Monomial &divisor, const Monomial &target)
判断 divisor 是否整除 target
divisor 除数单项式 target 被除数单项式 divisor 的每个分量都不超过 target 对应分量时返回 true
Referenced by fglm_convert, quotient_dimension, lamina::FGLMPoly::reduce.
static bool lamina::endpoint_is_numeric(const Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by can_merge, compare_endpoints_lower, compare_endpoints_upper, lamina::Interval::contains, lamina::Interval::is_empty.
static double lamina::endpoint_numeric_value(const Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by can_merge, compare_endpoints_lower, compare_endpoints_upper, lamina::Interval::contains, lamina::Interval::is_empty.
static std::optional< double > lamina::endpoint_to_double(const Endpoint &ep)
Helper: extract a numeric double value from an Endpoint.
Returns std::nullopt if the endpoint is not a finite numeric value.
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_pos_infinity, lamina::Endpoint::value.
Referenced by lamina::InferenceEngine::propagate_bounds.
static bool lamina::expr_has_free_variables(const std::shared_ptr< SymbolicNode > &node)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands, MatrixNode::storage.
Referenced by try_convert_to_rational_poly.
int64_t lamina::extended_gcd(int64_t a, int64_t b, int64_t &s, int64_t &t)
扩展欧几里得算法，求 gcd(a, b) 及 Bezout 系数
a 第一个整数 b 第二个整数 s 输出 Bezout 系数 s，满足 a*s + b*t = gcd(a,b) t 输出 Bezout 系数 t gcd(a, b)
Referenced by crt, lamina::ModInt::inverse, rational_reconstruction.
T lamina::extract_coeff_value(const std::shared_ptr< SymbolicExpr > &c)
从符号表达式中提取指定类型的系数值
T 目标系数类型 c 符号表达式 提取的系数值
BigInt lamina::extract_coeff_value< BigInt >(const std::shared_ptr< SymbolicExpr > &c)
References Rational::is_integer, Rational::to_BigInt.
Rational lamina::extract_coeff_value< Rational >(const std::shared_ptr< SymbolicExpr > &c)
References Rational::from_double, Rational, Rational::simplify.
SymbolicPolyCoeff lamina::extract_coeff_value< SymbolicPolyCoeff >(const std::shared_ptr< SymbolicExpr > &c)
static std::shared_ptr< SymbolicExpr > lamina::extract_coefficient(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
Referenced by extract_constant_term, lamina::ParametricSolver::solve_linear_parametric, lamina::ParametricSolver::solve_system_piecewise.
static std::shared_ptr< SymbolicExpr > lamina::extract_constant_term(const std::shared_ptr< SymbolicExpr > &expr, const std::vector< std::string > &unknowns)
References extract_coefficient, SymbolicExpr::number.
Referenced by lamina::ParametricSolver::solve_linear_parametric.
static int lamina::extract_exp_multiplier(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References FunctionNode::Exp.
Referenced by has_exp_k_var_terms, rewrite_exp_as_u_power.
std::vector< FGLMPoly > lamina::fglm_convert(const std::vector< FGLMPoly > &source_basis, const MonomialOrder &source_order, const MonomialOrder &target_order, size_t num_vars)
FGLM 算法：将零维理想的 Gröbner 基从源序转换到目标序
source_basis 源序下的 Gröbner 基 source_order 源单项式序 target_order 目标单项式序 num_vars 变量个数 目标序下的 Gröbner 基 std::runtime_error 理想非零维或维数过大时抛出
References lamina::FGLMPoly::add_term, lamina::detail::GaussianEliminator::add_vector, divides_monomial, lamina::FGLMPoly::from_monomial, lamina::FGLMPoly::is_zero, is_zero_dimensional, lamina::FGLMPoly::LC, lamina::FGLMPoly::LM, lamina::detail::MonomialEnumerator::next, normal_form, lamina::FGLMPoly::normalize, quotient_dimension, Rational, lamina::FGLMPoly::sort_terms, lamina::FGLMPoly::terms.
Referenced by grevlex_to_lex.
std::vector< Rational > lamina::find_rational_roots(const Polynomial< Rational > &poly)
查找有理系数多项式的所有有理根。
poly 有理系数多项式 有理根列表
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::eval, lamina::Polynomial< CoeffType >::is_zero, BigInt::lcm, lamina::Polynomial< CoeffType >::lead_coeff, positive_divisors, Rational, lamina::Polynomial< CoeffType >::variable_name.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, solve_by_factoring.
static std::vector< std::pair< std::shared_ptr< SymbolicExpr >, int > > lamina::find_roots_with_multiplicity(const std::shared_ptr< SymbolicExpr > &expr, const std::string &variable)
References SymbolicExpr::number, Rational, solve_by_factoring, square_free_factorization, Rational::to_double.
Referenced by lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_rational_inequality.
void lamina::gaussian_eliminate(std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > &A, size_t m, size_t n, std::vector< size_t > &pivot_col_for_row, int &sign)
对增广矩阵进行高斯消元
A 增广矩阵（符号表达式元素） m 行数 n 列数 pivot_col_for_row 输出各行的主元列号 sign 输出行交换的符号（+1 或 -1）
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power.
Referenced by lamina::Solver::solve_linear_system, SymbolicExpr::solve_system.
T lamina::gcd_coeff_impl(const T &a, const T &b)
计算两个系数的最大公约数（泛型实现）
T 系数类型 a 第一个系数 b 第二个系数 gcd(a, b)
References BigInt::gcd, Rational.
Referenced by lamina::Polynomial< CoeffType >::gcd.
std::vector< int64_t > lamina::generate_good_primes(int count, const std::vector< int64_t > &leading_coeffs, uint64_t start_from=1000000000ULL)
生成指定数量的好素数
count 需要的素数个数 leading_coeffs 首项系数列表（用于过滤） start_from 搜索起始值 好素数列表
References is_good_prime.
static bool lamina::get_integer_value(const std::shared_ptr< SymbolicNode > &node, long long &value)
References num.
Referenced by collect_denominator_factors, is_polynomial_node.
std::vector< FGLMPoly > lamina::grevlex_to_lex(const std::vector< FGLMPoly > &grevlex_basis, size_t num_vars)
将 GrevLex 序下的 Gröbner 基转换为 Lex 序
grevlex_basis GrevLex 序下的 Gröbner 基 num_vars 变量个数 Lex 序下的 Gröbner 基
References fglm_convert, lamina::MonomialOrder::grevlex, lamina::MonomialOrder::lex.
static bool lamina::has_exp_k_var_terms(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
References extract_exp_multiplier, has_exp_k_var_terms.
Referenced by detect_substitution, has_exp_k_var_terms.
static bool lamina::has_integral_node_check(const std::shared_ptr< SymbolicNode > &node)
References FunctionNode::Calculus_Integral, has_integral_node_check.
Referenced by lamina::MultipleIntegralEngine::evaluate, has_integral_node_check, lamina::TableLookupStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
std::shared_ptr< SymbolicExpr > lamina::implicit_diff(std::shared_ptr< SymbolicExpr > F, const std::string &x, const std::string &y)
对隐函数 F(x, y) = 0 求 dy/dx
利用隐函数定理：dy/dx = -F_x / F_y F 隐函数表达式 F(x, y) x 自变量名 y 因变量名 dy/dx 的符号表达式
References SymbolicExpr::divide, SymbolicExpr::multiply, num, SymbolicExpr::number, DifferentiationVisitor::result.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_cos(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, make_arccos, make_pi, SymbolicExpr::multiply, SymbolicExpr::number, try_evaluate_numeric.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_exp(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::ln, try_evaluate_numeric.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_exp_base(const std::shared_ptr< SymbolicExpr > &base, const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::divide, SymbolicExpr::ln, try_evaluate_numeric.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_cos(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References make_arccos, try_evaluate_numeric.
Referenced by invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_exp(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References SymbolicExpr::ln, try_evaluate_numeric.
Referenced by invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_power(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var, int n)
References SymbolicExpr::divide, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, try_evaluate_numeric.
Referenced by invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_sin(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References make_arcsin, try_evaluate_numeric.
Referenced by invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_h_tan(const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References make_arctan.
Referenced by invert_substitution_h.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_lambert_w(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::lambertw.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_ln(const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::exp.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_sin(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, make_arcsin, make_pi, SymbolicExpr::multiply, SymbolicExpr::number, try_evaluate_numeric.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_substitution_h(const std::shared_ptr< SymbolicExpr > &h_expr, const std::shared_ptr< SymbolicExpr > &u_root, const std::string &var)
References SymbolicExpr::add, FunctionNode::Cos, depends_on_var, FunctionNode::Exp, invert_h_cos, invert_h_exp, invert_h_power, invert_h_sin, invert_h_tan, SymbolicExpr::multiply, SymbolicExpr::number, FunctionNode::Sin, SymbolicExpr::solve, FunctionNode::Tan.
Referenced by solve_transcendental_impl.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::invert_tan(const std::shared_ptr< SymbolicExpr > &c, int max_roots)
References SymbolicExpr::add, make_arctan, make_pi, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by solve_transcendental_impl.
static bool lamina::is_even_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds an even integer value.
References BigInt::is_even, is_integer_number, num.
Referenced by lamina::InferenceEngine::infer_power_property.
static bool lamina::is_exponent_neg_one(const std::shared_ptr< SymbolicNode > &node)
Helper: check if an exponent NumberNode is exactly -1 (for division detection).
References num, Rational.
Referenced by lamina::InferenceEngine::propagate_bounds.
static bool lamina::is_exponent_two(const std::shared_ptr< SymbolicNode > &node)
Helper: check if an exponent NumberNode is exactly 2 (for squaring detection).
References num, Rational.
Referenced by lamina::InferenceEngine::propagate_bounds.
bool lamina::is_good_prime(int64_t p, const std::vector< int64_t > &leading_coeffs)
判断素数 p 是否为"好素数"（不整除任何首项系数）
p 待检测素数 leading_coeffs 首项系数列表 若 p 不整除任何系数则返回 true
Referenced by generate_good_primes.
static bool lamina::is_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds an integer value.
Works for BigInt (always integer), Rational (if denominator == 1), and double (if finite and equal to its floor).
References num.
Referenced by lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property, is_even_integer_number, is_positive_integer_number.
static bool lamina::is_polynomial_node(const std::shared_ptr< SymbolicNode > &node)
References get_integer_value, is_polynomial_node.
Referenced by collect_denominator_factors, is_polynomial_node, lamina::Solver::solve_polynomial_system.
static bool lamina::is_positive_integer_number(const NumberNode &num)
Helper: check if a NumberNode holds a positive integer value (> 0).
References is_integer_number, BigInt::IsNegative, num.
Referenced by collect_power_exponents, lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property.
static bool lamina::is_purely_numeric(const std::shared_ptr< SymbolicExpr > &expr)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands.
Referenced by solve_biquadratic, solve_cubic, solve_quartic.
static bool lamina::is_wildcard(const std::shared_ptr< SymbolicNode > &node, const std::unordered_set< std::string > &wildcards, std::string &name_out)
Referenced by match_recursive.
bool lamina::is_zero_dimensional(const std::vector< FGLMPoly > &basis, size_t num_vars)
判断理想是否为零维（每个变量都有纯幂次首项）
basis Gröbner 基 num_vars 变量个数 零维返回 true
References lamina::FGLMPoly::LM.
Referenced by fglm_convert.
static bool lamina::is_zero_number(const NumberNode &num)
Helper: check if a NumberNode holds the value 0.
References num.
Referenced by lamina::InferenceEngine::infer_power_domain, lamina::InferenceEngine::infer_power_property.
static std::pair< SymbolicExpr, SymbolicExpr > lamina::isolate_linear_coeff(const SymbolicExpr &expr, const std::string &var)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_number, SymbolicFactory::create_variable, SymbolicExpr::root, to_ptr.
Referenced by lamina::Solver::solve_linear_system.
std::vector< std::pair< Rational, Rational > > lamina::isolate_real_roots(const Polynomial< Rational > &poly)
使用 Sturm 序列隔离有理系数多项式的所有实根。
poly 有理系数多项式 隔离区间列表，每个区间包含恰好一个实根
References cauchy_bound, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::is_zero, Rational, roots_in_interval, lamina::Polynomial< CoeffType >::square_free_part, lamina::Polynomial< CoeffType >::trim.
Referenced by rootof_evaluate, solve_numeric.
uint64_t lamina::lammp_gcd(uint64_t a, uint64_t b)
计算两个无符号整数的最大公约数（调用 LAMMP）
a 第一个无符号整数 b 第二个无符号整数 gcd(a, b)
bool lamina::lammp_is_prime(uint64_t n)
判断无符号整数是否为素数
n 待判断的整数 是素数返回 true
uint64_t lamina::lammp_next_prime(uint64_t n)
求大于 n 的下一个素数
n 起始值 大于 n 的最小素数
Monomial lamina::lcm_monomial(const Monomial &a, const Monomial &b)
计算两个单项式的最小公倍单项式
a 第一个单项式 b 第二个单项式 各分量取最大值构成的单项式
std::vector< std::shared_ptr< SymbolicExpr > > lamina::line_plane_intersection(const LineSymbolic &line, const PlaneSymbolic &plane)
计算直线与平面的交点
line 直线 plane 平面 交点坐标向量
References SymbolicExpr::add, lamina::PlaneSymbolic::d, lamina::LineSymbolic::direction, SymbolicExpr::divide, SymbolicExpr::multiply, lamina::PlaneSymbolic::normal, SymbolicExpr::number, lamina::LineSymbolic::point, vector_dot.
static std::shared_ptr< SymbolicExpr > lamina::make_arccos(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcCos.
Referenced by invert_cos, invert_h_cos.
static std::shared_ptr< SymbolicExpr > lamina::make_arcsin(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcSin.
Referenced by invert_h_sin, invert_sin.
static std::shared_ptr< SymbolicExpr > lamina::make_arctan(const std::shared_ptr< SymbolicExpr > &c)
References FunctionNode::ArcTan.
static std::shared_ptr< SymbolicExpr > lamina::make_arctan(const std::shared_ptr< SymbolicExpr > &op)
References FunctionNode::ArcTan.
Referenced by lamina::RationalDecompositionStrategy::integrate_term, invert_h_tan, invert_tan, lamina::PartialFractionStrategy::try_integrate.
static Endpoint lamina::make_closed_endpoint(double val)
Helper: create a closed Endpoint from a double value.
References lamina::Endpoint::closed.
Referenced by make_interval.
ComplexSymbolic lamina::make_complex(std::shared_ptr< SymbolicExpr > real, std::shared_ptr< SymbolicExpr > imag)
构造符号复数
real 实部表达式 imag 虚部表达式 符号复数对象
Referenced by complex_add, complex_conj, complex_div, complex_exp_form, complex_locus_circle, complex_locus_perpendicular_bisector, complex_mul, complex_sub, solve_complex_quadratic.
static std::shared_ptr< SymbolicExpr > lamina::make_expr_ptr(const SymbolicExpr &e)
Referenced by lamina::Integrator::check_cycle, lamina::LinearSubstitutionStrategy::extract_linear_arg, lamina::Integrator::integrate_def, lamina::Integrator::integrate_recursive, lamina::IntegrationTable::load_defaults, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::LinearSubstitutionStrategy::try_integrate, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
static Interval lamina::make_interval(double lo, double hi)
Helper: create an Interval from two double values [lo, hi].
References lamina::Interval::lower, make_closed_endpoint, lamina::Interval::upper.
Referenced by lamina::InferenceEngine::propagate_bounds.
static std::shared_ptr< SymbolicExpr > lamina::make_pi()
References SymbolicExpr::number.
Referenced by invert_cos, invert_sin, invert_tan.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::make_rootof_solutions(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
为不可约多项式构造 RootOf 解表达式列表。
poly 符号系数多项式 var 求解变量名 RootOf 表达式列表，每个元素对应多项式的一个根
References lamina::Polynomial< CoeffType >::degree, SymbolicExpr::root_of, symbolic_poly_to_expr.
Referenced by solve_by_factoring, solve_dispatch.
static bool lamina::match_commutative_recursive(const std::vector< std::shared_ptr< SymbolicNode > > &p_ops, const std::vector< std::shared_ptr< SymbolicNode > > &t_ops, std::vector< bool > &used_t, size_t p_index, const std::unordered_set< std::string > &wildcards, MatchMap &results)
References match_commutative_recursive, match_recursive.
Referenced by match_commutative_recursive, match_recursive.
static bool lamina::match_recursive(const std::shared_ptr< SymbolicNode > &p_node, const std::shared_ptr< SymbolicNode > &t_node, const std::unordered_set< std::string > &wildcards, MatchMap &results)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, is_wildcard, match_commutative_recursive, match_recursive.
Referenced by lamina::Matcher::match, match_commutative_recursive, match_recursive.
std::shared_ptr< SymbolicExpr > lamina::matrix_determinant(const std::shared_ptr< SymbolicExpr > &A)
计算符号矩阵的行列式
A 输入矩阵 行列式的符号表达式
References SymbolicExpr::determinant.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::matrix_eigenvalues(const std::shared_ptr< SymbolicExpr > &A)
计算符号矩阵的特征值
A 输入矩阵 特征值列表
std::vector< std::vector< std::shared_ptr< SymbolicExpr > > > lamina::matrix_eigenvectors(const std::shared_ptr< SymbolicExpr > &A)
计算符号矩阵的特征向量
A 输入矩阵 特征向量列表，每个特征向量为一组分量
std::shared_ptr< SymbolicExpr > lamina::matrix_inverse(const std::shared_ptr< SymbolicExpr > &A)
计算符号矩阵的逆矩阵
A 输入矩阵 逆矩阵的符号表达式
References SymbolicExpr::inverse.
std::shared_ptr< SymbolicExpr > lamina::matrix_multiply(const std::shared_ptr< SymbolicExpr > &A, const std::shared_ptr< SymbolicExpr > &B)
计算两个符号矩阵的乘积
A 左矩阵 B 右矩阵 乘积矩阵的符号表达式
References SymbolicExpr::multiply.
std::shared_ptr< SymbolicExpr > lamina::matrix_reflection(double angle, int dim=2)
生成反射矩阵
angle 反射轴角度（弧度） dim 矩阵维度，默认为 2 反射矩阵的符号表达式
References SymbolicExpr::add, SymbolicExpr::matrix, SymbolicExpr::multiply, SymbolicExpr::number.
std::shared_ptr< SymbolicExpr > lamina::matrix_rotation(double theta, int dim=2)
生成旋转矩阵
theta 旋转角度（弧度） dim 矩阵维度，默认为 2 旋转矩阵的符号表达式
References SymbolicExpr::matrix, SymbolicExpr::multiply, SymbolicExpr::number.
std::shared_ptr< SymbolicExpr > lamina::matrix_scaling(double sx, double sy, int dim=2)
生成缩放矩阵
sx x 方向缩放因子 sy y 方向缩放因子 dim 矩阵维度，默认为 2 缩放矩阵的符号表达式
References SymbolicExpr::matrix, SymbolicExpr::number.
static Endpoint lamina::max_upper(const Endpoint &a, const Endpoint &b)
References compare_endpoints_upper.
Referenced by lamina::IntervalUnion::normalize.
std::pair< int64_t, int64_t > lamina::multi_crt(const std::vector< int64_t > &residues, const std::vector< int64_t > &primes)
多模数中国剩余定理
residues 余数列表 primes 对应的模数列表（两两互素） pair(合并余数, 合并模数) std::invalid_argument 若输入为空或大小不匹配
References crt.
static std::shared_ptr< SymbolicExpr > lamina::multiply_factors(const std::vector< std::shared_ptr< SymbolicNode > > &factors)
References SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::Solver::solve_polynomial_system.
static std::shared_ptr< SymbolicExpr > lamina::multiply_no_expand(const std::shared_ptr< SymbolicNode > &term, const std::vector< std::shared_ptr< SymbolicNode > > &den_factors)
References add_number_nodes, multiply_number_nodes, num, SymbolicExpr::number.
Referenced by lamina::Solver::solve_polynomial_system.
static std::shared_ptr< NumberNode > lamina::multiply_number_nodes(const std::shared_ptr< NumberNode > &a, const std::shared_ptr< NumberNode > &b)
References Rational.
Referenced by multiply_no_expand.
static std::shared_ptr< SymbolicExpr > lamina::negate(const std::shared_ptr< SymbolicExpr > &x)
References SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by solve_biquadratic, solve_cubic, solve_linear_internal, solve_quadratic_internal, solve_quartic, sub.
std::optional< NumericRoot > lamina::newton_raphson(const std::shared_ptr< SymbolicExpr > &f, const std::shared_ptr< SymbolicExpr > &df, const std::string &var, lmmc_real_t x0, const SolveOptions &opts)
Newton-Raphson 迭代求根（无区间约束）。
f 目标函数表达式 df 目标函数的导数表达式 var 求解变量名 x0 迭代初始值 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
Referenced by rootof_evaluate, solve_numeric.
std::optional< NumericRoot > lamina::newton_raphson(const std::shared_ptr< SymbolicExpr > &f, const std::shared_ptr< SymbolicExpr > &df, const std::string &var, lmmc_real_t x0, lmmc_real_t bracket_lo, lmmc_real_t bracket_hi, const SolveOptions &opts)
Newton-Raphson 迭代求根（带区间约束，迭代超出区间时回退到二分法）。
f 目标函数表达式 df 目标函数的导数表达式 var 求解变量名 x0 迭代初始值 bracket_lo 搜索区间下界 bracket_hi 搜索区间上界 opts 求解选项 收敛时返回数值根，否则返回 nullopt
References bisection, lamina::SolveOptions::max_newton_iterations, SymbolicExpr::number, lamina::SolveOptions::tolerance.
static bool lamina::nodes_equal(const std::shared_ptr< SymbolicNode > &a, const std::shared_ptr< SymbolicNode > &b)
Referenced by decompose_lambert_w_pattern.
FGLMPoly lamina::normal_form(const FGLMPoly &f, const std::vector< FGLMPoly > &basis, const MonomialOrder &order)
计算多项式关于基的标准形（余式）
f 待约化多项式 basis Gröbner 基 order 单项式序 标准形
References lamina::FGLMPoly::reduce.
Referenced by fglm_convert.
static std::shared_ptr< SymbolicExpr > lamina::num(int n)
References SymbolicExpr::number.
Referenced by determine_leading_sign, lamina::anonymous_namespace{solver.cpp}::div_mono, lamina::QueryInterface::get_infinity_sign, get_integer_value, implicit_diff, lamina::TrigCombinationStrategy::integrate_even_case, lamina::TrigCombinationStrategy::integrate_odd_case, is_even_integer_number, is_exponent_neg_one, is_exponent_two, is_integer_number, is_positive_integer_number, is_zero_number, multiply_no_expand, lamina::InferenceEngine::propagate_bounds, lamina::InferenceEngine::query_integer, lamina::QueryInterface::query_integer, lamina::InferenceEngine::query_negative, lamina::QueryInterface::query_negative, lamina::InferenceEngine::query_nonnegative, lamina::QueryInterface::query_nonnegative, lamina::InferenceEngine::query_nonpositive, lamina::InferenceEngine::query_nonzero, lamina::QueryInterface::query_nonzero, lamina::InferenceEngine::query_positive, lamina::QueryInterface::query_positive, lamina::InferenceEngine::query_real, lamina::QueryInterface::query_real, lamina::anonymous_namespace{integration.cpp}::rd_collect_rational, solve_cubic, solve_linear1_ode, lamina::InequalitySolver::solve_parametric_inequality, solve_quadratic_internal, solve_quartic, sym_rational, lamina::anonymous_namespace{integration.cpp}::trig_rational, lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value, lamina::PartialFractionStrategy::try_integrate, lamina::anonymous_namespace{solver.cpp}::ContainsImaginaryVisitor::visit.
static std::shared_ptr< SymbolicExpr > lamina::num_r(int p, int q)
References SymbolicExpr::number, Rational.
std::ostream & lamina::operator<<(std::ostream &os, const Polynomial< T > &p)
多项式流输出运算符
T 系数类型 os 输出流 p 多项式 输出流引用
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::variable_name.
static bool lamina::parse_endpoint_value(const std::string &str, size_t &pos, Endpoint &ep)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, parse_numeric_value, skip_ws, starts_with_at, lamina::Endpoint::value.
Referenced by parse_single_interval.
static std::shared_ptr< SymbolicExpr > lamina::parse_numeric_value(const std::string &str, size_t &pos)
References SymbolicExpr::number.
Referenced by parse_endpoint_value.
static bool lamina::parse_single_interval(const std::string &str, size_t &pos, Interval &iv)
References lamina::Endpoint::is_neg_infinity, lamina::Endpoint::is_open, lamina::Endpoint::is_pos_infinity, lamina::Interval::lower, parse_endpoint_value, skip_ws, lamina::Interval::upper.
Referenced by lamina::IntervalUnion::parse.
PlaneSymbolic lamina::plane_general(std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b, std::shared_ptr< SymbolicExpr > c, std::shared_ptr< SymbolicExpr > d)
由一般方程系数构造平面 ax + by + cz = d
a x 方向法向量分量 b y 方向法向量分量 c z 方向法向量分量 d 常数项 构造的 PlaneSymbolic 对象
std::shared_ptr< SymbolicExpr > lamina::point_plane_distance(const std::vector< std::shared_ptr< SymbolicExpr > > &point, const PlaneSymbolic &plane)
计算点到平面的距离
point 空间点坐标 plane 平面 距离的符号表达式
References FunctionNode::Abs, SymbolicExpr::add, lamina::PlaneSymbolic::d, SymbolicExpr::divide, SymbolicExpr::multiply, lamina::PlaneSymbolic::normal, SymbolicExpr::number, SymbolicExpr::sqrt, vector_dot.
std::shared_ptr< SymbolicExpr > lamina::poly_to_symbolic(const Polynomial< T > &poly)
将一元多项式转换为符号表达式
T 系数类型 poly 一元多项式 对应的符号表达式
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, lamina::Polynomial< CoeffType >::variable_name.
Referenced by SymbolicExpr::poly_gcd, solve_numeric.
static std::vector< BigInt > lamina::positive_divisors(const BigInt &n)
References BigInt::Abs, BigInt::is_zero.
Referenced by find_rational_roots.
int lamina::quotient_dimension(const std::vector< FGLMPoly > &basis, size_t num_vars, int max_degree=50)
计算商空间维数（标准单项式个数）
basis Gröbner 基 num_vars 变量个数 max_degree 搜索的最大次数上限 商空间维数；无法确定时返回 -1
References divides_monomial.
Referenced by fglm_convert.
std::pair< int64_t, int64_t > lamina::rational_reconstruction(int64_t x, int64_t m)
有理数重构：从模像 x mod m 恢复有理数 a/b
x 模像值 m 模数 pair(分子 a, 分母 b)；失败时返回 (0, 0)
References extended_gcd.
static Polynomial< SymbolicPolyCoeff > lamina::rational_to_symbolic_poly(const Polynomial< Rational > &rat_poly)
References lamina::Polynomial< CoeffType >::coeffs, SymbolicExpr::number, lamina::Polynomial< CoeffType >::variable_name.
Referenced by solve_by_factoring.
static std::shared_ptr< SymbolicNode > lamina::rewrite_exp_as_u_power(const std::shared_ptr< SymbolicNode > &node, const std::string &var, const std::string &u_var)
References SymbolicFactory::create_add, SymbolicFactory::create_multiply, SymbolicFactory::create_power, extract_exp_multiplier, rewrite_exp_as_u_power.
Referenced by detect_substitution, rewrite_exp_as_u_power.
static bool lamina::root_less_than(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
Referenced by lamina::InequalitySolver::solve_parametric_inequality, lamina::InequalitySolver::solve_rational_inequality.
std::optional< lmmc_real_t > lamina::rootof_evaluate(const std::shared_ptr< SymbolicExpr > &rootof_expr)
对 RootOf 表达式进行数值求值。
rootof_expr RootOf 符号表达式 若求值成功则返回数值结果，否则返回 nullopt
References isolate_real_roots, lamina::SolveOptions::max_newton_iterations, newton_raphson, SymbolicExpr::number, FunctionNode::RootOf, lamina::SolveOptions::tolerance, try_convert_to_rational_poly.
std::shared_ptr< SymbolicExpr > lamina::rootof_simplify(const std::shared_ptr< SymbolicExpr > &rootof_expr)
化简 RootOf 表达式（如可用根式表示则转换为闭式）。
rootof_expr RootOf 符号表达式 化简后的符号表达式
References FunctionNode::RootOf, rootof_simplify, solve_closed_form_from_poly, sort_roots_by_convention.
Referenced by rootof_simplify.
static bool lamina::roots_equal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
Referenced by lamina::InequalitySolver::select_intervals, lamina::InequalitySolver::solve_inequality, lamina::InequalitySolver::solve_rational_inequality.
static int lamina::roots_in_interval(const std::vector< Polynomial< Rational > > &sturm, const Rational &a, const Rational &b)
References sturm_sign_changes_at.
Referenced by isolate_real_roots.
std::shared_ptr< SymbolicExpr > lamina::skew_lines_distance(const LineSymbolic &l1, const LineSymbolic &l2)
计算两条异面直线之间的距离
l1 第一条直线 l2 第二条直线 距离的符号表达式
References FunctionNode::Abs, SymbolicExpr::add, lamina::LineSymbolic::direction, SymbolicExpr::divide, SymbolicExpr::multiply, SymbolicExpr::number, lamina::LineSymbolic::point, SymbolicExpr::sqrt, vector_cross, vector_dot.
static size_t lamina::skip_ws(const std::string &str, size_t pos)
Referenced by lamina::IntervalUnion::parse, parse_endpoint_value, parse_single_interval.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_biquadratic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::string &var)
求解双二次方程 ax⁴ + bx² + c = 0。
a 四次项系数 b 二次项系数 c 常数项 var 求解变量名 所有根的符号表达式列表
References is_purely_numeric, negate, SymbolicExpr::number, solve_quadratic_internal, SymbolicExpr::sqrt.
Referenced by solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_by_factoring(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
通过因式分解求解多项式方程。
poly 符号系数多项式 var 求解变量名 所有根的符号表达式列表
References convert_to_rational_poly, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::div_mod, find_rational_roots, lamina::Polynomial< CoeffType >::is_zero, make_rootof_solutions, SymbolicExpr::number, Rational, rational_to_symbolic_poly, solve_closed_form_poly, square_free_factorization.
Referenced by find_roots_with_multiplicity, solve_dispatch, solve_symbolic_poly.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_closed_form_from_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, solve_cubic, solve_quartic, SymbolicExpr::sqrt.
Referenced by rootof_simplify.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_closed_form_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &var)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, SymbolicExpr::multiply, SymbolicExpr::number, solve_cubic, solve_quadratic_internal, solve_quartic.
Referenced by solve_by_factoring.
std::vector< ComplexSymbolic > lamina::solve_complex_nth_root(std::shared_ptr< SymbolicExpr > c, int n)
求复数 c 的 n 次方根
c 被开方的复数表达式 n 根的次数 n 个复数根的列表
References complex_exp_form, SymbolicExpr::number.
std::vector< ComplexSymbolic > lamina::solve_complex_quadratic(std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b, std::shared_ptr< SymbolicExpr > c)
求复系数一元二次方程 az^2 + bz + c = 0 的根
a 二次项系数 b 一次项系数 c 常数项 两个复数根
References SymbolicExpr::add, complex_div, make_complex, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::sqrt.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_cubic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::string &var)
使用三次公式求解三次方程 ax³ + bx² + cx + d = 0。
a 三次项系数 b 二次项系数 c 一次项系数 d 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, cbrt_expr, SymbolicExpr::divide, is_purely_numeric, SymbolicExpr::multiply, negate, num, SymbolicExpr::number, SymbolicExpr::power, solve_linear_internal, solve_quadratic_internal, SymbolicExpr::sqrt, sub.
Referenced by solve_closed_form_from_poly, solve_closed_form_poly, solve_polynomial_closed, solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_dispatch(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, const SolveOptions &opts)
方程求解策略调度器，根据表达式类型选择合适的求解方法。
expr 待求解的表达式（视为等于零） var 求解变量名 opts 求解选项 所有根的符号表达式列表
References SymbolicExpr::add, lamina::SolveOptions::allow_numeric, RelationalNode::EQ, make_rootof_solutions, SymbolicExpr::multiply, SymbolicExpr::number, lamina::SolveOptions::return_rootof, solve_by_factoring, solve_numeric, solve_polynomial_closed, solve_transcendental.
Referenced by SymbolicExpr::solve.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_inner_equation(const std::shared_ptr< SymbolicExpr > &inner, const std::shared_ptr< SymbolicExpr > &value, const std::string &var, int depth)
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::solve, solve_transcendental_impl.
Referenced by solve_transcendental_impl.
std::shared_ptr< SymbolicExpr > lamina::solve_linear1_ode(std::shared_ptr< SymbolicExpr > Px, std::shared_ptr< SymbolicExpr > Qx, const std::string &x, const std::string &y)
求解一阶线性 ODE：dy/dx + P(x)*y = Q(x)
Px 系数函数 P(x) Qx 非齐次项 Q(x) x 自变量名 y 因变量名 通解的符号表达式
References SymbolicExpr::add, SymbolicExpr::divide, SymbolicExpr::exp, SymbolicExpr::multiply, num, SymbolicExpr::variable.
Referenced by solve_linear2_ode.
std::shared_ptr< SymbolicExpr > lamina::solve_linear2_ode(double a, double b, double c, std::shared_ptr< SymbolicExpr > fx, const std::string &x, const std::string &y)
求解二阶常系数线性 ODE：a*y'' + b*y' + c*y = f(x)
a 二阶导数系数 b 一阶导数系数 c 零阶项系数 fx 非齐次项 f(x) x 自变量名 y 因变量名 通解的符号表达式
References SymbolicExpr::add, SymbolicExpr::cos, SymbolicExpr::divide, SymbolicExpr::exp, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::sin, solve_linear1_ode, SymbolicExpr::variable.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_linear_internal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
References SymbolicExpr::divide, negate.
Referenced by solve_cubic.
std::vector< NumericRoot > lamina::solve_numeric(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, const SolveOptions &opts={})
对表达式进行数值求根，综合使用 Newton-Raphson 和根隔离方法。
expr 待求根的表达式（视为等于零） var 求解变量名 opts 求解选项（容差、最大迭代次数等） 数值根列表
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, Rational::from_double, lamina::SolveOptions::has_initial_guess, lamina::SolveOptions::initial_guess, isolate_real_roots, lamina::SolveOptions::max_roots, newton_raphson, SymbolicExpr::number, poly_to_symbolic, Rational, lamina::NumericRoot::residual, lamina::SolveOptions::tolerance, lamina::NumericRoot::value, lamina::Polynomial< CoeffType >::variable_name.
Referenced by solve_dispatch.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_quadratic_internal(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c)
References SymbolicExpr::add, SymbolicExpr::divide, SymbolicExpr::multiply, negate, num, SymbolicExpr::power, SymbolicExpr::sqrt, sub.
Referenced by solve_biquadratic, solve_closed_form_poly, solve_cubic, solve_quartic.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_quartic(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b, const std::shared_ptr< SymbolicExpr > &c, const std::shared_ptr< SymbolicExpr > &d, const std::shared_ptr< SymbolicExpr > &e, const std::string &var)
使用四次公式求解四次方程 ax⁴ + bx³ + cx² + dx + e = 0。
a 四次项系数 b 三次项系数 c 二次项系数 d 一次项系数 e 常数项 var 求解变量名 所有根的符号表达式列表
References SymbolicExpr::add, SymbolicExpr::divide, is_purely_numeric, SymbolicExpr::multiply, negate, num, SymbolicExpr::number, SymbolicExpr::power, solve_biquadratic, solve_cubic, solve_quadratic_internal, SymbolicExpr::sqrt, sub.
Referenced by solve_closed_form_from_poly, solve_closed_form_poly, solve_polynomial_closed.
std::shared_ptr< SymbolicExpr > lamina::solve_separable_ode(std::shared_ptr< SymbolicExpr > rhs, const std::string &x, const std::string &y)
求解可分离变量型 ODE：dy/dx = rhs(x, y)
rhs 方程右端表达式 x 自变量名 y 因变量名 通解的符号表达式
References SymbolicExpr::add, SymbolicExpr::divide, SymbolicExpr::multiply, SymbolicExpr::number.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_symbolic_poly(const Polynomial< SymbolicPolyCoeff > &poly, const std::string &variable)
References lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, SymbolicExpr::divide, get_coeff, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, solve_by_factoring.
Referenced by lamina::InequalitySolver::solve_parametric_inequality.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_transcendental(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
求解超越方程（三角、指数、对数类型）。
expr 待求解的表达式（视为等于零） var 求解变量名 所有根的符号表达式列表
References solve_transcendental_impl.
Referenced by solve_dispatch.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_transcendental_impl(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var, int depth)
References FunctionNode::Cos, decompose_exp_base_pattern, decompose_lambert_w_pattern, decompose_trig_exp_pattern, detect_substitution, FunctionNode::Exp, invert_cos, invert_exp, invert_exp_base, invert_lambert_w, invert_ln, invert_sin, invert_substitution_h, invert_tan, FunctionNode::Ln, lamina::SolveOptions::max_roots, MAX_TRANSCENDENTAL_DEPTH, FunctionNode::Sin, SymbolicExpr::solve, solve_inner_equation, FunctionNode::Tan.
Referenced by solve_inner_equation, solve_transcendental.
std::vector< std::shared_ptr< SymbolicExpr > > lamina::solve_with_assumptions(const std::shared_ptr< SymbolicExpr > &equation, const std::string &variable, const AssumptionContext *ctx=nullptr)
Solve an equation with assumption-based domain filtering.
Calls the existing SymbolicExpr::solve() to compute all solutions, then applies domain filtering based on the variable's declared domain in the AssumptionContext. Solutions that violate the domain constraint are excluded. Domain filtering rules: Real: exclude solutions containing sqrt(-1) or non-real numeric values PositiveInt: exclude non-integer or <= 0 solutions NonNegative (Natural): exclude solutions evaluating to < 0 equation The equation to solve (equal to zero, or RelationalNode) variable The variable name to solve for ctx Optional assumption context; if nullptr, all solutions returned unfiltered Filtered solutions preserving original order
References Complex, lamina::anonymous_namespace{solver.cpp}::contains_imaginary, lamina::AssumptionContext::get_domain, lamina::AssumptionContext::has_sign, Integer, lamina::anonymous_namespace{solver.cpp}::is_integer_value, Natural, Negative, NonNegative, NonPositive, Positive, PositiveInt, Rational, Real, SymbolicExpr::solve, lamina::anonymous_namespace{solver.cpp}::try_get_numeric_value.
static std::vector< std::shared_ptr< SymbolicExpr > > lamina::sort_roots_by_convention(const std::vector< std::shared_ptr< SymbolicExpr > > &roots)
References lamina::RootWithIndex::eval_success, lamina::RootWithIndex::expr, lamina::RootWithIndex::imag_part, lamina::RootWithIndex::is_real, lamina::RootWithIndex::real_part, try_eval_complex.
Referenced by rootof_simplify.
std::vector< std::pair< Polynomial< Rational >, int > > lamina::square_free_factorization(const Polynomial< Rational > &poly)
对有理系数多项式进行无平方因子分解。
poly 有理系数多项式 因子与重数的列表
References lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::differentiate, lamina::Polynomial< CoeffType >::div_mod, lamina::Polynomial< CoeffType >::gcd, lamina::Polynomial< CoeffType >::is_zero, lamina::Polynomial< CoeffType >::make_monic.
Referenced by lamina::RationalDecompositionStrategy::factor_denominator, find_roots_with_multiplicity, solve_by_factoring.
static bool lamina::starts_with_at(const std::string &str, size_t pos, const std::string &prefix)
Referenced by lamina::IntervalUnion::parse, parse_endpoint_value.
static int lamina::sturm_sign_changes_at(const std::vector< Polynomial< Rational > > &sturm, const Rational &x)
References count_sign_changes.
Referenced by roots_in_interval.
static int lamina::sturm_sign_changes_at_neg_inf(const std::vector< Polynomial< Rational > > &sturm)
References count_sign_changes.
static int lamina::sturm_sign_changes_at_pos_inf(const std::vector< Polynomial< Rational > > &sturm)
References count_sign_changes.
static std::shared_ptr< SymbolicExpr > lamina::sub(const std::shared_ptr< SymbolicExpr > &a, const std::shared_ptr< SymbolicExpr > &b)
References SymbolicExpr::add, negate.
Referenced by solve_cubic, lamina::Solver::solve_polynomial_system, solve_quadratic_internal, solve_quartic.
static std::shared_ptr< SymbolicExpr > lamina::sym_rational(long long num, long long den)
References num, SymbolicExpr::number, Rational.
Referenced by lamina::IntegrationTable::load_defaults, lamina::PowerRuleStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > lamina::sym_sub(const SymbolicExpr &a, const SymbolicExpr &b)
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by lamina::MultipleIntegralEngine::evaluate, lamina::Integrator::integrate_def, lamina::IntegrationTable::load_defaults, lamina::Integrator::resolve_cycle, lamina::PartialFractionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
static std::shared_ptr< SymbolicExpr > lamina::symbolic_poly_to_expr(const Polynomial< SymbolicPolyCoeff > &poly)
References SymbolicExpr::add, lamina::Polynomial< CoeffType >::coeffs, lamina::Polynomial< CoeffType >::degree, lamina::Polynomial< CoeffType >::is_zero, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power, SymbolicExpr::variable, lamina::Polynomial< CoeffType >::variable_name.
Referenced by make_rootof_solutions.
Polynomial< T > lamina::symbolic_to_poly(const std::shared_ptr< SymbolicExpr > &expr, const std::string &var)
将符号表达式转换为一元多项式
T 系数类型 expr 符号表达式 var 主变量名 对应的一元多项式
Polynomial< T > lamina::symbolic_to_poly_recursive(const std::shared_ptr< SymbolicNode > &node, const std::string &var)
递归地将符号节点转换为一元多项式
T 系数类型 node 符号节点 var 主变量名 对应的一元多项式
References depends_on_var, BigInt::IsNegative, BigInt::to_int.
static std::shared_ptr< SymbolicExpr > lamina::to_ptr(const SymbolicExpr &expr)
Referenced by isolate_linear_coeff, lamina::Solver::solve_polynomial_system.
int lamina::total_degree(const Monomial &m)
计算单项式的全次数
m 单项式 各分量指数之和
Referenced by lamina::MonomialOrder::compare_deglex, lamina::MonomialOrder::compare_grevlex, lamina::detail::MonomialEnumerator::next.
static bool lamina::try_convert_to_rational_poly(const Polynomial< SymbolicPolyCoeff > &sym_poly, Polynomial< Rational > &out_poly)
References lamina::Polynomial< CoeffType >::coeffs, expr_has_free_variables, Rational::from_double, Rational, lamina::Polynomial< CoeffType >::trim, lamina::Polynomial< CoeffType >::variable_name.
Referenced by rootof_evaluate.
static std::pair< std::complex< double >, bool > lamina::try_eval_complex(const std::shared_ptr< SymbolicExpr > &expr)
Referenced by sort_roots_by_convention.
static bool lamina::try_evaluate_numeric(const std::shared_ptr< SymbolicExpr > &expr, lmmc_real_t &out)
References FunctionNode::arguments, PowerNode::base, PowerNode::exponent, AddNode::operands, MultiplyNode::operands.
Referenced by decompose_exp_base_pattern, invert_cos, invert_exp, invert_exp_base, invert_h_cos, invert_h_exp, invert_h_power, invert_h_sin, invert_sin.
static bool lamina::valid_dependency(const SymbolicExpr &expr, const std::string &var)
References SymbolicExpr::differentiate.
Referenced by lamina::Integrator::apply_linearity, lamina::Integrator::check_cycle, lamina::Integrator::integrate_recursive, lamina::Integrator::resolve_cycle, lamina::PowerRuleStrategy::try_integrate, lamina::SubstitutionStrategy::try_integrate, lamina::IBPStrategy::try_integrate.
double lamina::vector_angle(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个向量的夹角（弧度）
a 向量 a 的各分量 b 向量 b 的各分量 夹角的数值（弧度）
std::vector< std::shared_ptr< SymbolicExpr > > lamina::vector_cross(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个三维符号向量的叉积
a 向量 a 的各分量 b 向量 b 的各分量 叉积结果向量的各分量
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number.
Referenced by skew_lines_distance.
std::shared_ptr< SymbolicExpr > lamina::vector_dot(const std::vector< std::shared_ptr< SymbolicExpr > > &a, const std::vector< std::shared_ptr< SymbolicExpr > > &b)
计算两个符号向量的点积
a 向量 a 的各分量 b 向量 b 的各分量 点积结果的符号表达式
References SymbolicExpr::multiply.
Referenced by line_plane_intersection, point_plane_distance, skew_lines_distance.
std::shared_ptr< SymbolicExpr > lamina::volume_of_revolution_x(std::shared_ptr< SymbolicExpr > fx, std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b)
计算函数 f(x) 绕 x 轴旋转所得旋转体的体积
fx 被旋转的函数表达式 f(x) a 积分下限 b 积分上限 旋转体体积的符号表达式
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power.
std::shared_ptr< SymbolicExpr > lamina::volume_of_revolution_y(std::shared_ptr< SymbolicExpr > fy, std::shared_ptr< SymbolicExpr > a, std::shared_ptr< SymbolicExpr > b)
计算函数 f(y) 绕 y 轴旋转所得旋转体的体积
fy 被旋转的函数表达式 f(y) a 积分下限 b 积分上限 旋转体体积的符号表达式
References SymbolicExpr::add, SymbolicExpr::multiply, SymbolicExpr::number, SymbolicExpr::power.
SymbolicExpr lamina::wildcard(const std::string &name)
创建通配符表达式
name 通配符名称 表示通配符的符号表达式
References SymbolicFactory::create_variable.
Referenced by lamina::IntegrationTable::load_defaults.